### ISSUE TITLE
Implement Javelin launcher limitations

### ISSUE THREAD

**Issue by jaynus** [acemod/ACE3#1058]
https://en.wikipedia.org/wiki/FGM-148_Javelin#Disadvantages
- [ ] thermal cooldown
- [ ] ???

**Comment by cych** [comment]
lock on for IR mode requirement :

- Forced Thermal View
- Forced NFOV
- ability to lock-on non thermal target by simple click :

http://en.wikipedia.org/wiki/FGM-148_Javelin

"...The tracker is key to guidance/control for an eventual hit. The signals from each of the 4,096 detector elements (64x64 pixel array) in the seeker are passed to the FPA readout integrated circuits which reads then creates a video frame that is sent to the tracker system for processing. By comparing the individual frames the tracker determines the need to correct so as to keep the missile on target. The tracker must be able to determine which portion of the image represents the target. The target is initially defined by the gunner who places a configurable frame around it. The tracker then uses algorithms to compare that region of the frame based on image, geometric, and movement data to the new image frames being sent from the seeker, similar to pattern recognition algorithms. At the end of each frame the reference is updated. The tracker is able to keep track of the target even though the seeker’s point of view can change radically in the course of flight."

**Comment by jaynus** [comment]
Everything you listed is already implemented....

**Comment by jaynus** [comment]
This ticket was referencing thermal cool down

**Comment by LorenLuke** [comment]
Automatic filtering of view when zoomed in, optional 'view through seeker' with correct display light, green/black-hot thermal imaging.

http://www.globalsecurity.org/military/library/policy/army/fm/3-22-37/chap4.htm#14

**Comment by ElTyranos** [comment]
I shot some times on Javelin simulator when my country decided to buy Javelins for Afghanistan (as ATGM operator). The lock-on is not automatic. You have to scale a rectangle (with a D-Pad) to the size of the target you're aiming so that the missile can "learn" its global IR signature, wich it will aim once flying.
This makes it pretty hard to lock (for a beginner) if the vehicle is changing from front to profile views as you have to adapt the size of this rectangle. 
Once the rectangle is sized, you have to follow the target a few seconds so the system can lock it, then fire.
Not a simple "reticle + lock button" as in the video above.

**Comment by Dobakjang** [comment]
I recommend to see operation flash point sereies Javeline.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
