### ISSUE TITLE
PIP optics in triple monitor broken

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#1121]
ACE3 Version: 3.0.0.2 50abf643

**Mods:**
* `@cba_a3`
* `@ace3`
* `@task_force_radio`

**~~Placed~~ ACE3 ~~Modules~~ userconfig:**
* Advanced Ballistics
  * Advanced Ballistics (Boolean): `Yes`
* BlueForceTracking 
  * `Enabled`
* Medical Settings
  * Medical Level (Option): `Advanced`
* MK6 Settings
  * `Enabled`

**Description:**
When paying in triple monitor setup PIP optics are broken, as seen in this screenshot:
http://i.imgur.com/JXbzbPC.jpg

**Steps to reproduce:**
* Play with 3 monitors
* Attach a PIP optic
* Watch the weirdness?

**Where did the issue occur?**
Multiplayer - Dedicated Server

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
@jonpas

If you wouldn't mind, could you test this version http://www.filedropper.com/aceoptics

based on 031e48dce727d10106a71344e4c88df6b967cffc

**Comment by jonpas** [comment]
I don't have triple head myself, but I'll relay to a community member that reported it to me to test it.

**Comment by PabstMirror** [comment]
Seems like anyone can run the game in 1440x440 allowing you to see the problem in "tipple head" mode.

The problem is the optics's p3d doesn't cover the side monitors.  Here's 2 screen shots showing what's going on:

![2015-05-12_00003](https://cloud.githubusercontent.com/assets/9376747/7599494/1313046a-f8c8-11e4-94e1-759b0780244a.jpg)
![2015-05-12_00002](https://cloud.githubusercontent.com/assets/9376747/7599496/1b64b47e-f8c8-11e4-8afd-83c4d7ad8e97.jpg)

My idea is to just fill the side bars with a black box.
Unless there is a way to get the optics.p3d to cover all the monitors?

**Comment by jonpas** [comment]
Ooh, hacky triple head for testing, nice find!

**Comment by jaynus** [comment]
we could try testing an optics p3d at higher resolutions and see what it looks like?

**Comment by PabstMirror** [comment]
Should be improved by commit 30adc2d463846011f8a31646b07a3c52a5dcf7ec
