### ISSUE TITLE
Flash and sound suppressor produce too much muzzle flash

### ISSUE THREAD

**Issue by ShocknAw3** [acemod/ACE3#1194]
ACE3 Version: 3.0.0.3

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
When mounting a flash suppressor or a sound suppressor on, for example, the MX, the weapon still produces an abnormally large muzzle flash. The player character and the surrounding area gets lit up heavily, albeit less so than without one. Videos like this (https://www.youtube.com/watch?v=q-4hlP5oz_o) and this (https://www.youtube.com/watch?v=ZM5ih_c_4yo) show that the muzzle flash should be far smaller.

**Steps to reproduce:**
* Attach a flash or sound suppressor to a regular MX and fire off the weapon at night in first and third person

**Where did the issue occur?**
Singleplayer and Multiplayer

**RPT log file:**
N/A

**Comment by esteldunedain** [comment]
I don't we can fix that without (legal) access to the vanilla models.

**Comment by ace3mod** [comment]
Hello!

We're automatically closing this issue since it has not received any updates or comments in the past 14 days. We therefore assume that the original reporter has lost interest or the issue has been resolved.

If this has been closed in erorr,  please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested. 

Thanks!
