### ISSUE TITLE
How to set unconcious time in 3.0 release?

### ISSUE THREAD

**Issue by ESUSSanchez** [acemod/ACE3#1202]
Hi, las unsupported version have a parameter to set max unconcious time. But in this release no parameter on the module to set the maximum time to unconsciousness like in AGM and its more realistic than a simple revive script with mouse scroll. 

This parameter provides more gameplay with basic medical system for games with few slots. 

Thanks!!

**Comment by Grollig** [comment]
The Revive module might be what you're looking for. Though you should note, that the "prevent instant death" feature in conjunction with the Revive modul is broken at the moment. This has already been fixed by glowbal and there might (!) be a hotfix release of ACE3 shortly (depending on devs' decision).

**Comment by ESUSSanchez** [comment]
Many thanks!!!

**Comment by esteldunedain** [comment]
> Though you should note, that the "prevent instant death" feature in conjunction with the Revive modul is broken at the moment. 

It was fixed on version 3.0.1 released yesterday.
