### ISSUE TITLE
Create ACE Zeus Modules

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#130]
This is something I would like to do probably post 0.1.0. In the spirit of the Ares Mod (https://github.com/astruyk/Ares), have extra runtime modules that Zeus can use during the mission to call ACE API functions.

E.g.:

- [x] Knockout or wake up units
- [ ] Change unit health status
- [x] Make units surrender
- [x] Set/unset unit captivity
- [ ] Change weather
- [x] Make Explosives compatible with ACE disarm

**Comment by ulteq** [comment]
:+1:

**Comment by SilentSpike** [comment]
Working on this.

**Comment by SilentSpike** [comment]
Testing isn't possible as long as #1209 isn't fixed

**Comment by jaynus** [comment]
#1209 is merged

**Comment by SilentSpike** [comment]
About the weather module, what functionality is desired that isn't provided by the vanilla one?

**Comment by esteldunedain** [comment]
> About the weather module, what functionality is desired that isn't provided by the vanilla one?

We probably need it modify our internal weather simulation by calling some api function we don't currently have. Unless it only changes overcast, fog and time of day, in which case it would already be compatible.

**Comment by SilentSpike** [comment]
The vanilla one uses setFog, setRain and setOvercast only. Is that acceptable?

**Comment by esteldunedain** [comment]
No, setRain will not work as intended. It will probably make it rain for a few secs, before it's ovewritten by the weather simulation. We make it rain start/stop automatically from the overcast value. If we really need to for it to rain 100% reliably when the weather is set we need to modify weather fnc_updateAceWeather.sqf.

**Comment by jaynus** [comment]
This has been a point of confusion in the past week or so:

ACE Weather - Creates random weather based on the maps regional location information. This is basically the ACE implementation of the random weather setting
ACE Weather Sync - Synchronizes weather correctly across clients

A. will have problems with zeus set weather. B will not and will just augment anything setting weather on the server.

@esteldunedain What you are talking about is adding API ability to properly set weather in tandem with A; correct?

**Comment by esteldunedain** [comment]
No, I don't think that's how it works. There's no clear distinction between those two syncs on the code. Syncing weather correctly requires that we generate it ourselves, cause you need to know not only the current weather of the server but the *forecasted* weather too. Otherwise, you'd have to sync the weather mostly every frame to broadcast whatever the server happens to randomize, creating heavy network traffic.

The only condition in which syncing weather without simulating it would be acceptable would be if you set all the weather deterministically on the mission, so Arma doesn't randomize anything. But at that point syncing wouldn't be required either.

Anyway, all that is a description of how ACE2 weather worked. There's been recently some modifications on the ACE3 pbo that I don't fully understand, which may have changed this slightly.

**Comment by jaynus** [comment]
Thats not my understanding of the system as discussed with @ulteq. 

You can set the weather on the server, and it will propagate to clients. Additionally, the changes in weather in the server over time (by vanilla or by the system) will propagate to clients. That is as long as the ACE sync weather is enabled.

ACE *only overrides weather* if the actual weather is enabled. 

See this snippet from slack:

e.g. im not sure how MCC does the weather, but if it does it the same way everyone else always has - it'll change the weather for everyone and then slowly fall out of sync between all the clients.

jaynus [2:01 PM]
And you'll still have drastically different wind on each client regardless

jaynus [2:01 PM]
while still using ACE weather sync, it would match across all clients - but the server-side change by MCC would still apply

jaynus [2:02 PM]
am i correct in all that @ruthberg

ruthberg [2:02 PM] 
Yes

ruthberg [2:02 PM]
That's the main reason why we added so many options.

bullhorn [2:02 PM] 
awesome

ruthberg [2:02 PM] 
To prevent people from deleting the weather pbo, because they can't use their own stuff anymore.

jaynus [2:02 PM] 
Yes. While "ACE weather generation" is basically our own version of the "random" weather setting

ruthberg [2:02 PM] 
There are several weather mods out there, but most of them fail on the sync part.

ruthberg [2:03 PM]
> While "ACE weather generation" is basically our own version of the "random" weather setting
Exactly!

**Comment by esteldunedain** [comment]
Mmm, ok. Now I see how @ulteq changed it. Yeah, it will work with some caveats. 

We are broadcasting the current server value as both current value and 60 sec forecast (there's nothing better that can be done under this conditions). So basically the weather will be fixed in the clients for 60 seconds as it was in the server at the beginning of that period. That will kinda work for rain.

However that setup is actually quite bad for wind, cause if "random" is selected on the mission the intensity and direction changes a lot very fast, so bullet trajectories won't have a chance to be in sync any more. 

I still we should NOT recommend that setup, and in any case advice the `GVAR(serverUpdateInterval)` setting to be greatly reduced for those conditions, to something like 1~2 secs.

**Comment by ViperMaul** [comment]
Status?

**Comment by SilentSpike** [comment]
Were the mine modules made compatible with ace disarm already? I heard they were but couldn't track down any changes relating to it

**Comment by alrik11es** [comment]
For the sake of ... don't do things that are already done like changing weather: https://github.com/astruyk/Ares
