### ISSUE TITLE
Aiming with the Mk6 Mortar digital compass is inaccurate unless on perfectly flat ground

### ISSUE THREAD

**Issue by VKing6** [acemod/ACE3#1498]
I talked about this in Slack but I forgot to ticket it.

Unless the Mk6 mortar is on flat ground the digital compass will be inaccurate when firing without using the artillery computer. The cant doesn't appear to affect the fired round because of some BIS magic or other.

More testing is required to determine if the round will land where expected if the compass error is corrected for.

**Comment by alganthe** [comment]
This is a BI issue and has been fixed on dev branch

**Comment by GitHawk** [comment]
@alganthe Can you post a link to dev branch change log?
I believe I have a similar problem with Artillery.

**Comment by ulteq** [comment]
> This is a BI issue and has been fixed on dev branch
Are deployed rfiles also affected?

**Comment by GitHawk** [comment]
@ulteq I believe they are see #890 Artillery is affected aswell - notice the difference between cannon and tracer angles.
![107410_screenshots_2015-06-04_00011](https://cloud.githubusercontent.com/assets/1816059/8021634/942ce76c-0ca7-11e5-8f06-5898f9a99c5e.jpg)

**Comment by esteldunedain** [comment]
My god BIS

**Comment by VKing6** [comment]
> This is a BI issue and has been fixed on dev branch

Unfortunately it appears it hasn't.
http://i.imgur.com/TdryHkD.jpg
http://i.imgur.com/rVcGsfn.jpg
http://i.imgur.com/gci9PpW.jpg

**Comment by ulteq** [comment]
> My god BIS

:disappointed:

**Comment by austinjames314** [comment]
@VKing6 I can confirm that if (if!) you comensate for the azimuth and elevation offset (yes elevation too!) introduced by the angle and direction of the ground's slope, then you can get rounds on target. See Codings Artillery Computer, a mod which, among other things, provides the angle added by the ground's slope, so that you can apply that offset. (Except that it gives it in degrees, making it pretty useless for me).
 Ideally of course, the mortar sight would just give you the _actual_ azimuth and elevation of the barrel, relative to the coordinate system, not relative to the piece of terrain you happen to be set up on.

**Comment by VKing6** [comment]
Heh ideally the model should animate so the tube could be upright even if the base is tilted (like on the real things!), but I'll check that method out.

A mission maker from my community said he was going to try to attach the mortar to a game logic to level it. I have to ask him how that experiment went.

**Comment by austinjames314** [comment]
Any progress on this? In my clan we're getting better at procedures for adjusting fire, and guesstimating offest based on previous fire missions, but it would be great to have this work like it's supposed to.

**Comment by PabstMirror** [comment]
Sorry for the delays, should be fixed in next release.
Also, good news, in 1.48 RC the mortars seems much more stable and don't tip over as much.
