### ISSUE TITLE
Mk6 mortar: range table ('air resistence' enabled) is wrong?

### ISSUE THREAD

**Issue by Armilio** [acemod/ACE3#1625]
First of all: sorry for my english, i'm not mother tongue.

I made a lot of test with mk6 for my clan. And when i say a lot, i mean it. So, without 'air resistance' enabled, i have no problems, always very accurate shot. But with 'air resistance' enabled, i have big problem on the medium-long range especially with the charge 2. I know that is normal that charge 2 has a bit of inaccuracy, but here i'm talking about 200 meters too long in a 1300 meters shot (for example). First, i thought about wind. But without it, 0 m/s everywhere on the map, the problem remain. So i thought about air density, but that's the first problem, without acrimony: air density column isn't explain anywhere. The tutorial on the wiki forget to explain the last 3 column. I know how to calculate air density, but i don't understand what mean "1 PCT" and from which value i must start to count "inc" or "dec". But may density make error like that (200 m), when it is not explained, so probably (i thought) is a minor variable? That's why i put the question point: may be air density that make my medium-long range shot so inaccurate, or is it innacurate the range table? i'm starting to believe the second one.  Indeed, another strange thing – if my problem is air density - it is that in an environment with less air density – Takistan – the average "inaccuracy" with charge 2 drop from 200 m too long (on Altis) to 100 m too long, instead of raise.

P.s: The inaccuracy remain with the charge 1. But it drop from an average 200 m error to an average 50-75m error, at the same distance of 1300 m, in Altis, 0 metres above the sea. That's another reason why i doubt that can be only the air density. 

P.p.s: Yes, i always shot from a flat terrain.  And the air density was 1,123 on Altis and 0,93 on Takistan.

**Comment by MaHuJa** [comment]
"But without it, 0 m/s everywhere on the map, the problem remain."
Was this measured with the kestrel while "inside" the mortar? This seems to count like being inside a closed vehicle, causing it to read zero. The wind readout can also be disturbed by terrain or objects blocking the wind to where you are standing.

The table itself claims a ch2 3km shot with 2m/s headwind will fall 18m short if you don't compensate for wind. It explicitly specifies the unit to be meters rather than mils of elevation change. (I even found that when looking at the code.)

**Comment by austinjames314** [comment]
We just ran a tac last night using ace mortars, and it was working like a charm. 3.2.0 has fixed all Mortar problems that I can find. 
Air density makes a huge difference on Takistan, due to the altitude. Use the Kestrel to get the ambient pressure and compare that to 1013.25 hPa (standard pressure). That's a good enough proxy for density. Then multiply the percentage difference by the value in the table, and apply the offset.

**Comment by Armilio** [comment]
Thanks for the answer. I was just writing that after the 3.2.0 patch the mortar works fine for me too, good work. About density, @austinjames314 : do you mean that if - for example - i have 1200 hPa, so approximately 20% difference, i have to multiply 20xValueOnTheTable?

**Comment by austinjames314** [comment]
That would be a +18.4% difference, so multiply the 1% amount on the table by 18.4, yes.

**Comment by Armilio** [comment]
@austinjames314 : i made some test in Takistan. HPA doesn't work for me. An example: 2450m of distance, charge 2: 1% = 5.5 elevation. In Takistan the pressure is 793 hPa, so more than 20% of difference; 20% x 5,5 = 110 mils. It's too much, the round goes too short. Maybe ambient pressure it's not a good proxy for air density. Air density formula (see wikipedia) works better, but it's still inaccurate.

**Comment by MaHuJa** [comment]
At 20x, you're running into another problem - you're given a linear correction for a non-linear error.

**Comment by Armilio** [comment]
@MaHuJa : Ehm... what do you mean? and, most important, what's the solution?

**Comment by MaHuJa** [comment]
"An example: 2450m of distance, charge 2: 1% = 5.5 elevation. In Takistan the pressure is 793 hPa, so more than 20% of difference; 20% x 5,5 = 110 mils."

For 1% difference, a 5.5 correction is correct. For a 2% difference, the correct compensation may be something like 10.9 rather than the calculated 11.0. Which is still fairly small, but the error per 1% increases for each added 1%. 

As for how to work around it, it's complicated.  

Solution 1:
- Turn off wind, and then shoot until you find the correct value to compensate for.
- Several times
- See if you get a (constant) factor you can apply to the values in in the table

Solution 2:
- Change the table generator script (and possibly display scripts) to do an extra set of tables for low air density, closer to what it's like in takistan. 

Solution 3:
- Use an (external) artillery calculator. I'm working on one, but who knows if I'll finish it.

**Comment by austinjames314** [comment]
@Glowbal A year, and hundred of ace3 mortar fire missions later, on various maps, and I've never encountered this problem. The closest thing I've observed is that when firing with a significant height difference between firing point and target, you need to guesstimate the average air pressure between the two points. That's really as you'd expect.

**Comment by bux578** [comment]
Thanks @austinjames314. Will close this issue.
