### ISSUE TITLE
RHS smoke grenades mislabeled.

### ISSUE THREAD

**Issue by BigPoppaBlunts** [acemod/ACE3#1629]
In the status box (upper right corner of screen) when cycling grenades types, all RHS smoke grenades shown as RGO grenades. Vanilla smoke grenades are labeled correctly. V3.1.0

**Comment by esteldunedain** [comment]
@BigPoppaBlunts, sorry but I can't reproduce it. Tested with the latest RHSAFRF version 0.3.8 and the  current version of ACE (but should be the same with previous releases of both, based on their configs).

**Comment by Legolasindar** [comment]
I remember this happen in AGM and ACE3 with RHS USA version from the last Arma3 patch.
CBA, RHS, ACE3 and ArmA3 have lastest version.

**Comment by esteldunedain** [comment]
@Legolasindar, I only tested the Russian faction; does RHS USA have custom grenades now too?

**Comment by Legolasindar** [comment]
RHS USA have custom grenades from the 3.0.0 version :D M84 Flashbang, M67 Defensive, M18 Smoke and others.
http://class.rhsmods.org/rhsusaf/index.html

This is M84 Flashbang of RHS USA, with correct icon, but wrong name.
![M84](http://i.imgur.com/V9jo0oF.jpg "M84")

**Comment by esteldunedain** [comment]
Ok, I'm downloading the pbo atm to test it and look at the configs.

**Comment by Legolasindar** [comment]
Thanks ;)

**Comment by esteldunedain** [comment]
Ok, I went through this in detail. Now I understand the reported issue properly.

> all RHS smoke grenades shown as RGO grenades

@BigPoppaBlunts, you are totally right. RHS USF is NOT setting the correct `displayNameShort` parameter for grenade magazines, and since all of them inherit from the RGO grenade all of them display that name. This is something RHS has to fix. The icons are ok. 

---------------------

Besides that, most grenades are correclty classified in letal vs non-letal. Some are not though. We consider lethal any grenade that causes explosive damage (`explosive > 0`) in config. Unfortunately RHS decided to make flashbangs do explosive damage (so they are considered potentially lethal), but decided to make incendiary grenades not to produce damage (so they are considered non-lethal).

To revert this we would need to create additional config entries and create compat pbos. I'm not sure if it's worth it.

**Comment by BigPoppaBlunts** [comment]
Sorry, I had to be away a couple days or I would have given more detail. Thank you all for investigating the issue.

**Comment by bux578** [comment]
> Unfortunately RHS decided to make flashbangs do explosive damage (so they are considered potentially lethal),

The same with @super_flash: http://www.armaholic.com/page.php?id=21139

It's in the lethal grenades rotation.
