### ISSUE TITLE
Possibly make hypovolemic shock more realistic?

### ISSUE THREAD

**Issue by HTSean** [acemod/ACE3#1733]
I subjected some test subjects to rapid blood loss using the Advanced Medical System and monitored their vitals every minute and wrote 'em down and made it into a line graph.

I noticed however, that the vitals don't seem to resemble their "real-life" counterparts during hypovolemic shock. Even though subject 2 bled out significantly faster, the blood pressure and heart rate patterns remain consistent. 
1) The heart rate raises slightly while staying below the tachycardia threshold, before going down slightly just to eventually just go into sudden cardiac arrest.
2) The blood pressure declines steadily throughout the process with the gap between systolic and diastolic decreasing in size until the event of cardiac arrest once it reaches around 35/25.

![](http://i.imgur.com/uPXZ0Pp.jpg)

While these patterns are consistent with seperate subjects, it does not seem to be true-to-life, as many sources seem to:
1) Describe the heart rate increasing as long as the casualty is losing blood rapidly, going well above the tachycardia threshold of 100bpm from stage 2, even reaching above 140bpm in stage 4 of hypovolemic-shock.
2) Describe the blood pressure staying more or less the same until >15% blood volume is lost (with the exception of the diastolic increasing slightly in Stage 2).

It would be great to be able to actually know how much saline we should administer just by reading the casualty's vitals. Keep up the great work, I'm loving ACE3 so far.

http://sogc.org/wp-content/uploads/2013/01/115E-CPG-June2002.pdf (Page 4)
http://www.ambulancetechnicianstudy.co.uk/shock.html#.VYlEGvmqpBc
http://wps.prenhall.com/wps/media/objects/4849/4966157/vid_anim/ch13/hypovolemic.html (very detailed interactive guide to hypovolemia)

**Comment by BaerMitUmlaut** [comment]
So does the heart rate rise because it is trying to compensate for the blood loss? What would happen if you stop the blood loss, would it drop again or stay high?

**Comment by HTSean** [comment]
Yeah that's why the heart rate rises, from what I understand. And I believe it would stay high until blood volume increases again as the lower the blood volume, the harder the heart has to work to keep it running properly. I'm not entirely sure though, so I could be wrong.

**Comment by mjblay** [comment]
For what it's worth, I am a general surgeon and trauma surgeon in real life.  I'm also an ATLS (Advanced Trauma Life Support) instructor.  I'm not military, but still when people get shot, I'm the one who admits them to the hospital (and if they're shot in the neck/chest/abdomen/pelvis I'm the one taking them to the operating room).  I can link you to my professional email address or provide whatever other confirmation you need. I'm also an ArmA and ACE lover.  I'd be happy to add any information I can to make things more realistic.

Sean, your understanding is correct.  The first sign of hypovolemia is tachycardia.  This happens well before blood pressure drops.  Tachycardia increases cardiac output (or the amount of blood the heart is pumping per unit time) so initially, although blood volume drops, blood pressure remains constant.  Once you've lost enough blood that the heart can't pump effectively (i.e. it's not filling up enough during its relaxation phase to make its squeezing phase efficient), then you start to see blood pressure drop.  And when you lose so much blood that the heart can no longer pump blood to itself through the coronary arterial system, you slip into cardiac arrest.

It may be slightly different on the battlefield, but in the civilian world and according to ATLS  protocols, you give 2 liters of crystalloid (saline or lactated ringers solution) first through two large-bore IVs.  If you don't get an improvement in heart rate and blood pressure, you start hanging blood, and quickly.  You use O-negative blood unless you already have a type and cross-match by that time.  And all the while you play the game: "Blood, blood, where's the blood?" i.e. look for all the potential areas an injured patient could be bleeding from.

On average, a 70 kg male will have about 5.25 liters of blood.
* Each hemithorax (one side of the chest) can hold 2-2.5 liters of lost blood
* The abdomen and pelvis can hold over 3 liters of lost blood
* Each injured thigh/femur can hold 1-2 liters of lost blood
* Each injured calf/tibia can hold 0.5-1 liter of lost blood

So if you take one in the thigh and one in the abdomen, you can exsanguinate (bleed to death) in a matter of minutes without even much blood spilling on the ground.  And in that situation, only surgery and critical care will help you, so you're effectively out of the battle.  I'd love to see the integration of triage like the [START method](https://en.wikipedia.org/wiki/Simple_triage_and_rapid_treatment) into medical care in ArmA so that if you're red or dead, you can no longer fight and just need evacuation.  From the lectures I've attended, the US military uses a very similar triage model ([like this?](http://www.cs.amedd.army.mil/borden/FileDownloadpublic.aspx?docid=68aca9a0-9cd7-4d8f-a17f-a4c01264daef)).

**Comment by TonkaTruck** [comment]
mjb, I'm glad that you posted! I've been thinking about how inadequate ACE is when showing shock. There is no use of Adenosine in the current system unless I purposely overdose the patient on Epi.

ACE needs to show a sharp increase of pulse as the BP drops. I'd also like to see bonus's to the fluids. Plasma and Blood should have better BP raising ability than the normal saline.  

Also, something that may be neat. If it was possible to remove the ability to feel a pulse when the BP is past a certain low threshold and only able to feel a pulse at the neck (or head).

**Comment by ulteq** [comment]
The medical rewrite will address this issue.

**Comment by jonpas** [comment]
This has been attempted in the rewrite but has been shown to be unsustainable and has been reverted. Other changes in the rewrite should however improve this, @HTSean if you are still active and want to compare medical rewrite, we will gladly accept it.

**Comment by SilentSpike** [comment]
Yeah just to add on to this, we were seeing heart rate increase in rewrite which we believe we an attempt to implement more realistic behaviour like this (https://github.com/acemod/ACE3/issues/6913#issuecomment-499082968).

However, we had massive issues with blood loss being way too brutal and had to change the effects of bleeding on HR and BP. It's more than likely not realistic, but has fixed the issues we were having. Perhaps now that we understand the system more we could look into making it more realistic after release of rewrite.

**Comment by KHunter-Arma** [comment]
Hi @mjblay . Are you still active here? Because we've been talking about this issue on the ACE Discord while thinking about potentially improving hypovolemic calculations. If we forget that your comment is almost 10 years old 😆, could you perhaps comment more specifically about Sean's suggested graphs above? If we could get some data points for the whole of the hypovolemic spectrum, we could quite possibly come up with a better formula to simulate this on ACE.

**Comment by TonkaTruck** [comment]
> Hi @mjblay . Are you still active here? Because we've been talking about this issue on the ACE Discord while thinking about potentially improving hypovolemic calculations. If we forget that your comment is almost 10 years old 😆, could you perhaps comment more specifically about Sean's suggested graphs above? If we could get some data points for the whole of the hypovolemic spectrum, we could quite possibly come up with a better formula to simulate this on ACE.


Hi, I can add onto this. 
His comment is a little outdated these days. We've found that dumping lots of saline into patients isn't the best thing. Ultimately, you gotta fix the hole and stop the leak instead of turning blood into kool-aid with fluid. Blood products are the ultimate replacements for blood loss, go figure. These days, EMS agencies work on maintaining a Mean Arterial Pressure (MAP) of 65 with small amounts of fluid. It's about a blood pressure of 90 systolic.

I looked over the graphs and the suggested graph that the OP posted is actually pretty good. I would recommend increasing the upper limits of heart rate. Antecodally speaking, most patients that I have worked cardiac arrests on from trauma origins display an electrical rate of 180ish with no pulse (they have no blood to pump, but the pump is still working). A HR of 140 with a BP of 80 or less seems very sensible. Most patients that have blood pressures of 60 systolic are usually unresponsive/sluggish, with exceptions.

Here is a link that talks more about the scientific mechanics about it. It's worth a peruse. I also believe it contains some of the source material, given that the ATLS graph in the link uses the same data points as his graph (namely the 140 HR means death). 

I still maintain my earlier comment that buffing blood products and plasma with greater increases of BP will be an effective in-game way to explain their benefits. You'd have to figure out balancing (if thats something you'd want).

https://derangedphysiology.com/main/cicm-primary-exam/required-reading/cardiovascular-system/Chapter%20502/cardiovascular-response-haemorrhage-and-hypovolaemia

**Comment by mjblay** [comment]
I'm not active in gaming at all anymore (for better it worse, I've fallen
into several more expensive hobbies), but I'm still active in the care of
injured patients.  I'd agree that trauma resuscitation has changed a lot
over 10-15 years. ATLS is a great resource. Glad to hear the ACE mod is
still being actively developed. Unfortunately I can't really dedicate any
time to it now.  EMTs, ED docs within the community would be great
resources though.  Best of luck!
