### ISSUE TITLE
Q: Accessing functions from external mod/scripts

### ISSUE THREAD

**Issue by ArcticSnowSky** [acemod/ACE3#1752]
Hey guys,
I'd like to write some scripts for the AI to do medical treatments.
As you don't want to mix AI in the mod (which is good so people have the freedom to choose), I wanted to ask:
How can I access/call values/functions like fnc_getUnconciousCondition (call FUNC(getUnconciousCondition) isn't possible from my Scope I think?)?

Is it even possible? (Sorry for my noobish question, but with all those magical things I don't get the ropes this fast)

or would I have to make an ACE module?

And can ACE modules interact from module to module? (I guess yes)

Thank you for your time and the mod, this mods are what makes ArmA so incredibly awesome³²!

**Comment by jonpas** [comment]
> How can I access/call values/functions like fnc_getUnconciousCondition (call FUNC(getUnconciousCondition) isn't possible from my Scope I think?)?

It is not a matter of scope, `FUNC` is a CBA macro (reference https://github.com/CBATeam/CBA_A3/blob/master/addons/main/script_macros_common.hpp#L700), due to CBA/ACE framework ACE3 makes full use of (ADDON is project-specific, so you might as well say out-of-scope), doing `call FUNC(getUnconsciousCondition)` in the project would equal to `call ace_medical_fnc_getUnconsciousCondition` outside of the project.

> And can ACE modules interact from module to module? (I guess yes)

Yes of course, that's where external reference macros come into play, such as `EFUNC`.

**Comment by ArcticSnowSky** [comment]
Hi jonpas, thank you very much for your answer!

this usage sounds very nice and I guess it would be good and nice for my project to get used to it.
I guess I will try to align my project in the same way if it lives longer than the creation time :)

**Comment by jonpas** [comment]
No problem. ;)
