### ISSUE TITLE
"Keep cursor centered" is the only viable option for large Interact Menu sizes - Look for alternatives

### ISSUE THREAD

**Issue by simonamdev** [acemod/ACE3#1774]
Posting this for someone in our community who does not have a github account,

ACE3 Version: 3.1.1

Release, both with some minor modifications (none relating to interact, more info: https://github.com/Winter259/ACE3/tree/ark-release-3-1-1-notriage) & with ACE 3.1.1 with no modifications

**Mods:**
- @cba_a3
- @ace3

**Placed ACE3 Modules:**
None

**Description:**
https://www.youtube.com/watch?v=hD9OUxPqmu0
Person says that reducing text size/arma interface size alleviates/solves the issue but makes it much less readable/ starts going into "this hud is too small" territory.

**Steps to reproduce:**
- Play at 1440x900 resolution
- Start Mission
- Place explosive
- Place trigger
- Try to detonate

**Where did the issue occur?**
SP

**RPT log file:**
Modified ACE: http://hastebin.com/iwohawovej.tex
Vanilla ACE: http://hastebin.com/xewewohemu.tex

**Comment by esteldunedain** [comment]
I'm not sure I consider this a bug, but it's certainly a usability/accesibility problem. The code is performed as intended; The menu disappears because the action point is no longer visible (it was moved off-screen when looking that much to the side). Even if it didn't (which would be a hell to code), I wouldn't ever recommend using it this way, cause it really cumbersome already having to look that far off to select an option.

To be honest, I think the only viable option for using such a large menu size is the "Keep cursor centered" option. I'd recommend trying that.

Maybe we could rearrange the Explosives menu to remove a level, but the problem would still happen for other deep actions, like interactions inside vehicles, so it wouldn't be a complete solution.

**Comment by Winter259** [comment]
Person tried the "keep cursor centered" option, this was his feedback:

> I'd have to get used to it, I guess, before being able to say whether it would be usable under fire. All elements do show, though.
>  I'd love it if they looked into either less levels, or maybe a way to "collapse" or "compress" the higher levels? Because... it does seem like something that should receive some love, at least.

I can understand the "its not a bug, its a feature" line of thought. Maybe you can put this issue on the backlog and get back to considering other ideas another time after having a think about it. If not, I guess issue can be closed.

Thanks for the fast response :+1:

**Comment by esteldunedain** [comment]
NP, @Winter259. 

I definitely think we should make another pass of improvements to how the IM behaves at some point, cause I imagine we CAN do better. It's just that I don't have a clear idea about how at the moment.

I'll rename the ticket and backlog it. Thank you

**Comment by jameslkingsley** [comment]
One solution could be to always center the IM on the current selected node. If you're navigating to the right then the IM could move to the left.

**Comment by tofof** [comment]
One alternative to keeping the cursor centered is to **draw the first menu node (for self interaction, at least) on the left side of the screen**, instead of in the center.

Use case:
- Very Large text size - easier to read in a hurry, bigger mouse movements reduce chance of selecting wrong thing
- Display in Lists - far easier for me to read in a hurry than radial popouts

This combination means that only the 3rd menu deep is visible at 1920x1080, where the 1st 'menu' is the completely redundant "Self Actions" node, the 2nd is the first usable tier of actions, and so on. So, for example, ACRE's "Self Action → Radios → AN/PRC-343 Chn: 1 → Multi Push-To-Talk 2 → Set as Multi Push-To-Talk 1" is hopeless. Without keep cursor centered, the 4th node is cut off and the 5th is off the screen.

Another helpful steps would be to **eliminate the redundant 'Self Action' node**.

Or, you could simply add detection for when the **draw position for text is completely off-screen**, and scroll in that case.

Finally, you should consider **scrolling when the cursor/selected node is near screen edges**. This would be in all 4 directions and useful for world and self interacts.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
