### ISSUE TITLE
"Do When releasing action menu key" option in OFF interferes with controls

### ISSUE THREAD

**Issue by Legolasindar** [acemod/ACE3#1785]
ACE3 Version: 3.1.1

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
None

**Description:**
* With "Do When releasing action menu key" on, things like move and extend the telescopic ladder option is possible. But if you have that option turned off, it is no longer possible.
Same for sandbag for example.

**Steps to reproduce:**
* Create a simple mission with Virtual Arsenal in a object.
* Go ACE Options menu with ESC key, and select "Do When releasing action menu key" with OFF option.
* Get Telescopic ladder.
* Put telescopic ladder. You cant move or extend this.
* Go ACE Options menu with ESC key, and select "Do When releasing action menu key" with ON option.
* Interact with telescopic ladder. You can now can move or extend this.

**Where did the issue occur?**
* Occur in SP and MP mission.

**RPT log file:**
Not need.

**Comment by austinjames314** [comment]
I can confirm this. I've been using "Do When releasing action menu key" set to 'off' so that I could actually use the menu properly, and It wasn't until someone else used the ladder that i realised that my settings meant I couldn't use it properly. My point is, there's no error message or anything, it just behaves differently.

**Comment by Legolasindar** [comment]
I see with sandbag occurs the same.
