### ISSUE TITLE
Flashbangs don't bounce from walls

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#1907]
As discussed in the TS meeting:

If you throw a flashbang against a wall (preferably in an angle) the flashbang doesn't bounce it just drops straight down.

**Comment by kripto202** [comment]
I think it's more of a bi problem because it happens to all of the grenades.

**Comment by bux578** [comment]
Actually: 
https://youtu.be/WrfHhxbCiI8

**Comment by PabstMirror** [comment]
Playing with changing deflecting on CfgAmmo

`deflecting = 60;`  seems good, it's what the smoke grenades use

**Comment by kripto202** [comment]
what does the grenades use?

**Comment by PabstMirror** [comment]
Grenades use 15 :confused: 
I think simulationType might also have an effect?  The M84 inherits from `FlareBase`.

I'm really not sure, but I do think 60 is an improvement over the current value of 30.

**Comment by kripto202** [comment]
is it possible to change the grenades to roughly 30? Those grenades should be able to bounce off walls a lot better than they are now.

**Comment by commy2** [comment]
`deflecting` is the minimum angle a projectile has to hit the ground to possibly bounce. 0 meaning never bounce, 90 meaning possibly (there is a %-chance modifier somewhere) bounce on all angles.

The issue is that perpendicular bouncing is a feature exclusive to the simulations of frag and smoke grenades, not flares.

There is no reason for the M84 not to be a smoke grenade though (with no smoke effect). It's just Flummis lazyness again.
This is also the reason you don't hear impact sounds on the flares. I'll see if I can do something about them later.

**Comment by bux578** [comment]
gj @commy2

**Comment by bux578** [comment]
Works very well! Finally :smile:
