### ISSUE TITLE
Finish Enhanchments to pointing

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#1917]
Finger is functional, but I didn't finish all the notes from @esteldunedain 
See #1548

**Comment by alganthe** [comment]
Dat name tho "fingering"

**Comment by ruPaladin** [comment]
Does "finger" check line of sight? Is it possible to use through walls? If yes, found another version with LOS check: http://forums.bistudio.com/showthread.php?188895-d_finger-quot-Point-a-finger-at-quot-addon&p=2938802&viewfull=1#post2938802

**Comment by PabstMirror** [comment]
It already checks LOS

https://github.com/acemod/ACE3/blob/master/addons/finger/functions/fnc_keyPress.sqf#L48

**Comment by Panimala** [comment]
This is what it currently looks like

**Comment by Panimala** [comment]
I'm glad this mod has made its way into ACE, nice job! I have some additions I'd like to share that I hope you could consider.
This is what it currently looks like:
http://a.pomf.cat/fwhbkz.png
This is @d_finger with some of my own edits:
http://a.pomf.cat/dpqqqc.png

This ring that isn't coloured is easier on the eye and since it is half black & half low opacity white it shows just as well during the night and day without being in the way.  Bumgie put in support for use within boats and cars. I added support for helicopters as well, this means that co-pilots and co-drivers can point out points of interest for the driver or pilot (LZ, mines on the road...) very useful and natural to use.
Here is my pbo:
http://a.pomf.cat/filomu.pbo
My is ring .paa (set to 25% opacity in the addon):
http://a.pomf.cat/bwcyun.paa

This is Bumgies post with .sqf including support for use within cars and boats, however not helicopters which is in my .pbo:
http://forums.bistudio.com/showthread.php?188895-d_finger-quot-Point-a-finger-at-quot-addon&p=2938802&viewfull=1#post2938802

**Comment by gienkov** [comment]
Oh ability to point while inside for example HMMWV could be great!

**Comment by alganthe** [comment]
I would like to see Panimala's improvement in there, they're good.

**Comment by VyMajoris** [comment]
There is a major bug/problem for those who use free aim. The ring apears on the center of the screen instead of the point of aim.
http://i.imgur.com/4XxIP1s.jpg

**Comment by ruPaladin** [comment]
Maybe it will be better to add ace interaction entry. Center of ace interaction menu will be the center of finger circle.

**Comment by SilentSpike** [comment]
:+1: for @Panimala's visual tweak to the circle, I definitely think we should include that

**Comment by PabstMirror** [comment]
Closed by #4002
