### ISSUE TITLE
Zeus interface climb

### ISSUE THREAD

**Issue by NemesisRE** [acemod/ACE3#1951]
ACE3 Version: 3.2.0

**Mods:**
@cba_a3
@ace3

**Placed ACE3 Modules:**
Non all set via Mission variables.

**Description:**
If you have Climb on CTRL+V and you are in the forced Zeus interface triing to paste something it will tell you that you can't climb here

**Steps to reproduce:**
* Bind Climb to CTRL+V
* Press CTRL+V while in Zeus interface

**Where did the issue occur?**
"Multiplayer"

**RPT log file:**
No script errors

**Comment by SilentSpike** [comment]
Related to #1949 in that they will  both be fixed by an improved method of handling specific display keybinds

**Comment by SilentSpike** [comment]
Mentioned in slack, but I might as well dump this here so that I don't forget. Potential idea to fix:

- Extend CBA keybind framework to allow "virtual" keybinds
  - Don't add any key event handlers
  - Simply associate DIK code with some unique identifier
  - Uses same framework and thus still settable via the same method
  - Can be retrieved by some function to allow displays to process the keys in their own way

**Comment by PabstMirror** [comment]
What about having `EFUNC(common,canInteractWith)` return false if the user is in zeus.

or just for keybinds add
`(!isNull curatorCamera) exitWith {false}` to free the key.

**Comment by SilentSpike** [comment]
Both would work, but they're more of workarounds than solutions to the underlying problem.

**Comment by SilentSpike** [comment]
Currently looking into a work around for this using CBA_fnc_getKeybind. However, `["ACE3 Common","ace_interact_menu_InteractKey"] call CBA_fnc_getKeybind` is returning nothing
