### ISSUE TITLE
ACE fonts pbo is outdated

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2035]
ACE3 Version: 3.2.1 Stable (downloaded from armaholic and from biforum ACE3 official thread)

Mods:
a lot of them

Description:
I get rpt error: [ACE] ERROR: File ace_fonts.pbo is outdated. Looks like config.cpp is not binarized in it.

Where did the issue occur?
nope

RPT log file:
nope

**Comment by jonpas** [comment]
> Looks like config.cpp is not binarized in it.

That's as it should be. Can you verify you have the latest version and try redownloading and replacing the entire `@ace` folder?

**Comment by PabstMirror** [comment]
Possibly related to #1953 (fixed by starting as admin)

The pbo isn't bined / so it's macros aren't unwrapped like most.  But as long as you have a current CBA and rest of ACE the game should be doing that just fine.

Double check you have the most recent CBA.  And it the issue still persists, please post full RPT log.

**Comment by ruPaladin** [comment]
I am sorry. Redownloaded ace3 and cba and tried with them. Cannot replicate.
