### ISSUE TITLE
ACE tracers are too dim at night

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2082]
ACE3 Version: 3.2.1

Mods:
@cba_a3
@ace3

Placed ACE3 Modules:
none

Description:
ACE tracers are too dim at night. Screenshots:
http://i.imgur.com/fecIInX.jpg
http://i.imgur.com/PpwYutO.png
My bloom setting is 0. 

Steps to reproduce:
Spawn any unit with tracers and shoot at night time. Ghosthawk is ok for this.

Where did the issue occur?
Editor

RPT log file:
none

**Comment by NouberNou** [comment]
Looking into this.

**Comment by commy2** [comment]
Models  are already using the materials of the vanilla tracers (emmisive {1,1,1,1}). I think this can only be improved further by changing the textures.

**Comment by Glowbal** [comment]
We are accepting PRs for this. As per @commy2 's suggestion, this should be changing the textures.

**Comment by Drofseh** [comment]
I've been poking around at this and the problem seems to be the rvmat's for the tracers.

If I use the values from `"P:\a3\weapons_f\data\bullettracer\data\tracer_red.rvmat"`
and I apply them to `"P:\z\ace\optionals\tracers\data\SLX_RedTracer_Material.rvmat"`

then I get nice visible tracers day or night
https://gyazo.com/a1fdfb0372cfe47a9c0ce7adf926bb17
https://gyazo.com/daa99f0334041aa4020132fadf64bf41
