### ISSUE TITLE
Advanced medical : crushing damage per car bug

### ISSUE THREAD

**Issue by havena** [acemod/ACE3#2154]
ACE3 Version: 3.2.1

Mods:

@cba_a3
@ace3
Placed ACE3 Modules: http://pastebin.com/uGuAaH8i

None.
Description:
when I crush someone with a car, this one has no damage, it simply has no pulse.

And doctors can do nothing for him.

Steps to reproduce:

ride on someone with a car

Where did the issue occur?
"Multiplayer"

RPT log file:
No need.

**Comment by headedhorseman101** [comment]
Had the same issue. Can get an rpt log of my test.

**Comment by ace3mod** [comment]
Hello!
We're automatically closing this issue since it has not receieved any updates or comments in the past 14 days. We therefor assume that the original reporter has lost interested or the issue has been resolved.

If this has been closed in erorr, please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested.
Thanks!
