### ISSUE TITLE
Distance in ACE_Action's sub-actions not respected

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2196]
*This issue does NOT adhere to the issue posting guidelines, it is a framework issue!*

When you use `distance` parameter in a sub-action, it is not respected, it will always show (and even expand the parent if it's a sub-sub-action) until the interaction menu's maximum distance itself.

It works fine for `ACE_MainActions`, but for any child action distance code (eg. `_obj1 distance _unit < N`) must be added into the `condition` code to limit the distance.

**Comment by NouberNou** [comment]
Do you have a use case for this? Because right now it seems like its able to be done in the current implementation and the original implementation was only for the main action.

**Comment by jonpas** [comment]
Yes, it would be a lot easier when adding actions in config, rather than manually putting distances in the action's conditions.

**Comment by PabstMirror** [comment]
I mentioned this in #3132, we could now easily add this in, but I don't think we want to.

 - createAction currently defaults to 2 meters, if we start enforcing distance on sub actions, old code will break or at least not work how people expected it to work
 - We only update the sub actions every 1 second (instead of 0.2 sec for the base level), so it's not as responsive when moving around.  Personally I though it felt very odd and not intuitive when you see an interaction point, but not all of it's actions,
 - Developers can still manually check distance in their own conditional code, which I think is what we should leave it at.

Can test by uncommenting: https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_collectActiveActionTree.sqf#L38-L41

**Comment by esteldunedain** [comment]
I agree. I'd leave change out.
