### ISSUE TITLE
Heavy FPS drops if zoomed out in MicroDagr

### ISSUE THREAD

**Issue by TheConen** [acemod/ACE3#2204]
ACE3 Version: 3.2.1. dev (latest commit: 42bd8751aa8b1937e5fd4b7df187c302209fe708)

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
none

**Description:**
The further you zoom out in the MicroDagr map view, the lower your fps get. On maximum zoom level, I have ca. half the fps I usually have.

**Steps to reproduce:**
Open MicroDagr, go to map view, zoom out.

**Where did the issue occur?**
Tested only in editor, but I assume it appears everywhere.

**RPT log file:**
N/A

**Comment by PabstMirror** [comment]
It's due to an aggressive `ptsPerSquareRoad` number.

https://github.com/acemod/ACE3/blob/master/addons/microdagr/gui_controls.hpp#L82

A low number makes it still draw maps when zoomed out.
Right now it will draw every road on alits when zoomed out.

I'll play with the number and get something a little more reasonable.
