### ISSUE TITLE
Overdosing doesn't work

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2223]
ACE3 Version: 3.2.1 and https://github.com/acemod/ACE3/commit/b8b71e1c764ed55e2c3236a648668067bbd4d874

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* *http://pastebin.com/N0uh0kte*

**Description:**
*Like in title, I was able to give an AI 5 injections of morphine in rapid succession and config says max dose is 4:*

```
            class Morphine {
                painReduce = 15;
                hrIncreaseLow[] = {-10, -20, 35};
                hrIncreaseNormal[] = {-10, -30, 35};
                hrIncreaseHigh[] = {-10, -35, 50};
                timeInSystem = 900;
                maxDose = 4;
                inCompatableMedication[] = {};
                viscosityChange = 10;
            };
```

**Steps to reproduce:**
* *Give AI 5 injections of morphine.*
* *Nothing happens.*

**Where did the issue occur?**
*"Multiplayer", "Singleplayer"*

**RPT log file:**
*-*

**Comment by Glowbal** [comment]
You can safely take up to `maxDose` of the medication without risking the overdose triggering. Obviously you have to worry about vitals in this case. After that the next usage might kill the patient. The one after will kill the patient.

**Comment by Glowbal** [comment]
If you want to test this, run the following through debug console:
```sqf
[] spawn { 
    while {true} do {
        cursortarget setvariable ["ace_medical_heartRate", 80];
    };
};
```
This will ensure that the vitals will stay at a safe level while giving morphine to the patient. Just make certain you keep the patient in view every once in a while.

After that, give morphine to the patient until the patient dies. Note that the dosage given slowly decreases over time. So it might not be wierd if sometimes the 7th morphine triggers overdose instead of the 5th or 6th. 

I think we might need to decrease the overDose number for morphine though.
