### ISSUE TITLE
Improvement suggestions for medical treatment realism

### ISSUE THREAD

**Issue by sgtBrowncoat** [acemod/ACE3#2261]
I like the system however I have a few tweaks in mind that relate to how we actually perform TCCC. 

There is no airway/breathing management. Introduction of respiratory distress and an NPA would be neat. If there is penetrating chest trauma and the NPA doesnt fix the respiratory distress it can cue the medic to perform needle thoracentesis. 

Adding this allows for a medic more closely follow the MARCH algorithm.

Changing the use of whole blood to Hextend (or any brand hetastarch). Carrying whole blood in the field would be a nightmare. It is required to be kept cold and then you need to make sure to cross match with the person receiving. Hextend is a plasma volumizer that is given in 500ml increments to increase a low blood pressure caused by hypovolemia. 

 Use of a sphygmomanometer is not a common practice in the field. Those should be limited to medical vehicles and aid stations. We determine need for volume expansion based on systolic over palpation. Locationalized palpable pulses tell the operator approximately what the systolic BP is at. 
~80 systolic at the radial (arm)
~70 systolic at femoral (leg)
~60 systolic at carotid (head)
also it would be fun if you could make a pulse appear absent on a limb with a TQ on it.

**Comment by gienkov** [comment]
>  make a pulse appear absent on a limb with a TQ on it

I like this one.

**Comment by sgtBrowncoat** [comment]
you wouldnt believe how many times while I was in SOCM that I got caught up in the moment and would check my patient's pulse and get no feedback and start freaking out that I had missed some major injury while in reality I was doing great. Just not paying attention.

**Comment by gienkov** [comment]
How does blood pressure behaves on limb that have TQ on? Is the readback lowered or raised?

**Comment by sgtBrowncoat** [comment]
If the TQ is applied correctly you would not get a BP. All blood flow to that limb is cut off and there is no blood going to it and the blood that was in it is equalized. You could possibly get a transient diastolic BP however you would not get a systolic pressure.


If applied incorrectly (not enough pressure, over a joint, ect) it can allow blood into the limb because arteries reside deeper and not allow blood out through the veinous system- this creates what is called a compartment syndrome; but I think that's a little more than you want/need. 


You should also not give medications in a limb with a TQ on it because it would not go anywhere and actually have a toxic effect because the concentration is too high. Trying to give IV fluids would result in the bag not flowing. 


Our drug of choice on the battlefield is also no longer morphine but ketamine because it does not have the issue of dropping a patients BP, heart rate, or causing respiratory distress and it has a wide therapeutic window (it's hard to overdose a patient unless being very negligent). Another pain medicine we give a lot is oral fentanyl citrate as a lozenge (basically a sucker). It can only be given to a conscious/responsive patient (putting something in the mouth of an unresponsive patient is a big no-go) but can cause some minor respiratory depression and slight drop in BP.

**Comment by bux578** [comment]
Hey @sgtBrowncoat: https://github.com/acemod/ACE3/issues/429 Feel free to join.

**Comment by gienkov** [comment]
Thanks! Added this to my PR. Wanted to ask about medications, does injection of morphine/epinephrine increases blood loss if there are wounds that are bleeding? Which one does it faster?

**Comment by sgtBrowncoat** [comment]
Morphine isn't going to effect bleeding much. Epinephrine can cause a slow in bleeding because of its sympathetic nervous system activation. This is the "fight or flight response" which will cause peripheral vasoconstriction. This is transient as epinephrine (adrenaline) is short acting, generally only good in the system for 5 minutes.


I was looking at the triage cards and was wondering if it would be possible to put times of drug administration and TQ's on there and vital signs. A single set of vitals are good but trending vitals give you a more complete picture and help the receiving medical unit understand what happened in the field. Look at a TCCC card for an example of how we annotate this. 

http://austeremedicine.webs.com/tccc1%20card%20updated.pdf

http://austeremedicine.webs.com/tccc2%20card%20updated.pdf


TQ's are typically able to be left in place for 3-4 hours and be removed by the medic in the field. After that if the TQ is removed there will be a large shift in electrolytes (particularly potassium) and dead muscle and all kinds of waste that will destroy kidneys and throw the heart into an arrhythmia. After that 3-4 hour window they need to be in an OR for the removal.

**Comment by sargken** [comment]
Would love to see these things implemented.

**Comment by headedhorseman101** [comment]
Would like to se the use of ketamine instas of morphine, as well. Thanks for the great post @sgtBrowncoat.

**Comment by headedhorseman101** [comment]
>TQ's are typically able to be left in place for 3-4 hours

:+1:

**Comment by Garzog** [comment]
Yes, i know this is an oulder post but i just stumbled across this and want to through in my 2cents.
Since i come from the section of civilian rescue services, i might have a bit other point of view on things, but i guess the basics of medicine work the same.

So for us it´s true aswell, we don´t use morphine any longer in the treatment, one of the main reasons for this is, that morphine creates addictions very quickly and is not as potent as modern medicine, while also causing more problems with the heart rate, bp and respiratory depression then more modern medicine does. So we use an other opiate called "Fentanyl", which we give over IV and is several times as potent on treating pain while being less aggresive on the sympathicus then the normal morphin. (btw, it is so potent that it is one of the only medicine we keep under a double lock.) Also fentanyl, in difference to other pain treating medications, due to it being a opiat, can be countered, if the opiat is overdosed for what ever reason/or if someone shot himself up with one of those drugs, by e.g. Naloxon

The second thing is for "Ketanest" which as far as i know is a ketamine. But we use it as an anesthetic, in connection with a benzodiazepam to counter it psychological effect. Yes it also has a relaxing effect, but for that you would need to apply it in so low doses that something else like Fentanyl.

To the tournequits: @sgtBrowncoat  described it pretty accuratly, one thing to describe it more easily: Blood pressure isn´t the pressure the blood has in your system but the pressue it has when a pump wave, sent by the heart mainly arrives at a point. --> No wave --> no blood preasse measurable.

To the effect on morphine: well morphine, in difference to most dosages of Fentanyl, will affect your heart rate and also your bp as @sgtBrowncoat described, with fentanyl just stronger. So with a lower heart rate, and bp bleedings will be slowed down somewhat, while arterial bleedings due to their nature of having a more of a pulsating nature more then venous bleedings.

To the effect of epinephrin: This is a tricky question, since, as far as i know, the effect on the rate of the bleeding depends a lot on the dosage and the time after applying it. So there is a stimulation of the sympathicus which would make arteries contract --> slowing the bleeding, but also increasing the heart rate aswell as bp --> increasing bleeding, and this effect is especially increased on the venous system since that can´t contract nearly as good as the arteries can.
So our rule of thumb is: if the patient has strong bleedings don´t give epinephrin/adrenalin, only if the heart rate/bp gets dangerously low, because as always in emergency medicine: Treat first what kills first --> which is also the reason why i would like to see a discussion and implementation of airway management giving the advanced medical system more depth while also allowing to stick more to the ABC scheme of treatment.

And yes, i will happily answer questions to that/ describe how that works, but that is for an other post, if this one gets read at all XD

**Comment by ssgsmith51** [comment]
I would add however that if we will incorporate the latest TCCC and 68W updates(I just went through the 68W sustainment course), hextend is no longer being recommended for in field care. They are pushing to limited fluids now instead of automatically doing one.two large bore(16-18g) IVs because there is no benefit besides a raise in BP. Which to that number is the sole reason to use something like Hextend since it is volumizer. The reason behind this(Explained to us) is that while the PT is getting adequate BP (100 sys) there is no ability for the fluid to hold oxygen, which is the only reason we want to keep up the BP so there is perfusion into the organ systems. Now they want fluid restriction unless the patient goes into arrest because a higher BP with any hemorrhage will result in the RBCs to be removed from the body. So the trauma doc's now want us to let the body to take over with compensated shock and if we do give fluids just give enough for compensated shock to persist. The medevac birds are now carrying whole blood and they are coming up with new equipment to allow medics to carry whole blood in the field for long duration(they told us up to 2 weeks). Its supposed to be some sort of vacuum sealed capsule that is resistant to temperature change. I just wanted to throw this out there since we are talking about keeping everything current. 

But everything else I agree with the OP, airway and the TQ changes would be great. But then for airway if we have a respiratory arrest will we need a second person to bag? That might be neat to see but in smaller groups it would be a pain. Unfortunately Ace Med has to juggle between real life while trying not to make the game one giant medical simulator and ruin the fun for other people.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
