### ISSUE TITLE
Bunch of bugs with medical menu

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#2528]
1. You can use medical menu on units that are very far
2. You cannot use drag from inside medical menu (option category is greyed out)
3. You can use "Stitch wounds" action on every body part but on old 3D medical you can use this option only on torso
4. STR_ace_medical_Activity_fullHeal http://images.akamai.steamusercontent.com/ugc/422566661700086717/D9C4BFCB60EA57B9404B975D4715009515E7E5E0/
5. Information on when something was given is shown in wrong format - in minutes as opposed to hours like in ACE3 3.2.x:  http://images.akamai.steamusercontent.com/ugc/422566661700086271/27A173CCA6E8A18756765541FE6262A28540495E/
6. Information that something was given X minutes ago is not always shown, may be related to issue above

All tested on dedicated.

**Comment by PabstMirror** [comment]
Fixed 4 and 5.

1. MEDICAL_ACTION_DISTANCE is 1.75m, the medical menu should be something similar.

2. We'll have to add to treatments, but dragging isn't guarented to be there, so we'll have to duplicate the strings, and add safe helper functions in case drag isn't there.

```
class Drag {
    displayName = CSTRING(drag);
    category = "drag";
    treatmentLocations[] = {"All"};
    allowedSelections[] = {"All"};
    treatmentTime = 0;
    allowSelfTreatment = 0;
    callbackSuccess = QFUNC(dragHook_startDrag);
    condition = QFUNC(dragHook_canDrag);
};
```

3. Not sure if this is error, it treatment effects the whole body is it really doesn't matter where it is called from, I think for 3d getting it off of limbs reduces clutter, but for the menu it really doesn't matter. (SurgicalKit/PersonalAidKit both have `allowedSelections[] = {"All"};`)

6. Is this caused by a specific treatment, or any way you can consistently reproduce this?

**Comment by gienkov** [comment]
Any treatment.

**Comment by PabstMirror** [comment]
six - Seems to happen when `ace_medical_enableFor` is 0.

treatmentAdvanced_bandage will exit to treatmentBasic_bandage before adding the log.
