### ISSUE TITLE
Disallow movement when reloading heavy weaponry

### ISSUE THREAD

**Issue by moonmanmove** [acemod/ACE3#2536]
I don't know whether this has been mentioned yet, but in ACE2 when you were reloading something that was pretty heavy like an m240 or a javelin, you had to stop to reload. can this be added to ace3?

**Comment by commy2** [comment]
Hello.

1. Feature requests usually go in #414.
2. Anything that was part of ACE2, AGM or CSE is automatically considered and doesn't need another request
3. I can't move while reloading a seondary weapon / launcher even in vanilla. My character always stops. Am I missing something?

**Comment by Przemro** [comment]
Well yes, you can move while reloading, you can`t move while switching weapon.

**Comment by moonmanmove** [comment]
@commy2 my mistake, should i repost this in the issue thread?

**Comment by commy2** [comment]
>Well yes, you can move while reloading, you can`t move while switching weapon.

@Przemro

I can't walk while reloading *a rocket launcher*

**Comment by commy2** [comment]
>my mistake, should i repost this in the issue thread?

No need to. It's reference there now by github magic.

**Comment by Przemro** [comment]
Well you can reload RPG-7 from RHS mod while running, even sprinting. Arma 3 RPG can`t be reloaded while running.

**Comment by commy2** [comment]
There is nothing we can do about it then.

**Comment by moonmanmove** [comment]
@commy2 
you can reload all of the vanilla arma 3 mgs (like the .338 MG and most of the other's that would  classify as an MMG or HMG)on the move, this was my main problem with it. If this could affect the weapons with the same inheritance for mods that would be pretty neat

**Comment by jokoho48** [comment]
@commy2 i think this is more a mod fault or a FR

**Comment by commy2** [comment]
I'll take a look. I doubt it's possible though.

**Comment by commy2** [comment]
Nope, not possilbe.
The reason why you can't move with vanilla lanchers is that they use "ReloadRPG" as reload action. This is not a gesture, but a proper animation. While in that animation you can't be in a walking animation at the same time. (This is the same reason why switching weapons on the move is impossible.)
That is different for gestures. You can be in an animation and do a gestures at the same time. All non-launcher animations in vanilla are gestures. Thats why you can move while reloading.
As for RHS my guess is that they use gestures for their RPGs too, because it's a pain in the ass to add animtions to the Arma animations config.
There is no way to convert an animation to a gesture and vice versa without having the source files for the .rtms.

**Comment by commy2** [comment]
Also ref: https://github.com/KoffeinFlummi/AGM/issues/62
I'm collecting the dups of this request.

**Comment by moonmanmove** [comment]
that's a real shame, thanks anyway
