### ISSUE TITLE
Always no pulse when people get shot and can't revive people

### ISSUE THREAD

**Issue by Dobakjang** [acemod/ACE3#2544]
As title said, can't revive people even i figure all wounded problem

**Comment by bux578** [comment]
Although we appreciate taking your time to submit an issue, please edit your ticket to follow the guidelines: http://ace3mod.com/wiki/user/how-to-report-an-issue.html

**Comment by tourist79** [comment]
@Dobakjang +@bux578: 

In order to save the hassle for unifying duplicate tickets, I'll provide a more detailed issue submission as comment to this #2544 here.  

ACE3 Version: 3.3.1 stable

Mods:

@CBA_A3
@ace

Placed ACE3 Modules:

medical settings
advanced medical settings
revive settings
set medic class
set medical facility
set medical vehicle
advanced ballistics
wind deflection
hearing
explosives
interaction
pointing
map
DAGR
name tags

Description:

According to the guidelines given in ACE3 Documentation, I set the above listed modules and within the revive module I set that revive time is 5 minutes and within the other modules I set that reving and unconsciousness apply to players and AI. 

As with my last report, surgical kits can be used anywhere, but Personal Aid Kits only at the medical facility and medical vehicle. Both can be used only by medics.  Whenever I wound an AI soldier enough to fall unconscious, I can use CPR on him, but I receive a script error on screen (see attached screenshots).  Another indication that CPR is broken is the fact that it doesn't "reset" the revive timer as it is supposed to do.  No matter how many rounds of CPR I administer, the wounded AI will always die after precisely 5 minutes. Also CPR never wakes up the wounded AI.  

For proof, see my linked repro mission, the screenshots and the RPT.

Steps to reproduce:

1) Place Rifle Squad with player as leader.


2) Place an advanced medical crate.

3) Place all the above listed modules and set them in the way that advanced medical system allows the use of the surgical kit anywhere, but the PAK only at medical facilities and vehicles.  Set revive time to 5 minutes and make it apply to players and AI.  Set unconsciousness as applicable for players and AI.

4) Make sure the player is set as medic via listing him in the set medic class module's field.

5) Shoot one of your soldiers full auto to inflict several wounds and make him pass out.

6) Grab all you need from the crate, then take care of the wounds, bloodloss, check pulse and heart rate, if no pulse give CPR once, stitch him up with surgical kit and give CPR again and again and again.

7) Observe how long after falling unconscious the wounded AI survives: always 5 minutes whether you give CPR once, twice or more often.

8) See this script error pop up each time you perform CPR: 
10:55:13 Error in expression <ocal.sqf"private " _reviveStartTime";
param ["_caller","_target"];if (_targe>10:55:13   Error position: <param ["_caller","_target"];
if (_targe>10:55:13   Error Type String, expected Number 10:55:13 File z\ace\addons\medical\functions\fnc_treatmentAdvanced_CPRLocal.sqf, line 6


9)If not reproducable: look for possible user errors made by me in creating my repro mission.


Where did the issue occur?

Editor, MP non-dedicated game

RPT log files: 

http://www.filedropper.com/ace3medicaltestrptfiles

or 

<a href=http://www.filedropper.com/ace3medicaltestrptfiles><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file storage</a></div>

Screenshots of script error: 

http://www.filedropper.com/cprerrorsace3

or 

<a href=http://www.filedropper.com/cprerrorsace3><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >upload files online</a></div>

Repro Mission:

http://www.filedropper.com/ace20medical20teststratis  

or 

<a href=http://www.filedropper.com/ace20medical20teststratis><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >online backup storage</a></div>

**Comment by PabstMirror** [comment]
CPR is bugged in 3.3.1, it should be fixed in next release (hopefully soon) via #2492

**Comment by Dobakjang** [comment]
NOPE STILL NOT WORKING test with 3.3.2
