### ISSUE TITLE
When I shoot an unconscious enemy AI, then animation bug occurs (sometimes)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2666]
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
None

**Description:**

Related to: https://github.com/acemod/ACE3/issues/2485#

I really appreciate the many details, that have been added to ACE3, but unfortunately loss of consciousness for the AI in the game is implemented poorly. First we have the bad animation of falling to the ground (#2485). Now I noticed, that if you will shoot(!hit but not kill them) at the already fallen soldier(who was unconscious) then sometimes this fallen soldier begins to twitch with super-speed. Unfortunately it's hard for me to record this moment, because bug occurs only sometimes, but I'm sure, that if you watch carefully for unconscious soldiers and shoot them, then you can watch this problem.  If any users have seen this problem also, please confirm this issue.

Any attempt to solve both problems with unconscious animation for the AI, will be greatly appreciated. Please pay attention to these details also.

PS: More than a two year! BIS is not able to solve the problem of hit in AI. 
http://feedback.arma3.com/view.php?id=12128
Such errors in ARMA3 looks like a real shame. Please solve totally this problem that can not solve BIS.

**Steps to reproduce:**
watch carefully for unconscious soldiers, which fall to the ground face down and shoot them.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment]
Same as #2657

**Comment by vlad8011** [comment]
Looks like Bohemia Developers dring too strong tea, or rather to drive tank with their new carton friend instead of fixing the bugs. Its pretty shame... 

Thank God there are people like ACE devs. Sorry for posting the idea which is actually in game (tank crew repairing vehicles, mechanic class etc.) i just didnt know you are so fast ;) You know the best what players need, and you are delivering it to us, as polish proverb says "May God reward you in children" :) :P ;)
