### ISSUE TITLE
Aqquirung the targer with javelin is almost impossible - Ai do it too fast

### ISSUE THREAD

**Issue by vlad8011** [acemod/ACE3#2686]
Aquire the target with ACE javeling is piece of art - first i need to aim little higher than target, second - frames around it are locking on all around it, makes aquire impossible in so small time (like AI). Swaying is killing it the most - beacuse of swaying i cant hold the sight on the target, so it is aquiring all round including building, objects, covers. try to aim the tank standing behind the sandabgs, and having building behind itself (2 layers of sandbags - one at 0 height, second on 0.5. Its impossible. Off course try to aim it inder fire and from the same haight as sandbags are.

**Comment by paul-hewson** [comment]
All i can say about this, it has become much harder to lock a vehicle since the initial release in may. The window for locking is smaller than what we see on the screen.

This leads to the problem reported by vlad, every object of the maps could break the lock easily. I don't remember this problem with the initial release, haven't used it much since June.


ACE3 Version: 3.3.2 (stable)

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
Haven't placed any modules in editor mode and reproduce. Got it with various framework mission. I don't think there is a special module to be place for that feature ? (if ace is on, it's new basic locking feature ?)


**Description:**
It's not an error, it's just a behavior and the fact that the locking window seems pretty smaller that the window reported when aiming.

**Steps to reproduce:**
Try to lock in a place with buildings/lights like an airport and some vehicules around.

**Where did the issue occur?**
Multiplayer/Editor, mostly tested in Chernarus airport where there is enough objects around that could prevent you from locking easily.

**RPT log file:**
No RPT, there is no real error. Only a problem with the locking window and that it may be to sensitive to "low heat items" around vehicles.
Not sure how a javelin behave in real life, but i were expecting it to lock on the most powerful source of heat ?

**Comment by vlad8011** [comment]
There should be turned off locking on objects not imitating hot, or limited only to vehicles(best way). Otherwise locking with jav is almost impossible
