### ISSUE TITLE
Map darkness/Brightness does not work on three monitors

### ISSUE THREAD

**Issue by hello12121212** [acemod/ACE3#2734]
Pulling up the map during nighttime with 3 screens only makes the center monitor dark. The other ones are default brightness

**Comment by MikeMatrix** [comment]
I'd recommend you read the [contribution guidelines](https://github.com/acemod/ACE3/blob/master/CONTRIBUTING.md) for creating an issue.

That out of the way, I think it's because of https://github.com/acemod/ACE3/blob/master/addons/map/functions/fnc_simulateMapLight.sqf#L25, which is using the `safeZoneW` command to calculate resolution. Probably have to switch that for [`getResolution`](https://community.bistudio.com/wiki/getResolution) instead.

I'll look into that when I get home tonight.
