### ISSUE TITLE
Hearing loss with small caliber rifles after explosion

### ISSUE THREAD

**Issue by ruPaladin** [acemod/ACE3#2754]
Modified ACE3 Version: 3.3.2, Arma 3 1.52 (stable)

Mods:
@CBA_A3
@ace

Placed ACE3 Modules:
None

Description:
I found that heraing loss from grenade explosion is hardly noticeable that is why I modified function  addons/hearing/functions/fnc_explosionNear.sqf
and replaced this:
_strength = (0 max _damage) * 30;
with this:
_strength = (0 max _damage) * 3000;

It works pretty well but I found a bug with hearing loss. After explosion you can hardly hear your MX shooting, then in 10-15 secs situation is better. But if you start shooting in auto mode with your MX, you will notice that hearing loss returns. Looks like after first run of hearing loss any other weapon sound (any caliber) will cause it again.

Steps to reproduce:
1. Change _strength = (0 max _damage) * 30; to _strength = (0 max _damage) * 3000; in addons/hearing/functions/fnc_explosionNear.sqf and pack it in PBO.
2. Run any mission and through frag grenade.
3. Stand in 10-15m from it when it explode.
4. Wait 10-15 secs and start to shoot with your MX rifle in auto mode. 

Where did the issue occur?
Checked in VR mission (not arsenal).

**RPT log file:**
* Add a link (pastebin.com) to the client or server RPT file.*

**Comment by PabstMirror** [comment]
@ruPaladin I think this behaviour is by design.

Try running with this updateVolume with some debug to see whats going on:

https://gist.github.com/PabstMirror/499c090d49e09a3fcccb

Then do `[player, 550] call ace_hearing_fnc_earRinging` so simulate a giant explosion causing massive hearing damage.

You should be completely deafened. Over time slowly your hearing recovers.  Shooting causes more damage so you go back to being deaf.

I could be wrong, so please let me know what you think.  Also I know explosives do too little damage, we have bumped it up in the past, but we might want to keep going.

**Comment by PabstMirror** [comment]
Does anyone have feedback on this issue?

**Comment by esteldunedain** [comment]
Obsolete
