### ISSUE TITLE
Loss of consciousness for AI happens too often (in medical settings - 50/50)

### ISSUE THREAD

**Issue by mickeymen** [acemod/ACE3#2764]
ACE3 Version: 3.3.2
Stable version 1.52

**Mods:**
* `@CBA_A3`
* `@ace`
* `@DragonFyre`

**Placed ACE3 Modules:**
Basic and Advanced Medical settings

**Description:**
In the basic settings of medicine, the player have the option to "disable" loss of consciousness for AI or set it to "50/50". The player has only two points! 
In my opinion this is a very narrow choice and also not realistic also unfortunately the loss of consciousness in ACE3 looks not best, for reason of bad animation. 
I already reported about it here: #2485 

So it seems to me, that the loss in 50% of cases is too frequent. 
I think the ratio to 70/30 or even 80/20 would look more realistic. Please to consider these proportions or extend the settings of the probability for loss of consciousness, thereby make them more realistic.

**Steps to reproduce:**
Shoot in the AI

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

**Comment by commy2** [comment]
Seems more like a feature request than a bug report.

**Comment by mickeymen** [comment]
This issue 3 in 1: feature request /bad ballance /not realistic detail

**Comment by Glowbal** [comment]
The 50/50 setting means that half of the AI that would enter the unconscious state, would die right away instead of staying unconscious. This is an optional setting and can be changed if you do not like this behaviour; you can disable unconsciousness all together for AI for example. That would mean that AI that would normally go unconscious, would instead be killed. The opposite is also possible.

**Comment by mickeymen** [comment]
"The 50/50 setting means that half of the AI that would enter the unconscious state, would die right away instead of staying unconscious" 
Why exactly half? It seems to me that the AI loses consciousness too often.

**Comment by commy2** [comment]
#414

**Comment by mickeymen** [comment]
Dear ACE3 team! My issue is not - "feauture request". This is  - "not realistic detail in the realistic mod". Indeed is a bug. Almost every my issue  is closed.Your  Feedback doesn't make sense/

**Comment by jonpas** [comment]
> Of course this is subjective opinion but additional settings (70/30 or even 80/20) will be greatly appreciated.

> I want to reduce the probability of unconsciousness, but have no way

These are both requesting for something to be added, hence why it's a feature request and not a bug report.

**Comment by mickeymen** [comment]
@jonpas my words only one way to solve the issue. While the 50/50 should ideally be removed in general, if ACE3 calls itself realistic mod. If every soldier will lose consciousness in 50% of cases, then all the wars on this planet will disappear

**Comment by jonpas** [comment]
> While the 50/50 should ideally be removed in general (if ACE3 calls itself realistic mod).

If it's a setting it doesn't mean ACE3 can't be a realistic mod, it is how you set it.

I am not saying you are wrong or anything, no one here is, we even agree with you. When one of the developers will be up to adding/changing the functionality, then they will do so, it has been noted, there are simply other priorities at this time.

This issue has been marked as a feature request because it's a request to add more functionality to already existing unconsciousness functionality. It has been tagged with feature requests issue to keep track of it easily.

**Comment by mickeymen** [comment]
Ok. thanks for your attention;)

**Comment by Glowbal** [comment]
The 50/50 setting does not determine how many units go into an unconscious state. It simply gives a 50% change of an AI to be killled when entering the unconscious state. It does not mean 50 out of a 100 go unconscious. It has nothing to do with an unconscious ratio, but rather the chance of a unit instantly being killed upon entering the unconscious state.

For simplicity; this setting has nothing to do with going / entering / becoming unconscious.

When a unit goes unconscious is determined by a combination of total damage and the damage amount done on a hit, plus the location where the damage is done (Head, Torso, legs or arms).

I hope this clears some of the confusion.

**Comment by mickeymen** [comment]
@Glowbal Yes, now I understand. But it's only numbers. In the any case, the player sees too frequent loss of consciousness of AI units. Thus, the player faces more often with: 1)lack of realism, 2)bad animation and even other problems. For example the enemy AI does not attack a unconscious soldiers  and this detail also looks is not good. Thus frequent loss of consciousness in the game creates a lot of small and frequent troubles. Why it required? Reduce the loss of consciousness for AI and you will reduce other bad items in the ACE3.

**Comment by dudakov** [comment]
> The 50/50 setting does not determine how many units go into an unconscious state. It simply gives a 50% change of an AI to be killled when entering the unconscious state.

If it's true, than this setting has wrong name and description.
In English strings it's called:
"AI Unconsciousness"
"Allow AI to go unconscious"

**Comment by Glowbal** [comment]
I think the description is correct, but do you have a suggestion for a better one?

It's about allowing AI to go unconscious. Not allowed equals death for an AI. It does not determine when or how many AI go unconscious.

**Comment by dudakov** [comment]
Ok. The name is not wrong but misleading.
I'll try to explain.

As a player I know that I will go unconscious if I got much injuries.
So I expect the same behaviour from AI. If I make AI much injuries he will go unconscious.

But what happened if I turn off the setting "Allow AI to go unconscious"? AI is not allowed to go unconscious. So he will be injured but he will stay conscious and shoot at me.

As you described above, this setting must have description like this:
"AI get instant death when go unconscious" or "AI get instant death instead of going unconscious".

**Comment by mickeymen** [comment]
Totally agree with @dudakov. Initially, the description of this setting led me astray.
