### ISSUE TITLE
Javelin functions fail on inherited ace_javelin_enabled config entry

### ISSUE THREAD

**Issue by Soldia1138** [acemod/ACE3#2854]
If a weapon (launcher) is a re-texture from one of the vanilla launchers (i.e. launch_O_Titan_short_F) and therefore inherits the config, including ace_javelin_enabled, the javelin features will not work.

IMHO the reason is here:
https://github.com/acemod/ACE3/blob/master/addons/javelin/functions/fnc_onOpticDraw.sqf#L39

As written in the configProperties BIKI description (https://community.bistudio.com/wiki/configProperties), the last parameter defines in inherited properties are check as well. It is set to false in the above linked function, consequently the launcher won't work.

**Comment by PabstMirror** [comment]
Javelin/missleguidance needs to be explicitly defined (non-inherited) in a weapons config.

This is by design because we found several cases were another mod made a launcher that inherited from the titan's and it would make no sense to run our javelin locking code.

For example RHS does:
`class rhs_weap_strela: launch_O_Titan_F`
`class rhs_weap_fim92: launch_O_Titan_F`.

What you can do is have the mod author just add a config entry for `ace_javelin_enabled` on their inherited weapon, eg:

```
class your_titan_F: launch_O_Titan_F {
    model = "retexture";
    ace_javelin_enabled = 1;
};
```

**Comment by Soldia1138** [comment]
Almost thought so, thx. 

Will contact the mod author (or fix it at our end)
