### ISSUE TITLE
Advanced Medycal system problem

### ISSUE THREAD

**Issue by BreberaCZ** [acemod/ACE3#2855]
Hello
I would like to report you a little problem that is our Arma 3 milsim group experiencing last few weeks. 
We are playing with advanced medical system, advanced wounds turned off (the same when turned on) and Medkit + surgical kit usable on stable patient. The problem is, that the patient could be stable on 100%, with no bleeding, no wounds, no pain, but he wont get up even with blood preasure and pulse okay. CPR and Epinefrin don't work. The only way to make people get up is by using a Medkit on the. 
Hope you will repair it soon ! (:

**Comment by Glowbal** [comment]
Are you using revive?

**Comment by xJenny99x** [comment]
Wouldn't revive cause hr to be 0?

**Comment by BreberaCZ** [comment]
revive ?

**Comment by BreberaCZ** [comment]
hr is usually at normal aswell.. maybe if there is revive modul, I forgot to place it .

**Comment by madpat3** [comment]
-ACE3 v.3.3.2
-stable
-mods:@cba_A3, @ace
-all medic modules

your list in your ace-wiki http://ace3mod.com/wiki/feature/medical-system.html doesn't work for me.
since i can use nearly any bandage on any wound. no matter how big the wound is, nor what kind of a wound it is, 
it always cures the injury. 
-place the modules place an ai unit,
-hit it with- and however you want to.
-do medical assistence to it like advised in the ace-wiki and try the opposite of advise.

-testet in editor with ace and cba with all referred modules on difficulty level elite(against AI), 
-driven by recognizing the issue in MP on dedicated server, along with other mods (i.g. DCG as mentioned above) - level elite(against AI). 

Rpt:
http://pastebin.com/Dp9Skg1j

**Comment by BreberaCZ** [comment]
There is bug, that causes whenever you take damage that takes you down, you HR is automatically lowered to 0 and cannot be raised anyway.

**Comment by madman2093** [comment]
I am having the same problem with medical system and having to us the personal first kit top get people up because of them not been got up by cpr or epy

**Comment by BreberaCZ** [comment]
Its okay now, last patch fixed it. Thanks
