### ISSUE TITLE
Machinegun belt linking bug

### ISSUE THREAD

**Issue by Pasrules** [acemod/ACE3#2881]
When linking a new belt onto a machine gunner who is firing the ammo type must match exactly eg.
standard rounds can't be linked to tracer rounds.
This is strange as the entire box of ammunition is replaced so it should seem normal to change ammo type.

If a machinegun has no ammobox in it then the option to link belt is removed.

Also is there any possible way to have more than the maximum ammount of ammo from this linking feature? I would assume not for multiple reasons.

**Comment by commy2** [comment]
You can mix and match tracer and non-tracer magazines in Arma.
There are some hard-coded values like `tracersEvery` and `lastShotsTracer` [or whatever they are called], but those are config entries and can't be changed while the game is running
You also can't go above the maximum magazine ammo count.

Close because this has no chance of getting added?

**Comment by Pasrules** [comment]
Thankyou for the response, I had thought the script just replaced the ammo box whilst firing but cleary this isn't the case.

**Comment by commy2** [comment]
We will keep this in mind should BI ever change anything about how tracer rounds / magazines are handled by the game (which is unlikely though since this is basically the same as it was '01)

#414
