### ISSUE TITLE
7.62x51 is less lethal than 5.56x45

### ISSUE THREAD

**Issue by Gwynblade** [acemod/ACE3#2931]
ACE3 Version: 3.4.0

**Mods:**
- `@CBA_A3`
- `@ace`
- `@ace_server.pbo` (so I can force advanced medical)

**Placed ACE3 Modules:**
None

**Description:**
It takes 3-4 (usually 3) torso shots to kill AAF unit with 7.62mm. It takes 2-3 (usually 2) torso shots to kill the same unit with 5.56mm. Advanced medical is enabled for both player and AI.

**Steps to reproduce:**
https://www.youtube.com/watch?v=SnNaj9FHFfQ&feature=youtu.be

**Where did the issue occur?**
Tested in multyplayer and editor, same results.

**RPT log file:**
Don't have one, because I'm using -nologs. If absolutely necessary, I can test again without -nologs.

**Comment by Rockfrog** [comment]
I don't know if it's by ACE design, but technically speaking 5.56 rounds do more damage in RL than 7.62, and it's the main reason 'the world' moved to 5.56 weapons over the 7.62 weapons of post WWII to 70s.

5.56 rounds deform when they hit the human body, and then tumble as they go through the body causing massive damage, and usually don't exit the body.

7.62 rounds enter through a small hole, usually go straight through, and come whizzing out the other side through a small hole (unless it's your skull of course).  Small holes, less damage.

Why use 7.62?  They fly significantly truer and further, so for accurised fire for DMR and/or sniper rifles it's much better to use 7.62 weapons.  Hit people further away, some times twice as far away.

Right round for the right job ;)

**Comment by Gwynblade** [comment]
I figured it's probably a bug, since in ACE2 7.62x51 dealt a lot more damage than 5.56, in vanilla ARMA 2/3 it deals more damage too. You do seem to make some valid points though (I say seem, because I don't know much about wounding, and have any real experience only with 7.62x39 and 7.62x54).

But what you said above, wouldn't that be the case if the bullet was hitting unarmored targets?
If the target is wearing a bulletproof vest, shouldn't 7.62x51 punch through easier than 5.56, and in that way, cause more damage with less bullets?

**Comment by Rockfrog** [comment]
7.62 rounds also don't fragment, where as 5.56 do, this is another of the things which creates permanent cavitaion (the big hole it makes as it goes through the body), hence greater wounding potential.

I'd suggest the A2 damage model by BI wasn't the best TBH.

I don't profess to understand how standard rounds of either type perform on soft tissue once passing through armour.  I'd say at a top level, that would depend what type of 5.56 or 7.62 round you're using (as there are plenty, some more armour piercing than others), and of course the quality and type of the armour you're punching through.  Or not.  I'd say given those variables, trying to model that would hard to impossible.

Round vs the human body is the only thing you can really use as a control/level state.

**Comment by Gwynblade** [comment]
Hm, I think you misunderstood me. I didn't mean how much damage they cause after both of them pass through the armor, if they do pass they will both do enough damage as it is (even **if** the 5.56 is indeed more dangerous).

What I meant is, 7.62x51 should actually penetrate the bulletproof vest with less bullets than 5.56 (I'll explain at the bottom why I think this is important). Let me just give you an example.

Let's say you have the same type / quality ammo (5.56x45 and 7.62x51).
You fire three 5.56 rounds in one plate, and three 7.62 rounds in the other. No penetration.
You fire 1 more bullet in both, 5.56 stops, 7.62 passes - which in turn is more damage.
You fire 1 more bullet in both, they both pass - even if the 5.56 causes more dangerous wounds, two shots to the chest by 7.62 should still be more dangerous than one of 5.56.
(these numbers are not accurate, it's here just as an example, and to explain to you what I meant)

Now as promised in the beggining, to explain why I'm bringing this up.
Pretty much everone in A3 has a bulletproof vest, so it's hard not to take it into an account, especially since (with ACE3) you can take 3 rounds of 7.62x51 in the chest and survive. It does not seem likely that you could survive that in real life without a bulletproof vest. Even in an extremely lucky case you do survive, I don't think you would get up in the next 10 seconds and just bandage yourself.

So, either they are taking the bulletproof vest into account by some degree, or this is a bug.

**Comment by JamesTheClarke** [comment]
I wonder if this was also the case before v 1.54. Unfortunately our community rarely ever uses vanilla assets so I can't confirm whether or not 5.56mm always was more deadly with ACE3 on or not.

But this could very well be connected to the vanilla vest update and not yet fully compensated for by ACE3.

**Comment by commy2** [comment]
>in vanilla ARMA 2/3 it deals more damage too.

There you have your answer.

**Comment by Blutulme** [comment]
The main reason most military moved to 5.56 is that the average soldier can carry more ammunition and the the recoil of 5.56 is easier to handle. That the bullets break was not intended initially, they where surprised that they did. 

5.56 was made to wound soldiers, 7.62 was made to kill.
The more wounded soldiers the other side has to take care of, the more soldiers are not on the field fighting against you.

Besides, if the bullet breaks and doesn't makes it through the body armor it will not do any lethal damage. Perhaps not even damage anything at all. Yes the 7.62 can also be stoped by body armor, but it has a greater penetration and will therefore more likely penetrate the armor.

7.62x51 has greater penetration & effectiveness at greater ranges at the cost of weight and recoil.
5.56x45 has less weight/recoil and a flatter trajectory but at the cost of penetration & effectiveness at longer ranges.

The 7.62x51 and the 5.56x45 are both lethal against soft targets.

It's quite different with armored targets.

The 5.56 is known for lacking stoping power against soldiers and vehicles where the greater penetration and energy of the 7.62 is more usefull.

If the bullet fragments or not has nothing to do with the caliber, but with what kind of bullet you use.
AP rounds will both pass through and don't break. If you use soft metal the bullets will break or deform and do more damage.

Example for different bullet types: https://www.youtube.com/watch?v=U0NTjd-Cx0I

The are many different bullet types. A catalogue form just one producer: https://nammo.com/globalassets/pdfs/ammobook/nammo_ammo-handbook_v3_2015.pdf

Conclusion
Saying one caliber is more lethal than the other is bullshit because thats not all that counts.

**Comment by Gwynblade** [comment]
Well you're from what I see, you're pretty much confirming what I said. It definitely should not be harder to kill someone with 7.62x51 than 5.56, quite the contrary.

I had a real short chat with commy2 a while ago, he said if 7.62 deals more damage in vanilla, then it's probably not intended to deal less in ACE3.

Also, **please** consider fixing this before 3.6.0 (3.5.1 maybe)? I'm generally patient, but this one has a huge impact on gameplay:

Whenever I get any kind of marksman role (mk14 ebr or rahim) I just take the scope, and dump the marksman rifle for a regular rifle first chance I get.

Or for example, why would you take M240 (7.62x51mm - 100 rounds) if you have a chance to grab M249 (5.56mm - 200 rounds). As it is, M249 kills faster, has less recoil, and to top it off, you get twice as much ammo to shoot without reload.

**Comment by DJ-Reticuli** [comment]
"but technically speaking 5.56 rounds do more damage in RL than 7.62, and it's the main reason 'the world' moved to 5.56 weapons over the 7.62 weapons of post WWII to 70s"

Wrong.

**Comment by DJ-Reticuli** [comment]
> I don't know if it's by ACE design, but technically speaking 5.56 rounds do more damage in RL than 7.62, and it's the main reason 'the world' moved to 5.56 weapons over the 7.62 weapons of post WWII to 70s.

US moved to 5.56 to give soldiers more rounds on a lighter, potentially shorter gun, that had less recoil. Compared to getting shot with 9mm or a 22LR, certainly 5.56 is far more lethal.  Unless 5.56 is tumbling after transitioning to subsonic and being really unlucky, though, its entry hole, and sometimes its exit, too, is always smaller than 7.62 NATO.  The 5.56 round *may* tumble after impact but doesn't always.  7.62 NATO has uniformly excellent stopping power regardless of whether it happens to tumble, including in comparison to 5.56.  This is one of the reasons after Mogadishu the US started investigating an alternative to 5.56 while trying not to have the recoil of 7.62 NATO, as well as why US SOCOM started increasingly using 7.62 NATO again.  The GWOT further motived both more use of 7.62 NATO, as well as transitioning to something else due to being outranged when using 5.56 against Taliban who were using old Russian guns, but I digress.
