### ISSUE TITLE
one shot one kill

### ISSUE THREAD

**Issue by Doosan123** [acemod/ACE3#3001]
ACE3 Version: 3.4.1

**Mods:**
* `@CBA_A3`
* `@ace`
* `@TRYK`

**Placed ACE3 Modules:**
* No Modules

**Description:**
We never ever edit any modules in map, We tested one of player and one AI , after player shoot at AI's body and then AI dies at a one shot

**Steps to reproduce:**
*We pressed "New" and opened the "ALTIS" map, we summoned NATO AI and one of the player (user), and then player (user) shoots AI's body, AI dies at one shot.

**Where did the issue occur?**
* editor / multiplay

**RPT log file:**
https://youtu.be/RpUJbW1Koco

**Comment by TheGrandVizier** [comment]
Tryk gear is not updated for 1.54 as far as i know. 
Uses old system of hitpoint.
Not compatible with arma 1.54.

Correct me if i am wrong, anyone?

**Comment by Doosan123** [comment]
normal vest also dies in one shot at body.

**Comment by Glowbal** [comment]
Well you are standing within 3 meters. What is your expected behaviour?

**Comment by Doosan123** [comment]
https://youtu.be/u_NffoFsQWA    < Plz check this video

**Comment by commy2** [comment]
First of all, I can't reproduce. It's working fine on my end, no matter which release or branch I'm on.

Secondly, the opening post has no RPT log file. In fact it's just a link to a youtube video.

RPTs are located at `"C:\Users\<USER>\AppData\Local\Arma 3"`

I suggest you start your game without `@TRYK`, because even though you are shooting at uniforms from the base game, that does not mean that `@TRYK` does not accidently alter _certain_ config values.

**Comment by commy2** [comment]
Same as #3006
