### ISSUE TITLE
one shot one kill 2

### ISSUE THREAD

**Issue by Doosan123** [acemod/ACE3#3006]
ACE3 Version: 3.4.1

Mods:
• @CBA_A3 
• @ace  

Placed ACE3 Modules:
•No Modules

Description:
 We never ever edit any modules in map, We tested one of player and one AI , after player shoot at AI's body and then AI dies at a one shot

Steps to reproduce:
 *We pressed "New" and opened the "ALTIS" map, we summoned NATO AI and one of the player (user), and then player (user) shoots AI's body, AI dies at one shot.

Where did the issue occur?
•editor / multiplay

RPT log file:
http://pastebin.com/zTfTh3aJ

Youtube
https://youtu.be/oPcIkryecjw

**Comment by Doosan123** [comment]
wut dose that mean the thing is written Armor Level 3 beside the vest name calls Carrier Lite[GReen]

**Comment by commy2** [comment]
>wut dose that mean the thing is written Armor Level 3 beside the vest name calls Carrier Lite[GReen]

I have no idea. A higher number probably means that it offers more protection.

Since we can nothing do about the uniforms from `@tryk` and the same happens in vanilla, I'll close this.

Please ask the author to adjust their mod for 1.54. A discussion can be found here:
https://forums.bistudio.com/topic/172261-tryks-multi-play-uniforms/page-28#entry2948574
