### ISSUE TITLE
T-10D Parachute

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3048]
@ohally has given me permission to implement his T-10D Parachute mod into ACE3. Problem is I don't know where to start, so I'm just gonna write what info I've found about it and just gonna donate it to you, devs.

> T-10D Parachute is a static-line trainer-combat parachute that is not steerable and is used for airborne operations.
> 
> The entire assembly weighs 31 pounds (14 kg). Paratroopers can be dropped from an aircraft at a maximum speed of 173 mph (150 kn), at a minimum of 500 ft (150 m). Maximum jump wind speed is 15 mph (13 kn).
> ![](http://americasarmy.pl/zdjecia/1049365059spadochront10c.gif)
> ![](https://upload.wikimedia.org/wikipedia/commons/d/d4/SCIE_T10_image1.jpg)

https://www.dropbox.com/s/vwnh57m4xl6a0y1/oh_round_chute.7z?dl=0

**Comment by jokoho48** [comment]
@gienkov i cant work with that because the P3D is Binarised. we need the source Files to make this work right

**Comment by gienkov** [comment]
I'l try to get them :)
18 gru 2015 15:07 "Joko" <notifications@github.com> napisał(a):

**Comment by ohally** [comment]
sent source files via BI Forums

**Comment by gienkov** [comment]
https://www.dropbox.com/s/j2a9q13an39k864/oh_round_chute.7z?dl=0
19 gru 2015 5:11 AM "ohally" <notifications@github.com> napisał(a):

**Comment by p1nga** [comment]
It needs LODS,  i took a quick look and made a working test inheriting from the NonSteerableParachute classes in ARMA3.  But yeah the biggest thing is LODS, 5k Verts is alot for a single LOD of an object that might be drawn many times on a screen at some distance.   I would also do a couple of shadowvolumelods, and set them to use the shadowbuffer instead of shadowvolume,  be able to have some quick decent shadows then.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
