### ISSUE TITLE
Ace 3 Self Interaction is not working but the External Interaction is.

### ISSUE THREAD

**Issue by AllenKalashnikov** [acemod/ACE3#3066]
For some reason I can Interact with certain objects like a vehicle and an ammo box but I can not interact with another person or with myself. 

[RPT.txt](https://github.com/acemod/ACE3/files/69018/RPT.txt)

**Comment by PabstMirror** [comment]
Double check launch params, I don't see any ace pbos loading in that RPT.

**Comment by commy2** [comment]
1. remove `@45thcba_a3` and `@45th_V4`
2. download latest CBA http://www.armaholic.com/page.php?id=18767
3. download latest ACE https://github.com/acemod/ACE3/releases

**Comment by PabstMirror** [comment]
@AllenKalashnikov is this still a problem?

**Comment by Furia139** [comment]
Me and my firends have the same problem. Curious thing is that when we play SP or with the editor, both interaction menus work good. If I host a mision in my machine both of my interaction menus work good but my friends menus only work with external interaction. Funny thing is that when I set up a dedicated server in my own machine and I log as client I have then the same problem as my friends. My external intercation menu works but the self interaction menu does not.

We do have CBA version 2.2.0.151130  and ACE3 version 3.4.2
I have tried to find the files mentiones by commy2 the  @45thcba_a3 and @45th_V4  but I cannot find those files on my system.

Any help would be most appreciated. We are about to start a campaing and ACE3 is one of our core mods and we cannot use it fully with this issue.

Thanks!!

**Comment by esteldunedain** [comment]
@Furia139, you need to upload your own RPT log

**Comment by Furia139** [comment]
Sorry I forgot. here it is

[RPT.txt](https://github.com/acemod/ACE3/files/105419/RPT.txt)

**Comment by esteldunedain** [comment]
@Furia139, you problem seem to be that FFAA MOD V6.0.3 units are not correctly supporting CBA event handlers.

**Comment by Furia139** [comment]
ok but I am not sure this is an issue just related to the FFAA MOD. Curiosly I can us the Interaction menu nicely in Multiplayer if I am the host but not when I am a client.
I have also seen other people in other forums having this issue with other units and Mods.
I have found in some forums some people had a similar trouble with A2OA and some people mentiones the issue was related to the "player identity" in multiplayer. 

Pls let me quote:

"Are you using PlaywithSix, Six Updater or launching manually? As the way to ensure it's setup correctly differs for each.
It comes down to the 'Steam\steamapps\common\arma 2 operation arrowhead\userconfig\ace\ace_clientside_config.hpp'
Specifically the line :
'#define ACE_IDENTITY John Doe'
Where John Doe should be your username. You can either set it manually then set the file to read only, or click the Ace mod in PlayWithSix, click settings and set the correct profile in there.
As others have suggested, running Ace.clippi \@ace\clippi\aceclippi.exe, clicking manual options and setting the correct profile there will set it up, though if PlayWithSix isn't correct it might interfere when you launch it through there."

however neither ACE3 neither A3 has such folders and exe files to check.

**Comment by esteldunedain** [comment]
> I have also seen other people in other forums having this issue with other units and Mods.

Yup, all the mods that don't properly support CBA fail with ACE unless that Pbo is added.

> I have found in some forums some people had a similar trouble with A2OA

ACE has been completely rewritten since ACE2; the issues are totally unrelated

**Comment by Furia139** [comment]
Seems it also fails with the Independent force units from the Arma 3 stock version not just with the FFAA Mod

17:56:15 [ACE] (interact_menu) ERROR: Compile checks bad for (classname: I_Soldier_SL_F)(addon: ["A3_Characters_F_INDEP"]) R Alpha 1-1:1 REMOTE
17:56:15 [ACE] (interact_menu) ERROR: Compile checks bad for (classname: I_soldier_F)(addon: ["A3_Characters_F_INDEP"]) R Alpha 1-1:2 REMOTE
17:56:15 [ACE] (interact_menu) ERROR: Compile checks bad for (classname: I_Soldier_LAT_F)(addon: ["A3_Characters_F_INDEP"]) R Alpha 1-1:3 REMOTE
17:56:15 [ACE] (interact_menu) ERROR: 14 Classnames failed compile check!!! (bad XEH / missing cba_enable_auto_xeh.pbo)

**Comment by Furia139** [comment]
Just as extra information  I have modified the same mission  to use the old AGM Mod instead the ACE3 and this way the interaction menu works Ok.
Since I am also using CBA and the FFAA Mod this way I am really not sure if the error I have initially mentioned is just directly realted to the interaction between the FFAA and the CBA

**Comment by commy2** [comment]
The AGM interaction menu works differently.

**Comment by CallsignVoodoo** [comment]
I'm having a similar issue, however mine is the opposite. Self interaction works but the interaction menu doesn't work at all. When I hit the interaction key, the red circle freezes and until I hit the key to open the self interaction, it stays there. After that point, I can't use the interaction menu at all.

**Comment by esteldunedain** [comment]
@CallsignVoodoo, that's certainly a different issue. Please open a sepparate issue and provide the relevant information (RPT).
