### ISSUE TITLE
Feature Request: Add easy options to enable or disable modules

### ISSUE THREAD

**Issue by kevinfoley** [acemod/ACE3#3081]
ACE3 is considered to be not compatible with ARMA 3's campaign or single-player showcases because certain modules (particularly medical* and demolitions**) completely break single-player missions that weren't designed for them. However, many other modules, including AI improvements, better ballistics modelling, etc, work fine with the campaign and showcases.

Simply removing the files for the problematic modules solves the problem, and ACE3 will work fine with the campaign and single-player missions. However, this is not a good solution, *because the files will be restored each time ACE3 updates*. This could easily be solved by allowing the user to enable or disable modules in the menu, or in some settings file that won't get overwritten each time ACE updates.

*Team AI does not know how to use the medical system. Missions can break when mission-critical AI become incapacitated but are still alive
**Any time the player needs to plant or disarm explosives, they will not have all of the relevant equipment

**Comment by MikeMatrix** [comment]
Thank you for your contribution, but make sure to check out [How to make a feature request](http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html) on our Wiki, as well as #414.

As for the request itself, it's currently not really possible to simply remove any of the modules without removing the files, because of some technical limitations.
The main focus of the mod is on MP games, so SP/AI adjustments are on a lower priority.

**Comment by TheConen** [comment]
You can use the ACE3 settings framework for that: http://ace3mod.com/wiki/framework/settings-framework.html

**Comment by jokoho48** [comment]
@TheConen the Problem behind that is that you cant disable the Medical Features because we Change Config Values and that are not "SQF side" Revertable

**Comment by commy2** [comment]
Config values cannot be changed on run time. If it were possible it would be part of ACE. (And AGM way back).Close?
