### ISSUE TITLE
RHS Explosives ACE Interaction/ SMAW Buddy Reload

### ISSUE THREAD

**Issue by armyinf0703** [acemod/ACE3#3152]
Has anyone done an ACE Compat work for the Explosives (C4/Mines) to work with Ace explosive clackers/ switches.

Also what is the best way to shorten the Rocket Reload time when using the SMAW Buddy reload. It currently takes ~12 seconds to reload the smaw with a buddy, which is a long time, to really just pop off the spent casing/ replace with fresh casing.

**Comment by commy2** [comment]
>Also what is the best way to shorten the Rocket Reload time when using the SMAW Buddy reload
The reload time the guy with the launcher experiences is a bug with a scriting command used:
http://feedback.arma3.com/view.php?id=21469#c100997

**Comment by sargken** [comment]
How is this BIS fault.

**Comment by esteldunedain** [comment]
> How is this BIS fault.

The reload time the guy with the launcher experiences is a bug with a scriting command used:

**Comment by sargken** [comment]
The buddy reload part can be added in rhs combat pbo.

**Comment by dixon13** [comment]
@sargken The issue cannot be fixed at this time because there is an issue with the scripting command. Once BIS fixes the issue with the scripting command the issue should be solved. The buddy reload system does not need to be added into the rhs compat PBO. It could possibly be altered to work with the ACE menu? Not sure, I would have to mess around with it, but right now nothing can be done because the scripting command that is used in RHS's script is broken.
