### ISSUE TITLE
Search Weapons List

### ISSUE THREAD

**Issue by CarlosHathcock** [acemod/ACE3#3176]
I like to play as a sniper. The problem is that I do not know the data of the weapon. So Bullet weight or so. I do not get the list: https://github.com/acemod/ACE3/blob/master/extras/CfgAmmoReference.hpp
where For example, the LRR or the GM6 Lynx? The weapons of the list are only mods or? I hope you can help me.
PS: I LOVE ACE3 <3  :+1:

**Comment by madpat3** [comment]
for the lrr and the gm6 you just have to open the gunlist and select the right caliber/ammotype and click open gun.
other weapons may vary, because some use the same ammo, but have different values in muzzle velocity and Barrel Twist. so u have to edit them with help of your list.

please ace Team update the gunlist, so every weapon is listet with every type of ammo.

**Comment by esteldunedain** [comment]
I don't think it's our place to document the ballistic parameters of each weapon.

ACE ballistics are so realistic enough that all that data can be grabed from RL publications, like wikipedia. Trajectories can be calculated using any ballistic calculator out there, and also the ATrag device in-game. Also extensive shooting practice on a range in-game is necessary when using this feature.

I hope that helps. Thanks for the ticket.

**Comment by DJ-Reticuli** [comment]
Fair point, but in nearly all ACE ammo, the hit values are higher than the default ammo, even for stuff that's just supposed to have a higher BC.
