### ISSUE TITLE
Question about bandages

### ISSUE THREAD

**Issue by Przemro** [acemod/ACE3#3322]
So my group is using advanced medical system, (we aren`t very about realism) we use only QuickClots. My question is about how "good" should be this QuickClots?

Sometimes after hit it takes like 5 or more QuickClots to stop bleeding (let say it is leg velocity wound from AK-74, from about 150m), but on your wiki it is said to have high effectiveness, by high I would think about 2 QuickClots to stop bleeding ( 3as maximum). When in the same sytuation 1 packing bandage should be enough since it is the best for it.

So is that correct or it is bug, or it is something I am doing wrong?

**Comment by PabstMirror** [comment]
We are working on this issue as part of overall issue #3134

3.4 changed so that wound type has an effect on bandage effectiveness
refer to http://ace3mod.com/wiki/feature/medical-system.html#bandages-effectiveness

Some wound types do not react well to quickClot like Avulsions.  But I think we are going to tweak this in next release: (ref 86158ac45b5e9ce200be5fc65d585d9ee4b9a5d4)

**Comment by Pergor** [comment]
I made this little chart for my community: http://spezialeinheit-luchs.de/uploads/ace_medical.jpg
The first number is the fraction of wound a bandage will patch up and the second number is the probability the wound will reopen.
0.7/0.1 means: It heals 70% of a wound and will reopen with a chance of 10%.
Green is good, yellow is fine if you can sew the wound directly after bandaging. White is bad.

**Comment by madpat3** [comment]
schöne grüsse aus dem digitalen düren!
hab so eine ähnliche tabelle fürs "jgbtl|533" gemacht; man sieht sich auf dem virtuellem Schlachtfeld XD
![ace bandagen](https://cloud.githubusercontent.com/assets/15272840/13150935/1af9b9de-d668-11e5-906a-ed3a5f4a7de9.jpg)
