### ISSUE TITLE
Enable hit reactions even when not jogging

### ISSUE THREAD

**Issue by nicolasbadano** [acemod/ACE3#3452]
It would be a simple way of preventing units looking like bullet sponges when shot in the limbs. IMO it doesn't look that bad.

Hit reactions when walking:
https://youtu.be/4-mrgDI95mY

Hit reactions when standing:
https://youtu.be/4hFZLaPjZHU

All of this is only a matter of changing one line:
https://github.com/acemod/ACE3/blob/master/addons/hitreactions/functions/fnc_fallDown.sqf#L65

**Comment by vlad8011** [comment]
Indeed, it look almost very nice :)

**Comment by captainblaffer** [comment]
My opinion, I never liked this feature because it takes the control of the player character out of their hands. They suddenly go prone and may not understand why. 
It also makes for very messy TVT situations, where players snap to prone mid-combat. Do we not remember the horrors of call of duty insta-prone tactics?

**Comment by bux578** [comment]
@captainblaffer delete hitreactions.pbo if you don't like it

**Comment by captainblaffer** [comment]
Sorry, didn't realize this feature is packed into a single pbo, (without any other features included).

For people who do want this feature, yeah this could be a nice change. Makes it behave more consistently also(from player's perspective).

**Comment by esteldunedain** [comment]
> Sorry, didn't realize this feature is packed into a single pbo, (without any other features included).

@captainblaffer: There's also a setting that controls the damage threshold that triggers reactions, `ace_hitreactions_minDamageToTrigger`. Higher means you have to receive a bigger hit to make you react. Also the behaviour is completely disabled if you set that parameter to -1.

**Comment by captainblaffer** [comment]
@esteldunedain Thanks. Can I change that variable in a mission real time?
Or does it need to go in a config file?

**Comment by esteldunedain** [comment]
You can change it in real time, no problem.

**Comment by esteldunedain** [comment]
but obviously the "correct" way of doing is on the server userconfig or on description.ext

**Comment by Gwynblade** [comment]
Got to say, the moonwalk slide looks really weird to me. But I'm gonna ignore it, and look on it from gameplay perspective.

Hit reactions currently have a nice impact to gameplay. Running exposed (from cover to cover for example) is risky even if the enemy is far, if they hit you, you fall in the open and you're a sitting duck.

The new hitreactions could have a nasty side effect. Since if the enemy is standing in a place, it's safe to assume he will have cover, similar to you in the video. Hitting him in a limb automatically puts him in cover, so you can't do follow up shots like you can with standing targets - it kinda rewards the guy that got shot. I can see this turning (medium-long range) firefights into a crapshoot, hit a guy in a limb, he goes down, wait for him to get up, accidentaly shoot the limb again... I could be wrong though, we'll have to see.

Also, I can see why a guy that gets shot in the leg would fall down, but arm shots don't look very convincing, especially since when you shoot him in the torso next to the arm, he just flinches.

For upper body shots, I think rotating the player a tiny degree left or right, just to throw him of target would be better, and more punishing.

All this, **only my opinion** of course :)

**Comment by esteldunedain** [comment]
> Hitting him in a limb automatically puts him in cover, so you can't do follow up shots like you can with standing targets - it kinda rewards the guy that got shot. 

I imagine a similar thing happens IRL. It will increase survivability for sure, which I don't think is a bad thing for players.

> especially since when you shoot him in the torso next to the arm, he just flinches.

That's was a shot in the vest, hence little/no damage was taken and no hitreaction was triggered.

> For upper body shots, I think rotating the player a tiny degree left or right, just to throw him of target would be better, and more punishing.

That's not a bad idea.

I'd love to make reactions depend on which part of the body was hit. That's however quite complex to code, because the `hit` event handler doesn't indicate where the bullet hit. We do have the bullet position, so it may be possible to estimate. Or it could be used in combination with the `handleDamage` event, but I think there's some locality issues. It's certainly something to investigate.

**Comment by Gwynblade** [comment]
> I'd love to make reactions depend on which part of the body was hit.

That sounds great, hopefully it's doable at some point :)

**Comment by john681611** [comment]
I think this would probably do best with a optional level (off/basic/advanced) . Then as long as suitable animations can be found/ made the sky is the limit. It would be really cool to have the possibility to drop a weapon when hit in a certain place making capturing a armed individual possible.

**Comment by esteldunedain** [comment]
> I think this would probably do best with a optional level (off/basic/advanced) 

Certainly it would have settings.

> possibility to drop a weapon

And yet such a simple thing is currently impossible to do right with the existing scripting commands.

**Comment by commy2** [comment]
I rewrote this: https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_dropWeapon.sqf
But the weapon will be dismantled, which is really annoying.

**Comment by esteldunedain** [comment]
"Ups, I got shot and my weapon fell to the ground and exploded into pieces"

So yeah, still impossible to do right

**Comment by PabstMirror** [comment]
```
private _weaponToCopy = currentWeapon player;

dummy = createAgent ["C_man_1", position player, [], 0, "FORM"];
hideObject dummy;

dummy addWeapon _weaponToCopy;

wh = "WeaponHolderSimulated" createVehicle (position player); 
wh addItemCargoGlobal ["ACE_DebugPotato", 1];

dummy action ["DropWeapon", wh, (currentWeapon player)];
diag_log text format ["Start [%1-%2", diag_tickTime, diag_frameno];

[{
    params ["_args", "_pfID"];
    _args params ["_dummy", "_weaponHolder", "_weaponToCopy", "_startTime"];
    
    if ((isNull _dummy) || {isNull _weaponHolder} || {time > (_startTime + 3)}) exitWith {
        deleteVehicle _dummy;
        deleteVehicle _weaponHolder;
        [_pfID] call CBA_fnc_removePerFrameHandler;
        diag_log text format ["End Err [%1-%2", diag_tickTime, diag_frameno];
    };
    if (!((getWeaponCargo _weaponHolder) isEqualTo [[],[]])) then {
        player removeWeapon _weaponToCopy;
        _weaponHolder setPosATL (getPosATL player);
        deleteVehicle _dummy;
        clearItemCargoGlobal _weaponHolder;
        [_pfID] call CBA_fnc_removePerFrameHandler;
        diag_log text format ["End Good [%1-%2", diag_tickTime, diag_frameno];
    };
}, 0, [dummy, wh, _weaponToCopy, time]] call CBA_fnc_addPerFrameHandler;


```
Drops a fully configured weapon into a "WeaponHolderSimulated" at player's feet

**Comment by jonpas** [comment]
That does work but visually it looks a bit stupid, with sinulated weapon holder weapon sinks to the ground, with normal weapon holder it floats.

**Comment by mickeymen** [comment]
one one opinion...

This:
https://youtu.be/4-mrgDI95mY 
looks tolerable

 but when standing:
https://youtu.be/4hFZLaPjZHU 
looks very bad.

I don't even want to think how it would be for gameplay. For me it is important how it looks. And you know why? Because I want play in a realistic simulator, but not in Unreal/Doom/Quake. Today we have only one decent simulator, please do not clutter it.

@esteldunedain in your exmple you use absolutely not a suitable animation for this case. 
I mean, when the unit is standing. This falling animation(which in your example) was created durring movement. Why you trying to use it while unit standing?  If unit stands, then this is not acceptable. 

Unfortunately Arma3 and ACE together already have so many bad animations (super-fast falling of unconsciousness, jumpy hit reaction, fantastic jumping ragdoll and etc) 
Are you going to restock this list?
I really hope ACE team will not add additional bad animation. 
ACE team, please If no proper animations for new ideas, then better not invent anything new.

**Comment by vlad8011** [comment]
@mickeyman +1

**Comment by headedhorseman101** [comment]
>That's was a shot in the vest, hence little/no damage was taken and no hitreaction was triggered.

That brings up another issue. Should hits to a chest plate cause a reaction? When a bullet impacts an armor plate, an inelastic collision occurs that transfers the momentum to the vest and body as the bullet impacts. Since the bullet transfers nearly all of its momentum, logically the bullet would cause a reaction of some sort.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
