### ISSUE TITLE
fnc_addHeartRateAdjustment.sqf error when using morphine

### ISSUE THREAD

**Issue by MojoDog** [acemod/ACE3#3526]
Arma 3 Version: 1.56.134787
ACE3 Version: 3.5.0

Mods:
CBA
ACE
ALIVE

Description:
I get [THIS](http://i.imgur.com/Gt92kp1.jpg) when I apply morphine on myself in the Editor (Singleplayer).

Placed Modules:
ACE_ModuleMedicalSettings
ACE_ModuleBasicMedicalSettings
ACE_ModuleAdvancedMedicalSettings
ACE_ModuleAssignMedicRoles
ACE_Weather_ModuleSettings
ACE_Spectator_ModuleSettings
ACE_ModuleSitting
ACE_finger_ModuleSettings
ACE_ModuleNameTags
ACE_Map_gestures_ModuleSettings

**Comment by grester** [comment]
I know this has been closed but I'd like to point out that I'm not sure if this is indeed a bug or instead mod conflict. I say this because I have some simple missions where this error doesn't show up but I have some other missions with more scripts where the error does show up for all injections not just morphine. Just a headsup.
