### ISSUE TITLE
Carry body bag function added

### ISSUE THREAD

**Issue by RockyJRT** [acemod/ACE3#3550]
I am part of a realism group that would like to use the body bags that are implemented in Ace 3, the only issue is you can only drag them which is very slow and has caused us to not be able to use them for furthering our immersion. Would there be a possibility of you adding a carry body bag function in to Ace 3? 

Regards
RockyJRT

**Comment by jonpas** [comment]
I'd say no, carrying body bags doesn't happen in reality and it would also look stupid.

**Comment by headedhorseman101** [comment]
I agree with @jonpas because usually handling the dead is done by 2 people carrying the body bag or by the use of gurny (a wheeled stretcher, common in hospitals and ambulances). As we have neither of those currently in the game, carrying a body bag with a ~200 lbs. corpse in it is impractical at the moment.

**Comment by jonpas** [comment]
We have decided this will stay is is due to above mentioned reasons.

**Comment by PabstMirror** [comment]
If you wish to add this functionality to your mission, place the following in description.ext:
```
class Extended_Init_EventHandlers {
    class ACE_bodyBagObject {
        class weirdCarry {
            init = "[(_this select 0), true, [0,1,1], 90] call ace_dragging_fnc_setCarryable;";
        };
    };
};
```
You could also make this into a tiny mod to make it apply to every mission.

It looks bad, but should be functional.
