### ISSUE TITLE
FRIES doesn't work with the Wildcat

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#3577]
**Arma 3 Version:** `1.56.134787` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- FRIES don't work with the wildcat.

**Steps to reproduce:**
- place wildcat on map. in Attribute mark "equip with fries" preview the Mission. get in wildcat as passenger try to prepare the ropes. same result for both types of wildcat, as well as for both ways to equip fries (Attribute / Module)

**Where did the issue occur?**
- Editor (Singleplayer)**Placed Modules: FRIES-Module**
**RPT log file: http://pastebin.com/bWwNfpzt**

**Comment by BaerMitUmlaut** [comment]
1. The wildcat has no "Prepare FRIES" interaction. The model lacks animatable doors, nothing I can do about that. The FRIES itself is not animated either and is just a static gantry, nothing to prepare here.
2. You need to be 2m off the ground to deploy the ropes. Make sure you are, because I think that's the reason why you do not get an interaction menu entry.

**Comment by madpat3** [comment]
ah, i see. works as u described. 
thanks for your "customers Service" ;)

**Comment by madpat3** [comment]
i think you mixed up "gantry" with "gantryReverse" in v3.5.1
![20160320143316_1](https://cloud.githubusercontent.com/assets/15272840/13904790/50a08502-eeac-11e5-9d88-f8069bb50f19.jpg)
![Uploading 20160320143259_1.jpg…]()
