### ISSUE TITLE
ACe supply crates have quit working

### ISSUE THREAD

**Issue by dvdbrewster** [acemod/ACE3#3586]
There was no problem before 3.50 vers.  I think the classname for the supply crates must be different.
Could you send the classnames (full) for the supply crates: Ammo, Medical, Adv.Medical, Support. ?

Arma 3 Version:** `1.56` (stable )
CBA Version:** `2.3.1.16..` (stable / dev + commit hash)
ACE3 Version:** `3.5.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- ACE Supply Crates (all) have quit working..

**Steps to reproduce:**
- Launch mission that uses ace crates in a build menu.. try taking a loadout.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / 

**Placed Modules:**
- @ ace_server mod.  complete Otherwise all modules (steam workshop vers. beCTI sari-annabella Altis ACE

**RPT log file:**
- Only says destroying object.. when it has time to .(destroyin item by item, not destroying crate.

**Comment by esteldunedain** [comment]
> Launch mission that uses ace crates in a build menu.. try taking a loadout.

@dvdbrewster, I've told you already that's not an issue with ACE but with beCTI.

**Comment by dvdbrewster** [comment]
I donno  how you can say that,  the only thing different about this map is the last update, are you  sure the Boxes arent recoded or renamed etc.      Theres 200+ clasnames for everything on ACE website, not one of them is the complete box.. Who wants to list item per item to put in a box,  when there should be a class for the whole Box. ?

**Comment by esteldunedain** [comment]
@dvdbrewster: 

1- You [reported issues with the crates in beCTI before 3.5.0](https://github.com/acemod/ACE3/issues/3383), so the problem is clearly not related to the update.

2- None of the ACE classnames were changed in 3.5.0. We make a great effort to maintain backward compatibility whenever possible.

**Comment by dvdbrewster** [comment]
OK  thanks

**Comment by esteldunedain** [comment]
No problem, @dvdbrewster. I'd love to be able to fix the issue, but I don't know how beCTI works. I don't think ACE box classes are hard coded, so they should work even if we've renamed them. 

The problem is most probably related to the many errors beCTI throws, according to the last RPT you sent.

Sorry, I don't think we can do anything to solve it.

**Comment by dvdbrewster** [comment]
OK THX. That particular mission has a reconfigured Recon class, everything 
loading to those units gets errored, 
but is resolved in milliseconds LOL
funny how it broke any personal/private
Items.
