### ISSUE TITLE
AB - AtragMX : "done" problem

### ISSUE THREAD

**Issue by J3aLeiNe** [acemod/ACE3#3607]
**Arma 3 Version:** `1.56` (stable)
**CBA Version:** `2.3.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- To obtain a final and stable elevation in the AtragMX, it's necessary to press a few times (2 or 3 times) the "done" button, especially for the "Gun" column.

**Steps to reproduce:**
- AB enabled (no tested with the default ballistic), open the AtragMX, open the "Gun list" and take the .408 CT for example. 
  Enter a target range : 1600 meter for ex. 
  Open the "Gun" column and change the "Bore" or/and the "Muzzle Velocity" or/and the C1 Coefficient, for ex. 
  - Press "Done" and check the elevation (Mils). 
  - Reopen "Gun" and press "Done" without change, check the elevation, it won't be the same.
  - Re-reopen "Gun" and press "Done" without change, check the elevation.
  - Repeat one more time this operation and it will be the good and stable elevation's value.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Advanced Ballistics manually enabled.

**RPT log file:**
- Not sure it's necessary but if you need it, tell me.

**Comment by Andrees97** [comment]
This is still a thing, although I find usually its small differences (0.5 mil aprox) I think something is wrong with AtragMX calculations (only regarding elevation). Almost all weapons tend to hit very low at close distances and too high at long distances, even when taking all factors into consideration. I think it may be something to do with the BCs too, ACE configs show 0.234BC for RHS M118LR and either ATRAG doesn't work well or this isn't the BC.
Yes I'm using custom profiles.
Yes AB is activated.

Also, regarding custom profiles. When using default .300WM Mk248 Mod. 0 (or Mod. 1) calculation gives a certain result in elevation correction, but when using a custom profile (Add new gun) with exact same data, the elevation correction is completely different.

**Comment by ulteq** [comment]
The problem is that the AtragMX only supports G1 ballistic coefficients.

The ballistic coefficients we use to simulate the [`Mk248 Mod. 0`](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L341) and [`Mk248 Mod. 0`](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L357) are G7 BCs.

You have to look up the G1 BC if you want to add custom profiles for such ammo types.

> When using default .300WM Mk248 Mod. 0 (or Mod. 1) calculation gives a certain result in elevation correction

Some of the default profiles actually use G7 BCs to improve the accuracy of the ballistic solution.
This is meant to be a temporary workaround until someone implements the `C1/distance interpolation table` (page 22 in the [official manual](https://github.com/acemod/ACE3/blob/master/extras/manual_Horus_ATrag-v385.pdf)).
