### ISSUE TITLE
AI hovers too high for safe fast roping

### ISSUE THREAD

**Issue by olivier28** [acemod/ACE3#3639]
**Arma 3 Version:** Game version: `1.59.135137` (dev)
**CBA Version:** `v2.3.1.160220` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When i use the fast rope near an object or in the city,it's too short
You can see that here: [https://youtu.be/hwyP6xgOFyw](url)

**Comment by kripto202** [comment]
I don't think it is the rope, I think it is the ai itself, I think they have a set of minimum altitude that they can hover, did you check how high the heli was hovering above the city and the terrain?

**Comment by BaerMitUmlaut** [comment]
Yes it's the heli hovering too high. The command used for the hover distance is a bit unreliable it seems, I'll see if I can fix it.

**Comment by kripto202** [comment]
one way this could easily be fixed is to extend the rope till the rope hits the ground or allow us add different type of ropes like 20m, 50m, or 100m. Another is an option to extend the rope some more like the advanced sling loading system.

**Comment by BaerMitUmlaut** [comment]
Different rope lengths are planned (see #3475), but not for a hacky bugfix. I'd rather fix the underlying error :wink:

**Comment by olivier28** [comment]
the helicopter is between 50 and 55 meters in height


2016-03-30 16:08 GMT+02:00 kripto202 <notifications@github.com>:

**Comment by madpat3** [comment]
i think 40 is maximum

**Comment by commy2** [comment]
Please someone rename this ticket. The title "Bug with X module" triggers me.

**Comment by jonpas** [comment]
Just for you @commy2 :banana:

**Comment by olivier28** [comment]
Thanks for all the rapidly response

**Comment by BaerMitUmlaut** [comment]
I did some testing: The AI does not react to the fly in height commands appropriately above buildings for heights between ~60m and 10m, so this is not fixable unfortunately.

**Comment by Knight1981** [comment]
In the SHK_Fastrope script you can easily define the rope length. Isn't it possible with ACE?

We also have the problem that the AI is hovering too high for fast roping so a config in the ACE Settings with the rope length would be really helpful for us!

`  // Create ropes
  _ropesObj = [];
  {
    _rope = ropeCreate [_heli, _x, ROPE_LENGTH];
    _ropesObj pushBack _rope;
  } forEach _ropesPos;`

**Comment by BaerMitUmlaut** [comment]
There are no 70m long fastroping ropes. Actually the rope length we currently have is one of the longer ones. 70m would look ridiculous.

**Comment by Nukedrabbit95** [comment]
I have no idea if anyone still cares about this or is working on this mod, and I have even less of an idea why this was marked as closed. The AI's ability to use fast rope is so completely and fundamentally broken that it might as well not even be a feature. 

I have literally _never_ managed to get an AI pilot to drop troops on a fast rope without injuring or killing those being dropped, outside of perfect flat open terrain such as VR or airports. Even in flawless conditions, it can still not be managed 100% of the time.

Is there/was there ever any plan to provide a workaround? It would be nice to know so I can stop wasting my time trying to get this broken non-feature to work.

**Comment by BaerMitUmlaut** [comment]
Hello @Nukedrabbit95! Lovely introduction you made there, always great to get such constructive feedback from our users!

To answer your questions:
- Yes, there are still a lot of people working on this mod. I suppose you don't update your mods that often, otherwise you would have noticed that.
- If you take a look at the labels of this issue, you should notice the "fault/BI" one. That means, this is an underlying engine issue, caused by BI, not by us. That also means that we can't fix it, because we don't have access to the engine source code. Since we often can't do anything in such cases, we close these issues.
- Contrary to your belief, this feature is not fundamentally broken. It actually works quite well when the AI finds a good spot. It might surprise you, but this even works in the center of a town if you set the waypoint just right.  
![20180327185403_1](https://user-images.githubusercontent.com/9693842/37982822-ed7162f4-31f1-11e8-98f6-9399933658ea.jpg)
- If you have a good workaround, we'd love to see your pull request. If you need any help with working with git/Github, feel free to join our Slack and I'd be happy to help you there.

Finally, feel free to submit an issue to the BI feedback tracker, send them a letter requesting to improve this, hack the engine yourself or apply for a job at BI to fix this problem. All of these options might help solve this issue in future, unlike your comment here.

**Comment by EvilItalianK** [comment]
Apparently it's not a fault but how flyinheight is designed to work: https://feedback.bistudio.com/T82970#2076506

I'm not totally sold on it but if it it's true, we would need 50m ropes

**Comment by BaerMitUmlaut** [comment]
@dedmen's answer is not 100% correct. There is a certain range in which helos do not respond to the command. They do react to super low ranges below 10m iirc - that's just not usable for us.

However, this doesn't change who's at fault here: If BI doesn't change how the command works, we cannot do anything about this.

**Comment by EvilItalianK** [comment]
> @dedmen's answer is not 100% correct. There is a certain range in which helos do not respond to the command. They do react to super low ranges below 10m iirc - that's just not usable for us.
> 
> However, this doesn't change who's at fault here: If BI doesn't change how the command works, we cannot do anything about this.

I do agree that it's a lacking of the engine, but neverthless until it's expanded/fixed we should think about expanding the rope to 50m, which would be better (albeit not much realistic) than having people roping to a certain point and then fall for the next meters.

Until BI makes the improvement, we should make the fastrope safe for the users and if that means that the rope must be a little bit longer than what is actually used IRL, I'm totally for it until BI improve the command.

**Comment by BaerMitUmlaut** [comment]
You can still use it, you just have to find places that don't have buildings or simply use player controlled pilots. I'm sure you could also get it to work with unit capture or something similar. There's this one specific use case where it doesn't work and I don't want to include a hacky solution to an already hacky system.

**Comment by EvilItalianK** [comment]
Having a longer rope is not a hacky solution though, it's just a bit less realistic, maybe it can be used only if the pilot is an AI and the height isn't being accepted at 30m?
I agree that it's BI fault but since we are developing on top of it we should either work with what they provide us or don't bundle the feature, having a feature that is not reliable can be a worse thing than not having it, and i don't think the workaround is so drastic (some meters more of rope only if the pilot is a bot) to not include it

**Comment by dedmen** [comment]
> answer is not 100% correct.

That is the "specification" of that command, just that is guaranteed and nothing else.
It cannot be fixed by changing the command implementation, it depends on the vehicles simulation type, and there are a few different ones that behave differently.

**Comment by EvilItalianK** [comment]
@dedmen Thank you for the clarification, do you think we can file an improvement request to have a way to fine control the altitude? I'm not sure how it's handled by the engine but i would be pretty surprised if there's no way to have it

**Comment by dedmen** [comment]
> do you think we can file an improvement request to have a way to fine control the altitude? 

no, I looked at it, won't be improving that.
