### ISSUE TITLE
Complete event list on wiki

### ISSUE THREAD

**Issue by Glowbal** [acemod/ACE3#385]
http://koffeinflummi.github.io/ACE3/wiki/dev/ace3-events-system.html

The event list is incomplete. All events currently in use should be added to that list.

**Comment by alexcroox** [comment]
+1 would find this very useful

**Comment by jonpas** [comment]
How should they be sorted, by event name or source(s)? Also how is locality determined? And what are callable events?

**Comment by SilentSpike** [comment]
Locality is determined by the way they're called (local, target, server).

Callable events are events that can be called to trigger certain code. For example captives has the `SetHandcuffed` event which can be called.

**Comment by bux578** [comment]
Status? Are we somewhat complete?

**Comment by jonpas** [comment]
I don't think anyone added any yet, I also forgot about it.

**Comment by SilentSpike** [comment]
I'll do a quick sweep in a couple minutes here :smile:

**Comment by Crazy538** [comment]
Any news on this guys? It would be a shame for features you've worked on to go unused because of this.

**Comment by jonpas** [comment]
I will work on that tomorrow. With @alganthe 's current framework documentation plan we will document events per-module (as was decided for configs and public functions).

Another idea that came up with that (since above would make it quite spread-around), was the following:
> another thing I just remembered we could do, or better said bux could do
if a standard is set for configs, public functions and events doc in respective framework docs
there could  be a page setup that would form tables/lists
out of those pages
so you have both per-module and combined pages

I will talk with @alganthe and @bux578 about that, either way you should soon see all events documented. :banana:

**Comment by jonpas** [comment]
Just a small update, events are starting to get documented in #2177
