### ISSUE TITLE
Improve the mil turrets on high power scopes

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#393]
I would like to suggest a few changes:

1. Change the default zero range to 100m (it is currently set to 1m)
2. Allow both minor (0.1 Mil) and major (1.0 Mil) increments/decrements
3. Allow a fast rotation of the adjustment knobs by pressing and holding the the adjustment buttons.

(Optional) 4. Allow to persistently change the zero adjustment of high power scopes (save the zero reference in the profileNamespace)

**Comment by da12thMonkey** [comment]
One other drawback with setting the zero to 1m is that some scopes created with realistic click values cannot be zeroed high enough to reach a realistic maximum engagement range on some weapons.

The [Nightforce 5.5-33x56 NXS] (http://nightforceoptics.com/military/nxs/5-5-22x56-nxs-riflescope/) that the game's LRPS is based on, realistically only has an elevation turret adjustment range of +27.3Mils from the zero position (The elevation turret has travel for 5 complete turns of 20MOA per turn = 100MOA or 27.3Mils), rather than +/- 70Mils (140Mils total) it currently has in ACE. So if you set the click values to a realistic limit, weapons fitted with the scope would have a much shorter range than they are currently capable of being zeroed to.

If the aim is to have a display of Mils in the Adjustment UI rather than clicks relative to a weapon/optic zero, it'd be useful to be able to set the minimum ACE_ScopeAdjust_Vertical[] value to be greater than 0 so that we can still set realistic click ranges and have them achieve realistic shooting ranges without setting the discreteDistance[] value to >1. Currently the script/UI doesn't work if you set both values to be +ve.

Fact is, many long-range rifles have an inbuilt cant on the optics rail; such as AI's AW/AX rifles that have an option for [20MOA or 30MOA sight rails] (http://www.accuracyinternational.com/assets/assets/ax338_brochure.pdf) (pg.2, cap.12), Badger Ordnance also make [20MOA] (https://www.badgerordnance.com/products/scope-rail-sako-trg-2242-20-moa-cant-3/) and [35MOA] (https://www.badgerordnance.com/products/scope-rail-sako-trg-2242-35-moa-cant-3/) rails for the Sako TRG 22/42. Or the scope-rings/sight-base has an inbuilt cant instead; AI provides additional [18MOA, 28MOA and even 45MOA] (http://www.accuracyinternational.com/assets/assets/accessories_brochure.pdf) scope mounts for its rifles (pg.3). And that's before the shooter even sets the scope's elevation zero to however many meters they wish to zero the scope to.

So it's very rare that a click value of 0 actually corresponds to an elevation of 0 Mils like it does in ACE, and it's often necessary for there to be some baseline elevation in the weapon system to shoot at longer ranges within the limited click adjustments available on their scope's elevation turret travel.

So I think it'd be wise to be able to configure the minimum ACE_ScopeAdjust_Vertical[] to be grater than 0 (i.e. both values can be +ve), or apply some range to the base discreteDistance[], so that there's some capacity for applying realistic click boundaries on weapon scopes. Generally, scopes don't have -ve clicks below their zero at all anyway, and if they do it's only a few mils. Adjusting to -ve Mils in the current system seem rather redundant when the zero is set to 1m - all you end up doing is shooting the ground.

**Comment by ulteq** [comment]
For reference: https://github.com/acemod/ACE3/pull/449

**Comment by ulteq** [comment]
@da12thMonkey, I absolutely agree on what you're saying. Please test the new scope adjustment module and let us know what you think about it. Feel free to create a new issue if you see necessity.
