### ISSUE TITLE
Enabling Mine Detector lags game

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#4049]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.0` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Using the Mine Detector lags the game if multiple objects close by

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- N/A atm

**Comment by esteldunedain** [comment]
Looking at the code, I think the problem is on `FUNC(getDetectedObject)`, called from in `FUNC(detectorLoop)`. There's various easy to implemenent optimizations that occur to me:

- Call the detector loop func every 0.1 sec instead of 0.01 sec (which is practically every frame). Maybe slightly increase range to compensate
- The kind of objects that are detectable could be stored as variables in a namespace to avoid fetching configs for each detected object.
- The detector loop should exitWith on the first detected object. I think that was the intention, but the exitWith is inside another code block, so the function doesn't exit properly until it iterates over all nearby objects.

**Comment by Glowbal** [comment]
We can make use of our cache function for quick gain

**Comment by esteldunedain** [comment]
@PabstMirror, @Glowbal, quick question; the fix should target the Apex branch, right?

**Comment by PabstMirror** [comment]
@esteldunedain yeah

**Comment by bux578** [comment]
fixed with #4052

**Comment by Glowbal** [comment]
Fixed by #4052

**Comment by jonpas** [comment]
Good job guys!
