### ISSUE TITLE
Issue: Make tools accessible through keybindings

### ISSUE THREAD

**Issue by ulteq** [acemod/ACE3#426]
Tools like the ATragMX, Kestrel4500 and microDagr should be easy and quick to reach. Always having to go through the interaction menu is a pain.

**Comment by commy2** [comment]
Note that in ACE2, Kestrel, HuntIR, DAGR etc. where all accessable by shortcuts too. Only the HuntIR had a menu option to open it additionally to that.

**Comment by esteldunedain** [comment]
I don't think so. Using the interact menu takes 1~2 sec, same or less than IRL. There are already too many keybinds on the armaverse.

Alternatives:

1- Create the keybind, but don't bind it by default. Please who heavily use this devices could then bind them if they choose too. I'm not sure if this's possible with CBA.

2- Create the concept of "selected" or "prepped" device. You 'd select one device from the interact menu to be "selected".  Then the Home keybind would display/hide it. If you then want to use a second device later, you can either use the interact menu as it is, or "select" it.

BTW, only one device should be displayed at any one time.

**Comment by ulteq** [comment]
I like both ideas very well.

**Comment by jaynus** [comment]
I'm not fond of adding more keybinds, the interact menu is quick enough to not need them. Part of our work effort has been eliminating erroneous keybinds with the interaction system so people are not memorizing 50 less-used keys. 

Fluidly knowing you can access your interact and find it is much more immersive than having to escape out and check your key binds constantly because you barely ever use that feature. 

This is irregardless of realism etc - from a usability stand point, its more intuitive and immersive to guarantee users a in-game method of finding and doing things.

**Comment by ulteq** [comment]
I'm convinced.
