### ISSUE TITLE
ACE3 Medical hard-intergrated; not "Module-based"

### ISSUE THREAD

**Issue by NikolaiGman** [acemod/ACE3#4309]
**Arma 3 Version:** `1.62.137494` stable
**CBA Version:** `3.0.160713` stable
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Hi all,
I'm integrating ACE into the missions my group plays. We're a bit late to the party.
The issue I've encountered is the ACE Medical System overwriting BIS's medical system, even without any of the related ACE modules being placed.
This could be a non-issue if I've missed something obvious. In that event, how would I go about disabling ACE Medical so we can continue to utilise BIS-standard reviving?

I've already attempted working around this by removing the medical pbo's, but then that also removes the interact function with player bodies, resulting in the inability to carry and drag downed friendlies to safety, loading, everything effectively. We've turned to ACE for it's incredible amount of functions and the hopes of consolidating the horrible mess of scripts we've been using.

Fingers' crossed and thank you for all the hard work you've done with ACE.

-Nikolai

**Where did the issue occur?**
- Self-Hosted Multiplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None

**Comment by jonpas** [comment]
There really is no other way of removing it, due to the config changes which can't be changed once the game is running.

@Glowbal Your medical separation into multiple components might be perfect for this, put interactions for loading, dragging, carrying of bodies in a separate component that doesn't require other medical components?

**Comment by commy2** [comment]
dragging (incl. carrying) already is in it's own component, but since the units aren't "ace unconscious" when they are incapacitated (vanilla revive), you cannot use the functionality.
I'm not sure if dragging is possbile with the incapacitated state. Depends on whether the game considers them to be ragdolled or not.
You'd have to edit the vanilla revive system to include a dragging / carrying functionality. Both systems are two different, and dragging is too huge a pain to set up correctly (the scripting) to have this simply be a module that you can plug into any old medic system.
