### ISSUE TITLE
ACE 3 Breaks AI's Ability to Aim (No Matter the Difficulty Settings)

### ISSUE THREAD

**Issue by Shadow6066** [acemod/ACE3#4326]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** Steam Workshop
**ACE3 Version:** Steam Workshop

**Mods:**
- @CBA_A3
- @ace

**Description:**
- After some testing, it seems Ace causes the AI to lose their ability to aim at ranges past 50m. I have provided a short video highlighting the bug:
  [https://www.youtube.com/watch?v=RzH4iEs_OdQ](https://www.youtube.com/watch?v=RzH4iEs_OdQ)

Please make the AI tweaks a separate module or at least allow us to adjust the AI somehow. I love ACE but it's making my group's missions way too easy.

**Steps to reproduce:**
- Launch Arma 3 with ACE, place unit of each side down in editor (50m or more apart), play as one of them, watch as the other fails to hit you.

**Where did the issue occur?**
- Always

**Placed Modules:**
- None.

**Comment by commy2** [comment]
It already is a seperate mod. Remove ace_ai.pbo and weapons ai should be like vanilla.

**Comment by Shadow6066** [comment]
Thank you very much, I really wish this was made more clear. Maybe an option in game to disable it under the ACE options menu? :)

**Comment by esteldunedain** [comment]
> Maybe an option in game to disable it under the ACE options menu

Sorry, that's not possible due to how this changes work.

**Comment by esteldunedain** [comment]
@commy2, the video provided by @Shadow6066 does show very poor results from the tweaks in AI. Should we scrap them, or at least adjust them?

**Comment by Shadow6066** [comment]
Thanks for watching it, while it does make for some epic sounding firefights once you get involved it gets awkward. I've had too many missions where I said "I shouldn't be alive right now" which was great at first but after so many times the exhilarating moments turned to eye rolls. I feel like you guys had the right idea though and I'm interested to see where this goes.

**Comment by brndd** [comment]
I also tested this and didn't spot the same issue: https://www.youtube.com/watch?v=4ON7iX4TlYw

**Comment by jonpas** [comment]
@Shadow6066 can you check the Skill slider and other AI options that might influence it? @brndd really does show the opposite of what you are experiencing.

**Comment by Shadow6066** [comment]
Skill slider is at default 50% where it should be, same with vanilla but notice how bad the difference is.

**Comment by commy2** [comment]
>@commy2, the video provided by @Shadow6066 does show very poor results from the tweaks in AI. Should we scrap them, or at least adjust them?

That's what I keep saying. These changes are from 2014 (TMR mod, even before AGM). Many things have changes since then and this is probably overcompensating in a lot of places.

**Comment by commy2** [comment]
@Shadow6066 please  upload a RPT file of the session you experienced this behaviour. Thanks.

**Comment by esteldunedain** [comment]
I suggest moving ace_ai to optionals for 3.7, until someone can take a deeper look.

**Comment by commy2** [comment]
One difference I can see in the videos is, that the AI with ACE is firing bursts in the full auto mode, while it's rapid firing in semi mode in vanilla.
The reason for this is, that the AI curves for selecting a fire mode are bugged in Arma 3. Instead of using the distance to target to determine the weighted probability of all available AI fire modes like in Arma 2, it will always select the mode with the highest probability and stick with it untill you leave the minimum or maximum range for that mode (in which case the next mode with the highest probability is chosen).
Due to the way the vanilla modes are set up, no rifle will ever use anything else than the default semi auto mode (the one the player has access to, some modes are AI only).
I have no idea why BI keeps making the configs for the AI modes (even for Tanoa weapons), because the way they set up the values, the AI will never use them anyway. I attribute this to a lack of understanding what the values do (sorry if any of them are reading this).

What ACE AI does is changing the probability tables so AI will use other modes too. In this case AI selected full auto mode, because you where so close, while this expected behaviour is broken in vanilla.

Additionally note that the delay between single shots will decrease linearly with the closeness to the target, which means that AI wil actually fire faster than the weapons ROF if you get really close in vanilla (depends on the weapon ofc.) This mimics full auto mode (expect the ROF is off of what you'd expect)

From this and memory I can tell that the distance here is below 30 meters.

**Comment by esteldunedain** [comment]
Do different fire mode have different accuracy or dispersion? That could explain why the AI has more trouble hitting the player in full vs semi auto.

Bottom line, if we tweak the AI to use full auto on close quarter it's because it should be better for them (more likely to kill). Apparently that's not the case.

**Comment by brndd** [comment]
It's possible there is some particular range where AI will swap to full auto, but will be too inaccurate with it to hit anything. However, having played a good hundred hours with ace_ai enabled I can attest that the AI does not become completely unable to hit anything with it.

Perhaps the distance the AI will use continuous full auto at should be tweaked, but aside from that I can not notice anything glaringly wrong with the current settings. They are a vast improvement over the default AI.

**Comment by commy2** [comment]
>Do different fire mode have different accuracy or dispersion? That could explain why the AI has more trouble hitting the player in full vs semi auto.

On normal weapons, all weapon modes have the same dispersion. This is because the weapons dispersion is measured relatively to the barrel, so dispersion shouldn't be used to simulate sway.

The AIs dispersion is done via the `aiDispersionCoefX` and `aiDispersionCoefY` entries, which are not influenced by the fire mode, but are tweaked in ACE AI too.

Sure you could change these values again, but just look at @Shadow6066 and @brndd .
Both show videos of the exact same thing and if you keep in mind that Shadow was constantly moving, while brndd was just standing still, you can see that the AI reacted consistent on both tests.
It all comes down to preference and gut feeling.
Take the last test of Shadow for example, where he simulated what a player would do in the place of the AI. I couldn't react that fast, unless I knew an enemy would be coming from that direction.

You cannot make an AI react the same way as people. It's simply impossible, especially if you know about the puny possiblities we modders have. It's ridiculous.

**Comment by commy2** [comment]
Lastly, what I realized by working on different things in the last week is, that the way Arma handles weapon AI, it might be considered impossible for us ACE people to do anything on it.
Every weapon has it's own brain. Fixing the vanilla ones, makes them behave differently than the RHS or CUP ones, which are probably balanced (copy pasted) on the vanilla ones. Sure we could make compat PBOs and tweak every weapon, but with the config inheritance in Arma this is a huge pain. No one even bothered to do the Tanoa weapons yet!

Due to the subjective nature of AI behaviour - sadly - what you now got is people getting angry at each other. This isn't what I want to put my time into to be honest.

**Comment by esteldunedain** [comment]
Ok, hold on. The discussion above only covers the changes to fire modes. I think we can agree we may want to keep them

But ACE_AI also changes `CfgAISkill`:

```c++
class CfgAISkill {
    aimingAccuracy[] = {0,0, 1,0.8};  // {0,0,1,1};   v1.26 defaults
    aimingShake[]    = {0,0, 1,0.6};  // {0,0,1,1};
    aimingSpeed[]    = {0,0, 1,0.7};  // {0,0.5,1,1};
    commanding[]     = {0,0, 1,0.8};  // {0,0,1,1};
    courage[]        = {0,0, 1,0.7};  // {0,0,1,1};
    endurance[]      = {0,0, 1,0.7};  // {0,0,1,1};
    general[]        = {0,0, 1,0.9};  // {0,0,1,1};
    // apparently breaks rapid firing in single fire mode for players
    //reloadSpeed[]    = {0,0, 1,0.8};  // {0,0,1,1};
    spotDistance[]   = {0,0, 1,0.9};  // {0,0.2,1,0.4};
    spotTime[]       = {0,0, 1,0.7};  // {0,0,1,0.7};
};
```

In particular it significantly reduces the aiming accuracy and the aiming shake. Most likely those are the changes that negatively affect the AI aim.

**Comment by commy2** [comment]
This contributes too, but the main reason is `aiDispersionCoefX` and `aiDispersionCoefY`

This CfgAISkill thing also conflicts with any AI mod which tweaks these values, be it via config or the SQF commands.

**Comment by esteldunedain** [comment]
What about scraping the CfgAISkill and the dispersion coeficients, and possibly leaving the fire mode tweaks as they are? AI would become a bit more letal by default, but people can tune that down using the skill slider if they want.

**Comment by commy2** [comment]
But then we remove a feature. @brndd seemed happy about our AI tweaks.

**Comment by commy2** [comment]
Oh and another note. Another reason the player seemed more durable during the ACE tests, is that he is. This is partly due to the medic system which does this on purpose, but the way it's currently using the handle damage event handler (our "caching" system) it might or might not register two hits coming in quick succession, which means that full auto mode does less damage than expected.

**Comment by esteldunedain** [comment]
> Every weapon has it's own brain. Fixing the vanilla ones, makes them behave differently than the RHS or CUP ones, which are probably balanced (copy pasted) on the vanilla ones. Sure we could make compat PBOs and tweak every weapon, but with the config inheritance in Arma this is a huge pain. No one even bothered to do the Tanoa weapons yet!

> Due to the subjective nature of AI behaviour - sadly - what you now got is people getting angry at each other. This isn't what I want to put my time into to be honest.

I think those are pretty strong reasons to just revert to vanilla, and let BIS or dedicated AI mods deal with this.

**Comment by commy2** [comment]
Also, this whole mess is just so difficult to communicate to the end users. For them there is "Vanilla AI", "ACE AI", "ASR AI". But if you know the configs, you know that that is not how it works. At all.

**Comment by brndd** [comment]
My 2 cents on the matter are that there's a distinct lack of functional,
up-to-date AI tweaks that make small adjustments to the AI such as these.
Mods like ASR are not what many users want, as they're often fairly heavy
and due to technical limitations have to result to very... unorthodox
solutions (eg. to improve driving ASR spawns dozens of invisible objects
that the AI tries to evade, IIRC).

There's a certain need for tweaks such as the ones ACE's AI module adds,
and it goes well together with the overall intent and spirit of ACE, so I
think it should be kept in until BIS manages to make these fixes
themselves. There's always room for improvement, but even in its current
form I feel it's a great help when it comes to reducing the frustrating
aspects of the AI without bringing in any massive changes that have good
potential to ruin mission balance.

**Comment by esteldunedain** [comment]
> There's a certain need for tweaks such as the ones ACE's AI module adds, and it goes well together with the overall intent and spirit of ACE, so I think it should be kept in until BIS manages to make these fixes themselves.

That's a fair argument too.

**Comment by alganthe** [comment]
On my end running on 1.64 RC and ACE3 3.7.0 RC1 the AI seem to be as accurate as the vanilla counterpart, fights tend to last longer due to medical but their accuracy is still pretty high (I'm using custom AI values)

Also please remember that the difficulty you're running affect AI aiming as well

**Comment by bux578** [comment]
@alganthe are you able to reproduce the same behavior as in @Shadow6066's dramatic titled video? (https://www.youtube.com/watch?v=RzH4iEs_OdQ)

**Comment by alganthe** [comment]
Yes, with vanilla and no mods by lowering the skill of the AI via the difficulty settings or via scripting commands.
On my tests the AI could accurately shoot me when moving (forcing me to fall on my side) at around 150m

**Comment by Shadow6066** [comment]
I will make a test video again, with different ranges. I'm using the default difficulty of spawned editor units, In the video I made there were no adjustments to the AI's skill level other than "expert" in the options menu. On that difficulty 50% is more than accurate enough but for some reason it just doesn't seem to work with ACE.

Also I'll figure out that RPT file.

**Comment by Shadow6066** [comment]
Alright so after so many responses saying it's on my end I decided to make sure it wasn't, I completely reinstalled ACE 3 but from Armaholic instead of steam workshop and I can say the AI are accurately putting fire on me from different ranges. Is something different on the steam workshop version? Can someone else look into that and make sure I'm not crazy?

**Comment by commy2** [comment]
The version on steam is the same as the one on github

**Comment by Shadow6066** [comment]
Well after reinstalling ACE completely it seemed to be fixed, something must have been wrong with my ACE folder. My apologies. :L

**Comment by crowmium** [comment]
It seems this issue has been resolved, but I just wanted to respond in case any ACE devs were still considering this topic. 

I spent about 12 hours making a training mission last week and I spent a large percentage of that time tweaking the AI skill values for my mission so it would be appropriate for training purposes. I spawned in and ran at an enemy emplacement at least two dozen times. I alternated between taking cover, attempting to suppress the enemy, running/standing in the open, etc.  I tested the gamut from 20% to 100% AI skill in 10% increments.

After all that, I can definitively say that the AI in ACE3 has a skill range of absolutely pants-on-head retarded to superhuman robot killers. Pretty much whatever skill you want them to be at, they can do that right now in ACE3. Tweaks might be interesting, but removing/rewriting the system is unnecessary. I'm happy with a lot of the improvements in the AI right now. They aren't perfect, but I think that's something BIS has to fix. I'm not sure how much more we can do with mods. FWIW.

**Comment by Shadow6066** [comment]
Hey, I recently launched ACE 3 again after using vanilla for a long time and as soon as I made contact I was reminded of this thread. Looks like I'll need to remove the AI changes from my .pbo because the AI literally cannot hit me for the life of them. The AI are aiming fine on vanilla and going from a vanilla mission to ace on the same mission was really disappointing.. I went from feeling the pressure to laughing as the AI missed my stationary body leaning out of cover for them. I'm not really sure why I seem to be the only one with these issues but my difficulty options are set pretty high: 0.8 skill 0.7 precision. Is ACE overriding my difficulty settings or something?

**Comment by commy2** [comment]
It's modifying the AI skill and the file hasn't been updated in about 2 years.
https://github.com/acemod/ACE3/blob/master/addons/ai/CfgAISkill.hpp

The additional dispersion for some weapons when used by AI has since been removed though. See #4484

**Comment by PabstMirror** [comment]
I believe https://github.com/acemod/ACE3/pull/5091 will have fixed this.
AI accuracy should be just like vanilla now (more deadly if you are used to prior ace version)

We still make some changes to weapons but I believe those are good and shouldn't have the effect on accuracy as seen in the video.

Let us know if this still an issue after 3.10 is released
