### ISSUE TITLE
[REQUEST] Add Damage Indicator for Wheels and some ideas

### ISSUE THREAD

**Issue by mihal190** [acemod/ACE3#4333]
**Arma 3 Version:** `1.62` stable
**CBA Version:** `Latest` stable
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
I and many people gets angry when see indicator in vehicle (Damaged Wheel Orange) after a fight we dont know how to chceck what wheels are still usable, idea is to add interaction "Check Wheel" and it will say its damaged, or without air in it (or something) next idea is for my unit, we will probalby Delte All HUD when 3.7.0, left only from ace, is it possible to add indicator to see what Fire Mode i have? that Custom UI sometimes get buggy with host so it will be very helpful ("Changed to Auto" or "Changed to Single")

**Comment by jonpas** [comment]
Thank you for your request, but this is a feature request. Please move it to the appropriate issue outlined in this guideline: http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

I do like the idea though, could make it the same as medical.

> that Custom UI sometimes get buggy with host so it will be very helpful ("Changed to Auto" or "Changed to Single")

We might be able to fix it if we would know about it and have some more information. We won't be adding another UI just because one is currently bugged (for you at least as I haven't heard anyone experiencing the same).

**Comment by PabstMirror** [comment]
So change the interaction icon's color just like medical (white/yellow/red)?

**Comment by jonpas** [comment]
Yes. At least for wheels/tracks as there is no other indicator for it, but might as well do it for all sections. After-all it's not like you couldn't see what's damaged IRL.

**Comment by PabstMirror** [comment]
Fixed by both #4450 and #4448
