### ISSUE TITLE
Error when advanced wounds get created

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#4343]
**Arma 3 Version:** `1.64` RC
**CBA Version:** `3.0.0` stable
**ACE3 Version:** `3.7.0` release branch; commit: be8b4468afcdf3b401f57cd294f7e66fbd50dbc2

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- An error pops up when damage is applied to a unit

**Steps to reproduce:**
- Reproduction mission: https://github.com/alganthe/ganthe_ACE3medical_vr

**Where did the issue occur?**
- SP / self hosted MP

**Placed Modules:**
- Medical settings / advanced medical settings (see the repro mission for the settings)

**RPT log file:**
- https://gist.github.com/alganthe/5837d21a25239f0f6af0f765d0e59b45

**Comment by commy2** [comment]
```
21:23:43 "ACE3 ERROR - Medical Extension: Something went wrong. Input: "
21:23:43 "   arg 0:hand_l"
21:23:43 "   arg 1:any"
21:23:43 "   arg 2:grenade"
21:23:43 "   arg 3:1"
21:23:43 "Exception: invalid stod argument"
```
no idea how the extension works

```
21:23:43 Error in expression <hitBody", _torsoDamage min 0.95];
_unit setHitPointDamage ["hitHands", (_handsDa>
21:23:43   Error position: <setHitPointDamage ["hitHands", (_handsDa>
21:23:43   Error Type Number,Not a Number, expected Number
21:23:43 File z\ace\addons\medical\functions\fnc_handleDamage_advancedSetDamage.sqf, line 16
```

https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_handleDamage_advancedSetDamage.sqf#L27

`_unit setHitPointDamage ["hitHands", (_handsDamageR + _handsDamageL) min 0.95];`

`_handsDamageR` or `_handsDamageL` is NaN type. Math error somewhere? Probably a follow up due to the extension erroring out.

**Comment by Glowbal** [comment]
#4344
