### ISSUE TITLE
Tripmine flares, chemlight shield, spare barrel: are not appearing in arsenal

### ISSUE THREAD

**Issue by KarlMoebius** [acemod/ACE3#4396]
**Arma 3 Version:** `1.62` (stable)
**CBA Version:** `3.0.0` (stable)
**ACE3 Version:** `3.7.0` (stable)

Mods:
- `@CBA_A3` (steam)
- `@ace` (steam)

**Description:**
- Mentioned in the update log: addition of tripmine flares, and the chemlight shield.

Problem: 
- Tripmine flares is not in arsenal or zeus spawn equipment box.  
- Chemlight shield is not in arsenal, only via Zeus via direct zeus span, or a zeus spawned ACE3 equipment box.
- Spare barrels is not in arsenal, only via a zeus spawned ACE3 equipment box.

**Steps to reproduce:**
Load mods
Enter editor
Spawn ARMA3 autorifleman, edit load out.
    or
place arsenal box, edit load out.

**Where did the issue occur?**
Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**RPT log file:**
http://pastebin.com/p2sMVLg8

**Comment by Meiestrix** [comment]
Same problem for the vehicle keys, but this is not new with this update.

**Comment by alganthe** [comment]
They will appear properly in 1.64.

**Comment by KarlMoebius** [comment]
If I may ask, what's the missing command or glitch that 1.62 has that 1.64 fixes (in regards to this)?

**Comment by commy2** [comment]
Arsenal doesn't show CfgMagazine entries that don't belong to any weapon you have currently equipped. Spare barrels are magazines internally, because that is the only way to distinguish individual spare barrels (and their temperatures, other properties).
Since 1.63 dev the Arsenal can show magazines of weapons you don't have equipped.
