### ISSUE TITLE
problems get ignored

### ISSUE THREAD

**Issue by DLEGION** [acemod/ACE3#4406]
Its unclear why Commy2 hate me and close my posts, i'm just trying to help fix issues.
so please, someone else take a look at this problem caused by 3.7.0 patch.
in 3.6.2 developer (where titan was locking correctly) it was working PERFECTLY. so its not "bis fault".

the problem : comanche and kajman helicopters can deplete all the ammo ( and i mean bullets, DAGR, skalpel AG, ecc) on a leopard tank, but it will not explode.
tried with javelin...seems very unreliable at best: sometimes 1 hit kill, sometimes 4 hits needed.

**Comment by jonpas** [comment]
You haven't supplied all the information as required in the template. And if you want to fix issues, please pull request the fix then, or stay at reporting them in a friendly manner, no one hates you or closes your issues because "it's you". @commy2 nicely asked you for an RPT file because he can't reproduce it.

Please refrain from opening issues such as this, as this is not the place for it.

**Comment by DLEGION** [comment]
ok....thanks.

**Comment by commy2** [comment]
Fine. I reopened #4405. Maybe there is a bug I can't repro.
