### ISSUE TITLE
Future request: rename Leopard 2 SG

### ISSUE THREAD

**Issue by OssifragA3** [acemod/ACE3#4561]
i think the arma 3 MBT Kuma is the leopard 2 evolution, and not the leopard 2 SG

i have some pictures here, maybe you should rename this tank.

Leopard 2 SG ? :
![1280px-upgraded_leopard_2a4_sg_ndp_2010](https://cloud.githubusercontent.com/assets/22060414/19449196/d7a2b09a-94a4-11e6-81aa-e61210148a30.JPG)

Leopard 2 Evolution:
![das-ist-deutschlands-panzer-zukunft-1200x800-6fb12226d7380863](https://cloud.githubusercontent.com/assets/22060414/19449250/0f92fbd6-94a5-11e6-927f-74975ae8cda8.jpg)

MBT Kuma:
![20161017200721_1](https://cloud.githubusercontent.com/assets/22060414/19449310/581ba1f0-94a5-11e6-864f-db3722294bb0.jpg)

**Comment by commy2** [comment]
We went over this countless times already and the conclusion was, that the tank in Arma 3 is an Leopard 2 SG. 
Since you were to lazy to make this an actual pull request and didn't even read the guidelines on how to make a feature request (hint: this is mainly a bug tracker), I'll also be to lazy to search for those discussions. They might be also on the AGM mods github issue tracker.
