### ISSUE TITLE
Fatigue System

### ISSUE THREAD

**Issue by cmann21** [acemod/ACE3#4756]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
There is nothing wrong with the fatigue system. In fact, this is a very great mod and I love using it. I, however,  would only like to know how to disable it. I want the medical side of this mod for my server but cannot figure out how to disable fatigue.

**Steps to reproduce:**
NONE

**Where did the issue occur?**
NONE

**Placed Modules:**
NONE

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

**Comment by TheGrandVizier** [comment]
I'd like to extend on this question.

**Comment by BaerMitUmlaut** [comment]
@cmann21:
There are three ways to disable Advanced Fatigue:
- delete the `ace_advanced_fatigue.pbo`
- place down the Advanced Fatigue module in the editor and set it to disabled
- use the [ACE settings framework](http://ace3mod.com/wiki/framework/settings-framework.html)

@TheGrandVizier:
The fatigue system is not enabled for AI units, both because they wouldn't know how to handle it and because it would cost way too much performance. Once you remote control an AI unit, the fatigue system will be enabled for it and frozen as soon as you stop remote controlling it. This way it will still be exhausted when exiting and entering the AI unit again.

**Comment by cmann21** [comment]
@BaerMitUmlaut 
Thank you very much for the reply and the help.

**Comment by BaerMitUmlaut** [comment]
No problem!

**Comment by Jestar342** [comment]
Why doesn't this mod just honor the "Enable Stamina" setting which is part of the default game?

**Comment by BaerMitUmlaut** [comment]
Because you can have no fatigue system, vanilla fatigue or ACE3's advanced fatigue this way without deleting PBOs.
