### ISSUE TITLE
Patient in cardiac arrest still with HR and BP

### ISSUE THREAD

**Issue by Howard16AA** [acemod/ACE3#4807]
**Arma 3 Version:** `3.66` (stable 
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.8.2.13` (stable )

**Mods:**
- `@CBA_A3`
- `@ace`
@AceX
@Acre2
@csa38
@CUP_Terrains
@fow 
@ifa3lite
@pecher

**Description:**
Patient is wounded, Bleeding Unresponsive multiple injuries. It shows he has a HR and BP all be it he is bleeding out, In advanced options it appears he requires CPR.

If he does not get CPR and no other intervention then he keeps having a blood pressure then instantly Tier 4s. No 0 HR 0 BP or anything. No chance to work on them with HR 0 BP 0 they are just dead dead. 

However if you treat him as though he has no HR or BP you can save him by doing CPR Epi Etc. 

**Steps to reproduce:**
Shoot another player and wait for them to bleed to unconsciousness. It will never go down to zero until he respawns. 

**Where did the issue occur?**
- Dedicated 

**Placed Modules:**
Unknown

**RPT log file:**
http://pastebin.com/swVtwisK

**Comment by Howard16AA** [comment]
http://images.akamai.steamusercontent.com/ugc/167030516895034461/85275DBA5071E36DC37678CF85DAB17387E15240/

**Comment by Stark91** [comment]
I m not sure it is an issue in your case, your patient is not in cardiac arrest, he is only unconscious.
He has lost a lot of blood, his HR is normal and his BP is under normal (120/90 for healthy soldier in ACE). 
I see that the patient is in pain and someone give him a morphine so it confirms what i think: the server modules are using the option "stop death" (unlimited coma, i don't know the exact text in english, i play with an other language), he would be dead without this option. Instead of be dead, the soldier is in coma until the time limit is reached, the player chose to respawn or someone use a PAK on him (the only solution that i know).
I m not sure we can call it an issue because it is a special case. Normally, the soldier would be dead but the unlimited coma place him in coma to be able to get back in the game quickly.

**Comment by Stark91** [comment]
This will confirm what i say:
[https://ace3mod.com/wiki/feature/medical-system.html#revive-advanced-medical](url)

**Comment by Howard16AA** [comment]
Nope he woke up in the field after some rounds of CPR and epinephrine. 

If they didn't require CPR the option would not appear under advanced options. However it did appear meaning he required it. 

Our server does have death enabled. Players die and continuously do so. It's most certainly an issue.

**Comment by Glowbal** [comment]
Cpr shows when a unit is unconscious regardless of the unit requiring it.

**Comment by Howard16AA** [comment]
Really? I haven't ever seen that. 

Well either way I have never seen a patient go into cardiac arrest on the 16AA server so. There is an issue with our end somewhere then.

**Comment by Stark91** [comment]
In Ace, when a soldier has around 30% of blood volume, he has 10% of chance to get unconscious per second (under 30% he dies), he is not in cardiac arrest.
To get back, the soldier need to have 60-70% of blood volume, a low pain level and no bleeding.

**Comment by Howard16AA** [comment]
Under 30 percent it should go to cardiac arrest not instant death. Cardiac arrest is when a patient is clinically dead. However it should still give medical staff the opportunity to do CPR give adrenaline increase blood volume with blood plasma and saline in order to resuscitate them. 

Not just instant death which is how I interpret your message then. 

What use is the CPR function if the patient respawns as soon as they suffer from HR 0 BP 0?

**Comment by Stark91** [comment]
In your case, you say that there was no 0 HR 0 BP, so he wasn't in cardiac arrest. He just woke up because he has got enough blood. The CPR and epi didn't be useful.

**Comment by Howard16AA** [comment]
He wasn't given blood only transfusions of saline.

**Comment by Stark91** [comment]
There is no difference between saline, blood and plasma in ACE, you can use each of them without problem.

**Comment by Stark91** [comment]
To resume,

- the soldier is bleeding after he takes a wound (pain increase but not enough for the soldier to be unconscious, blood volume decrease)

- he fells unconscious (blood volume too low ~30%)

- the medic stop the bleeding and give saline (blood volume stabilized and increased slowly)

- the patient has a normal HR and a low BP, he gives a morphine (low pain level)

- the medic do CPR and give epi (CPR has no effect because the patient is not in cardiac arrest, epi only increase HR during a few moment)

- the patient get back (blood volume increased enough >60~70%, pain level is low, no bleeding, HR >0, patient is not dead, patient is not in coma)

With your description and what i know, i see no issue.

**Comment by Howard16AA** [comment]
Fair enough I felt there was an issue obviously not  

On that list you provide it says the patient has normal HR and a low BP to give morphine. That would be wrong as morphine would actually decrease the BP more causing more damage to the patient. 

I'm a real life student paramedic so that's how I know about morphine.

**Comment by Stark91** [comment]
I m not medic or paramedic but i know too.
In Ace, morphine decrease HR and decrease viscosity (i don't know the real term in english, it means that BP decrease as BP=viscosity x (HR+blood volume) [in scripts]). In the list, i only resume your situation, i don't know why you give him a morphine at this moment. I think i would give the morphine after saline bags were finished if the patient didn't get back.
According to what i understand in the scripts, HR=80, BP=89/59 is possible with viscosity below normal and ~65% of blood volume.

Once again, it is Ace, i only give you information on how the advanced medical module works but it is not true irl in all situation. For example, in Ace, atropine (same in english?) decrease HR but irl it is wrong, it increase HR. All this content depends on the scripts. To understand how it works, you just have to read and understand it, what ive already done (as i can).

**Comment by Phyma** [comment]
Okey so this is not a issue and should be closed?  since

@Howard16AA  > Fair enough I felt there was an issue obviously not

**Comment by ArwynFr** [comment]
@Phyma
The paragraph on atropine was purely to illustrate that ACE has discrepancies with real life, and thus sometimes, doing what's correct IRL could be wrong in the game, and sometimes you are expected to do something in ACE which could be wrong IRL.

**Comment by Phyma** [comment]
@ArwynFr If this issue is still open to reflect the atropine change then this should be closed because we already have other issues open that reflects any atropine changes.

I'm just checking if the origin of this issue is still a issue since this is so old. If it's not then this issue can be closed.

ACE have alot of open issues that can be closed becuase it's no longer a problem because of other updates. Thus I'm trying to help and find out if things can be closed because they are irrelevant.

**Comment by ArwynFr** [comment]
I'll rephrase : the issue is **not** about atropine.
It was about being able to CPR an victim not in cardiac arrest.

I'm not the OP but I think this can be closed.

**Comment by SilentSpike** [comment]
I believe this issue can be closed, it's really old now anyway so most likely massively out of date. If there are any issues with cardiac arrest just open a new one 👍
