### ISSUE TITLE
Develop Workaround for Handled Damage Issue 45aa80

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#4828]
Develop workaround for handle damage issue which was broke in v1.66 
Reference: https://github.com/acemod/ACE3/pull/4064/commits/45aa80bed7ffccdcb38bd70652c0c23d829d2f00

**Comment by Glowbal** [comment]
> Develop workaround for handle damage issue which was broke in v1.66

Whats the context of this?

**Comment by commy2** [comment]
According to ulteq, hitting the legs fires the handleDamage twice in a row for that hitpoint which is counted as vehicle crash. Only happens in 1.66. ulteq found a work-around, but I want to confirm the underlying issue.

**Comment by commy2** [comment]
I could reproduce this by shooting units with the very heavy vests. Apparently the handleDamage doesn't run for the hitpoints after all when the damage would be zero? Normally it only stops when all the following would be undamaged (so "head" always runs, which was my assumption). I can speculate that this happens, because no damage could be caused by either the new damage being 0 or by simply being below the `minimumHit` threshold, which seems to cause this slight difference in behavior.
@ulteq's work around seems to be the best solution.
