### ISSUE TITLE
Add vests to realistic weights

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#4886]
`Carrier GL Rig` currently weights the same as `Carrier Rig` (and about 1kg more than a `Carrier Rig *Light*`). GL Rig clearly has more armor on it visually and is bigger than a regular Rig, additionally GL Rig provides A LOT more actual armor and should thus weight more as well.

This should overall cause no incompatibilities with inventory. I am not sure how many people stuff vests into their backpacks, it is possible, but in that case it's nothing worse than already existing weight changes for weapons.

Additionall @BaerMitUmlaut said on Slack:
> Make an issue and assign it to me
> That seems right up my alley

**Comment by Armilio** [comment]
I would add that, in my opinion, vest should weight more. There is no real advantage in speed and stamina in not use them and stay "light".

**Comment by kripto202** [comment]
When I worked on one of my uniforms (vests). It has been stated that the vests are actually over weight. The vest part is lighter and then you add the pouches that is needed. I think it might be better to take the armor only into account and let the equipment to add the extra weight. That is why I think that the carrier rig and carrier rig light are the same weight, both having the same armor but less places to put your pouches.

**Comment by alganthe** [comment]
Update on this:
All vests except the special rig seem to have a "normal" weight, the special rig is way too light.

The carrier GL has a 4.54Kg weight, which is about the same as the IOTV gen III with soft inserts (seems about right)

The carrier special seem to have front and back plates inserts and no groin protector.
the groin protector is 0.92 pounds (about 417g), we'll also assume the plates are made of futuristic material weighting 2kg each.

That makes the special carrier around 8.1Kg
it currently weights 5.5Kg, i'm not sure if it has side plates or not, if it does we can round up the weight to about 10.1Kg (assuming side plates weighting 1Kg each because "future" materials)

**Comment by dedmen** [comment]
Milestone -> "Ongoing"
Thus. Don't close.

**Comment by jonpas** [comment]
> Make an issue and assign it to me
> That seems right up my alley

That aged well @BaerMitUmlaut. Closing as keeping this open is pointless.
