### ISSUE TITLE
Cookoff sound and visuals desynchronize

### ISSUE THREAD

**Issue by theYoursTruly** [acemod/ACE3#4900]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.x.x` (dev + c0c41667)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Sound and visual effects have a random delay/desync on the dedicated server. Visualization of the problem: [YouTube](https://www.youtube.com/watch?v=Bdn1XfyfpXA)

**Steps to reproduce:**
- Fire at an armored vehicle with an AT to cause a cookoff.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- [RPT](https://gist.github.com/theYoursTruly/a80710513e783ad511bf6a605dcb8a24)

**Comment by rebelvg** [comment]
Probably say3d can be used. It will stop the sound if the object it's attached to is destroyed and it will follow the object if it moves around.

**Comment by commy2** [comment]
This commit broke it by introducing random delays that are calculated on each machine independently:
https://github.com/acemod/ACE3/commit/059980b1a5cec61edfb67b37e82b30fcb614c0ff

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/blob/master/addons/cookoff/functions/fnc_cookOff.sqf#L135-L137
https://github.com/acemod/ACE3/blob/master/addons/cookoff/functions/fnc_cookOffBox.sqf#L74-L76

Just need to remove these `random`

Because the function runs on every machine, everyone rolls a different number.
Sound and explosion is done by the server, but visuals by everyone (since related commands have local effects).
