### ISSUE TITLE
The ACE weather files, break manual, personal settings for rain.

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#5000]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.9.0` (stable)

**Mods:**
- CBA_A3
- ace
- JSRS Sound Mod

**Description:**
 I tried to create the cloudy weather, but without rain. However, the files - **ace_weather.pbo.ace_3.9.0.16-df693d69.bisign** and **ace_weather.pbo** prevents this! 

Even if the player in the editor, enables the option "manual override"  (intel/rain/ manual override), and sets the value of rain to 0%, then still, after the launch of the mission will be raining!  I tried to move ace weather files into another location and then, after run game, everything works correctly!  So I can say, that the ACE weather files, block manual settings for rain in any mission.

**Steps to reproduce:**
1 place in the editor you as player
2 In the Intel, create more clouds and set the rain on 0% (turn on checkbos - manual override)
3 run the mission, we can see big rain, despite the fact that rain is set at 0% !

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- not needed

**Comment by naizarak** [comment]
ace weather can be disabled through the weather module

**Comment by jshaw990** [comment]
No, I agree with ZeusWrath, even with ACE Weather turned off, the wind is insane, I have a mission with the wind set to manual override at 10% with gusts up to 15% and the wind is set at maximum, there is definitely a problem with ACE Weather.

**Comment by commy2** [comment]
Disable weather propagation. It does not work correctly when "manual overwrite" for wind/rain etc. is enabled in the mission. It's a bug with the weather set SQF commands from BI.

**Comment by Fourjays** [comment]
@commy2 Is the Wind Propagation setting what causes the insane wind levels? I have been trying to figure out the exact cause of that particular bug for a while now.

**Comment by commy2** [comment]
No, BI's API for wind is what is causing the problems when combined with "auto-wind" ("manual overwrite" unticked in 3den). This is because of some compatibility problem with the 3rd party library BI uses for the weather ("SimulWeather" or something like that) and the scripting commands.
ACE weather propagation is using the BI scripting API for manipulating the weather (obviously), but that breaks SimulWeather. When using ACE, "manual overwrite" is ticked when creating a mission, but if the mission is older or was created without ACE, it's disabled and SimulWeather is used instead.

**Comment by PabstMirror** [comment]
Should be fixed via 3.12, let us know if this is still an issue.
