### ISSUE TITLE
ACE MapTool coordinate scale

### ISSUE THREAD

**Issue by garfieldRSC** [acemod/ACE3#5004]
Arma 3 Version: 1.66 (stable)
CBA Version: 3.2.1 (stable)
ACE3 Version: 3.9.0 (stable)

Mods:
-ACE
-CBA_A3

Description:
I think i've found a little flaw with the ace_maptool. The numbers of the coordinate scale in the vertical line are counted in the wrong direction, from top to the bottom instead of from the bottom to the top. I've found no protractor which is counting the vertical scale in the same way the ace_maptool does.

**Comment by PabstMirror** [comment]
So it should be 0 on top and 6 on bottom?
To be honest I'm not sure if we have any original image files for the map tools, so I'm not sure if we'd be able to fix this cleanly.

**Comment by austinjames314** [comment]
I assume you're talking about the roamer: http://imgur.com/Q8x8afn

_This is by design._ Same as why the horizontal marks on the horizontal part of the roamer go from right to left, when the eastings on the map go from left to right.

You put the corner of the roamer on the point of interest, and read the marks on the roamer to get a more precise grid reference:

http://imgur.com/DWdwZ44

In the above screenshot, the grid of the hilltop under the corner of the roamer would be 07776 02669 (plus or minus a meter or two).

**Comment by bux** [comment]
Thanks @austinjames314 for the clarification. Good to know this.

**Comment by jtoppins** [comment]
Thought this was odd too, just orient the roamer south and the scale will be aligned with the map. Maybe we could have an "align north" as well as an "align south" option?

In my opinion given a grid and the task is find the point on the map, aligning south makes this task easier. I can see the usefulness of how the scales are aligned for north, but that seems most useful when the point on the map is already known and a grid is needed.
