### ISSUE TITLE
Understanding of the medical module code

### ISSUE THREAD

**Issue by okaryna** [acemod/ACE3#5056]
I try to understand how dying process works in advanced medical module code.
In ACE_Medical_TreatmentsACE_Medical_Treatments I see:

```
                class Medium {
                    name = CSTRING(Wounds_VelocityWound_Medium);
                    minDamage = 0.3;
                    maxDamage = 0.75;
                    bleedingRate = 0.05;
```
Somwhere in the code there is also check if bloodAmount < 30 or damage > 0.9 then player is set setDead.
Is that means when I receive a wound first of all I can be killed by damage and then after some time I can be killed by bleeding?
Is proper assumption that 3 medium shots will bleed patient to the death in about 
67 sec: When I will be dead directly in cause of wounds. It seems there are lethal and normal damages. I can't figure out what is impact of lethal damages on players condition and connection with normal damage.
What is maxDamage when there is no maxDamage in wound description? Is it 1?
Does damages impact on bloodAmount?
Regards.

**Comment by Phyma** [comment]
This is my first pass at the ACE code but the part you took out is from the class Medium that is in the class velocityWounds. Each wound type have different values minDamage, maxDamage and bleedingRate. 
1: If you ave instadeath turned on then yes you can insta die if damage is over 0.9. if instadeath is off then it will set the damage to 0.9. If you are not yet dead and get blood volume below 30 then you will die.
2: Its hard to say its 67 seconds because bleeding time is calculated depending on type of wound and how big it is and how many they are. And this is the impact of lethal: 
```
if ((_minLethalDamage <= _newDamage) && {[_unit, [_effectiveSelectionName] call FUNC(selectionNameToNumber), _newDamage] call FUNC(determineIfFatal)}) then {
    if ((_unit getVariable [QGVAR(preventInstaDeath), GVAR(preventInstaDeath)])) exitwith {
        _damageReturn = 0.9;
    };
    if ([_unit, false, true] call FUNC(setDead)) then {
        _damageReturn = 1;
    } else {
        _damageReturn = _damageReturn min 0.89;
    };
} else {
    _damageReturn = _damageReturn min 0.89;
};
```
If there is no maxdamage it will get a default value of -1.

Would love if a dev could confirm this so i know im on the right track.

Ps: You arent following your own code standards with Global variables ;)

**Comment by BaerMitUmlaut** [comment]
The answer seems correct, and since no further questions arised I'm closing this.
