### ISSUE TITLE
Ace 3 medical system bug with uniform mods

### ISSUE THREAD

**Issue by TheFrostyPyro** [acemod/ACE3#5072]
**Arma 3 Version:**  1.68
**CBA Version:** 3.2.1
**ACE3 Version:** `3.9.1

**Mods:**
```
- CBA_A3
- ace
-RHS
-TFAR
-Several uniform retexture mods, all from different authors
```

**Description:**
-Whenever a unit with a different uniform that is not RHS or Vanilla, all damage will go to the torso. I.e. I will shoot said person in the leg and their torso will take damage.

**Steps to reproduce:**
Said versions ACE and CBA with any uniform retexture mod that is not RHS.

**Where did the issue occur?**
Self-Hosted server

**Placed Modules:**
None

This issue will happen in any session no matter what kind of server it is.

**Comment by commy2** [comment]
Those uniforms are not compatible then. The ones from BWA3 for example are compatible too.

**Comment by kripto202** [comment]
How do you make sure the uniform is compatible? Is it more on the model?

**Comment by PabstMirror** [comment]
I think this was all fixed with the ArmA patch from around December 2015.
Any uniform put on a vanilla unit should have correctly configured hitpoints.

Try using a vanilla Nato Solider and then adding the uniform with `addUniform`.

If the base unit has modified hitpoints, ace's medical may not work.

Let us know which addon this is happening to and we can check their configs.
If the uniform pack hasn't been updated since that arma patch it may have incompatible configs.

**Comment by kripto202** [comment]
I noticed my uniforms had the same problem and for me to fix it, I just had to remove the class hitpoints to fix the issue. Maybe those uniforms has custom hitpoints and they can simply remove the lines and the problems should be solved.

**Comment by Glowbal** [comment]
Issue is not from ACE, but the third party mod author needs to address and resolve it. @kripto202 and @PabstMirror  posted some helpful hints. Please report this issue to the authors of said uniforms.
