### ISSUE TITLE
Preparing throwable or grenade not working

### ISSUE THREAD

**Issue by kripto202** [acemod/ACE3#5290]
**Arma 3 Version:stable
**CBA Version:stable 
**ACE3 Version:stable (workshop)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- can't prep grenade or trowable advanced throw.

**Steps to reproduce:**
- go to the editor, place yourself, try to do advanced thow

**Where did the issue occur?**
- tested only on the editor

**Placed Modules:**
- none

**Comment by HarryA3G** [comment]
Can confirm that it's no longer working, when pressing Shift+G it simply throws the grenade as if it's vanilla ARMA throwing

**Comment by Sheppard85oc** [comment]
Hello 
I can confirm that with more mods too its not only CBA and Ace3. I hope a fix coming soon too^^

**Comment by jonpas** [comment]
Yes, fix is coming soon, sorry for the trouble, thanks for reporting it so quickly! :)

For explanation: it was an after Release Candidate 1 merge of a compatibility thing after spectator enhancements, but due to an inverted logic broke it instead. (Would be rather hilarious being able to throw grenades from withing spectator though! 🤔)
