### ISSUE TITLE
Build ACE Problem

### ISSUE THREAD

**Issue by br1zey** [acemod/ACE3#5404]
One addon make Problems 
the fastroping addon can't Pack

Error
```
Bis Binarise...
 Checking for binarised rtm...

Bis binarise failed to binarise some or all rtm files.
There was no skeleton that could be used.
Read the documentation

```

**Comment by PabstMirror** [comment]
What version of mikro tools do you have?

**Comment by br1zey** [comment]
pboProoject is 2.23

**Comment by tbeswick96** [comment]
The latest version have these issues. 
Use older versions (1.73, 1.92 respectively). You can find these versions [here](https://armaservices.maverick-applications.com/Products/MikerosDosTools/FileBrowserFree)

**Comment by br1zey** [comment]
ok THX

**Comment by mikerobrooks** [comment]
This faulty is caused by bis binarise being unable to find a skeleton to match the contents of the rtm file. This is caused when the rtm file uses something other than the standard ofp2_manskeleton. Destruct sequences for buildings are an example.  The bones used in _that_ rtm must be in a model.cfg, and that model.cfg _must be adjacent to the rtms in the anims\folder.
