### ISSUE TITLE
Acex fixed sitting placement of unit

### ISSUE THREAD

**Issue by neetch1** [acemod/ACE3#5459]
**Mods:**
```
- CBA_A3
- ace
- acex
```

**Description:**
- Would be great if the placement of the player would be ajusted when using acex sitting.
Thanks

![20170717131637_1](https://user-images.githubusercontent.com/29946799/29751819-1652f048-8b53-11e7-8e88-850c20fa05f2.jpg)
![20170717131630_1](https://user-images.githubusercontent.com/29946799/29751818-15538bb2-8b53-11e7-84e1-722ff72f2295.jpg)
![20170717131543_1](https://user-images.githubusercontent.com/29946799/29751816-12da43ee-8b53-11e7-8269-7f0d2d940aa7.jpg)

**Comment by jonpas** [comment]
Except this is ACE3 repo. Also this is not really possible to adjust further, leaning will always cause overlap, and height can't be adjusted with the current system unless we add a helper object. But for a feature like that I don't want to over-complicate just for minor cosmetics.

Either way, marking as invalid because this is ACEX issue, not ACE3.
