### ISSUE TITLE
ACE Interaction Menus Not Appearing

### ISSUE THREAD

**Issue by MangoTangerine** [acemod/ACE3#5490]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.0` (stable)
**ACE3 Version:** `3.10.2` (stable)
**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- BattleEye is (presumably) causing this issue as the launcher service is reporting that it blocks several ACE .dll files. In-game, I have no indication that ACE is functioning other than having items, being able to wipe my googles, and slinging my weapon.

I believe BattleEye is up-to-date, however as I understand it they have reportedly been having server issues since Aug 20. According to them, this would be the cause of file blocks. Not everyone seems to be having this issue, so I'm under the impression there's a work-around or fix I haven't found.
![why](https://user-images.githubusercontent.com/31823834/30250324-da87986a-9611-11e7-9b8e-3cfbcaaea311.PNG)

**Steps to reproduce:**
- Launch/join any mission. Attempt to open interaction, self interaction, and medical menus.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- N/A

**RPT log file:**
https://gist.github.com/MangoTangerine/58652b60b1f0adb77867b8982b2ad0c9

**Comment by PabstMirror** [comment]
>We are aware of file block issues and are working on getting them resolved ASAP.
https://twitter.com/TheBattlEye/status/906901601604046849

Nothing we can do if battleye is blocking dlls.
You can run the game with battleye disabled
I just tried and it was working, so they may have already fixed the issue.

**Comment by RogueAus** [comment]
I'm having this issue, tried restarting Battleye but didnt work. I dont run a public server at the moment so I can disable battleye for now, but this sucks since I'll probably have to make all my players disable it too if they have the same problem 😆 
![screenshot_2](https://user-images.githubusercontent.com/17485782/30412779-8ae3bd82-994c-11e7-8d4d-c28cefb63e4b.png)

**Comment by RogueAus** [comment]
By the way guys, this is not a new problem and you know it, I and several other people have made multiple posts on here and other sites regarding this issue. Here is one such site: https://www.fuckknows.eu/forums/topic/82-battleye-blocking-ace-dll/ 
but I could find more quite quickly. If this has been happening to people since last year doesnt that say that this is an ongoing issue and needs to be addressed and discussed with them instead of being left up to battleye to fix?

**Comment by PabstMirror** [comment]
Just to see what happens, could you try running a non-steam version of ace
https://github.com/acemod/ACE3/releases/download/v3.10.2/ace3_3.10.2.zip

It could possibly be something like the file path is too long, but I doubt it.

Otherwise I really don't know what the problem is, I just tried and battleye accepted my copy of the workshop version's dlls just fine and they should be identical.

**Comment by MangoTangerine** [comment]
I have wonderful news, the non-workshop version works! I had tried it in the past, but I didn't try using different keys. Turns out my Logitech G710+ doesn't like to let programs use the Windows key. 

That being said, my workshop version is still blocked by BattleEye. I tried rebinding the keys with it loaded, no dice. Not sure what's going on there.

Thanks for the assist guys, going to catch up on all that realism I've been missing out on.
