### ISSUE TITLE
Fatal Damage - only headshots would kill a downed unit

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#5510]
This was brought up in some past conversations.

**Observations:**
https://www.youtube.com/watch?v=wD8ZKuD-5D4 
Note that the player survives many bullets.

The victim gets hit.
He seems to receive a non-instantly fatal wound. 
He goes unconscious.
Then he just bleeds. 

**Notes:**
- This was not on our internal ACE Dev test server however. 
- This was an AI - but it is believed this should not matter 

**Expected:**
Player is expected to die faster in this video.

**Comment by derbismarck** [comment]
https://github.com/acemod/ACE3/blob/medical-rewrite/addons/medical/functions/fnc_conditionCardiacArrestTimer.sqf - x60 multiplication is probably not meant to be there. Unit will wait 30 minutes (in default configuration) before dying in cardiac arrest.

https://github.com/acemod/ACE3/blob/32e73fa1b314180dc436985a461bf25f5cda7881/addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf#L127 - Controls when the `FatalInjury` event occurs (only headshots based on the condition) that will cause the state machine to enter the `FatalInjury` state from `Default`, `Injured`, or `Unconscious`. Also the same event that causes the transition from `CardiacArrest` to `Dead`.

**Comment by SilentSpike** [comment]
> x60 multiplication is probably not meant to be there. Unit will wait 30 minutes (in default configuration) before dying in cardiac arrest.

Yeah it looks like this setting used to be in minutes (see 39582914f743d586efcc361e9d01d97cd8e0ab77), but was later changed to seconds without updating this piece of code to match.

**Comment by DocScarle** [comment]
A body dies from shock. Septic shock caused by bacteria, Anaphylactic shock caused by hypersensitivity or allergic reaction, Cardiogenic shock from heart damage, Hypovolemic shock from blood or fluid loss, and Neurogenic shock from spinal cord/brain trauma.
Therefore in slow reality it would mean that the AI you shot would only die once these criteria have been met.
Would it not be right to have each wound cause an amount of Hypovolemia that is added to a total once that total reaches a certain level the patient suffers injuries not conducive with life and expires.

**Comment by SilentSpike** [comment]
In addition to something along the lines of #6277 we might want to think about removing the cap on blood loss and letting units bleed out incredibly fast if wounds stack up
