### ISSUE TITLE
Enabling forced ringing in the ears

### ISSUE THREAD

**Issue by KiDosn** [acemod/ACE3#5549]
**Arma 3 Version:** `1.76` (stable)
**CBA Version:** `3.4.1` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Please correct the possibility of ringing in the ears. I know there is an option to forcibly turn off ringing, and also not to oblige. But why there is no way to force the ringing in your ears. After all, this is  advantage over players who have **NOT** turned off ringing in their ears.

**Where did the issue occur?**
-  Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- Ace_ModuleHearing

**Comment by bux** [comment]
Use the Settings System: https://ace3mod.com/wiki/framework/settings-framework.html

**Comment by PabstMirror** [comment]
I think we didn't add the setting to the module was because some people actually have hearing problems and find the ringing noise painful.

https://github.com/acemod/ACE3/blob/master/addons/hearing/CfgVehicles.hpp#L121

we will lose this when we switch to cba settings unless we re-work the logic
but I'd say server admins could just listen to their players and if someone says they can't stand the noise then just don't force it on.

**Comment by KiDosn** [comment]
Then maybe tell me how I can implement it for my server, because we have a small community and we do not have people who do not hear well

**Comment by 654wak654** [comment]
> Use the Settings System: https://ace3mod.com/wiki/framework/settings-framework.html

**Comment by jonpas** [comment]
@654wak654 look at @PabstMirror's comment. 😆
