### ISSUE TITLE
ACE Arsenal stats suggestions

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#5964]
I am currently gathering informations in order to make the stats feature in ACE Arsenal,

### General

- Weight `mass` (bar + number)

### Primary / handgun:

- Rate of fire `reloadTime` (bar)
- Accuracy `dispersion` (bar)
- Range `maxZeroing` (bar)
- Impact `hit` (bar)

### Launchers

- Range `maxZeroing` (bar)
- Impact `hit` (bar)

### Containers

- Ballistic protection `passthrough` (bar)
- Explosion resistance `armor` (bar)
- Load `maximumLoad` (bar)

### Helmets

Same as containers minus load.

Any suggestions?

**Comment by dedmen** [comment]
Advanced ballistics

## Magazine

- Ammo displayname (does ammo even have a displayname?) Otherwise maybe classname of Ammo
- [Ballistic coefficient](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L18) and [type of coef](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L21)
- [Bullet mass in grams](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L16) and converted to grains
- [Muzzle velocities](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L22).. Which... is complicated.. They are an [array of muzzle velocities](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L22) that are different based on [the barrel length](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L23) of the [weapon](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp#L412) they are used in. And they also differ in [temperature](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgAmmo.hpp#L17).
Config velocities are in m/s maybe also want conversion into feet/s
The ACE_ammoTempMuzzleVelocityShifts is the temperature difference per 5°C from -15°C to +35°C

I don't think you need bulletLength/caliber/atmosphere.

## Weapon

- [BarrelTwist](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp#L411) in mm from config and also converted to inches
- [BarrelLength](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp#L412) in mm from config and also converted to inches
- Maybe [Dispersion](https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp#L414) is stored in Radians in config. Show that converted to MOA or Degrees. only `Single` firemode is really interesting. Not sure if you are forced to call that `Single` Mods could name it differently which could cause problems.

**Comment by Dystopian** [comment]
Sorting by some parameters would be helpful. E.g. sort vests by armor and load. And maybe weight.

**Comment by alganthe** [comment]
^ i'd need to save each stats in uiNamespace for thousands of items, unfortunately that's not happening, you can sort by mass for the right panel because the stat was already being stored in the listbox row for greying purposes.
