### ISSUE TITLE
ACE DAGR does not always display the correct grid for some CUP maps

### ISSUE THREAD

**Issue by Neciota** [acemod/ACE3#5991]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5.0` (stable)
**ACE3 Version:** `3.10.2` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- ACRE2
- CUP Vehicles
- CUP Weapons
- CUP Terrains (Core + Maps)
- CUP Units
```

**Description:**
- ACE DAGR does not display the correct (vertical) grid for some CUP maps (Sahrani, Chernarus). I believe this to be because some CUP maps have grid 000 000 situated top left instead of the vanilla bottom left. 

**Steps to reproduce:**
- Place down unit in editor on Chernarus or Sahrani and add a DAGR.
- Load into the editor and open your map and DAGR.
- The vertical grid does not match the one on the DAGR

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None.

**RPT log file:**
- No relevant RPT as there is no script errors. 
Screenshot:
[Here](http://oi68.tinypic.com/9unccp.jpg)

**Comment by bux** [comment]
Not sure if that's an error with our code or something in CUP Terrains directly

**Comment by PabstMirror** [comment]
In your screenshot you are between northing lines 051 and 050 and device reads 0504.
So I think it's as correct as we can make it (we want it to be continuous, so 05001 is 1 meter from 050)
The problem is the northings on the map are reversed.

The map's need config level changes to be correct (something ace can't do), and those changes could break old missions so I'm not sure if cup would want to change anything.
