### ISSUE TITLE
Map gray effect 

### ISSUE THREAD

**Issue by Triebtaeter** [acemod/ACE3#6054]
Hello I have a question how do I get this gray effect of the map away? I know that this effect comes from the ace_map.pbo

http://prntscr.com/i15eiy

that's the way it should look in the end
https://prnt.sc/i151i8

**Comment by dedmen** [comment]
How do you know that ace_map.pbo is causing that effect? Did you test how it looks in Vanilla Arma without ACE?

**Comment by bux** [comment]
The second screenshot you've provided doesn't show a map. I'm confused.

**Comment by Triebtaeter** [comment]
ups sorry https://prnt.sc/i151i8

**Comment by AACO** [comment]
@Triebtaeter if you're doing a custom build of that PBO you can try changing `maxSatelliteAlpha = 0.5;` (https://github.com/acemod/ACE3/blob/master/addons/map/config.cpp#L40) to a higher value.

Besides that, it can't really be changed at runtime, since it's part of ArmA configuration (as far as I know).

**Comment by Triebtaeter** [comment]
@AACO thx =)
