### ISSUE TITLE
AI helicopters didn't use Infrared Countermeasures when Javelin/Titan missile fire on them

### ISSUE THREAD

**Issue by BlackburnUTG** [acemod/ACE3#6116]
Arma 3 Version: 1.8.143869 stable
CBA Version: 3.5.0 stable
ACE3 Version: 3.12.1 stable

**Mods:**
- CBA_A3
- ace

**Description:**
When a javelin rocket fired into the helicopter, helli never uses сountermeasures, And 100% get destroyed by it. There is no reason to use AA guns then
[https://www.youtube.com/watch?v=4UAdCAEW72I](https://www.youtube.com/watch?v=4UAdCAEW72I)

**Steps to reproduce:**
place in editor: player with titan/javelin and enemy hellicopter in the air, Lock on it and fire

**Where did the issue occur?**
everywhere

**Placed Modules:**
no

**RPT log file:**
no

**Comment by Dystopian** [comment]
Javelin relies on a target thermal view and cannot be detected with countermeasure system.

**Comment by dedmen** [comment]
There is a reason the Javelin is so feared and soooo expensive. Because of things like that.

**Comment by BaerMitUmlaut** [comment]
IR guided missiles can be detected by countermeasures systems, it's just very hard and you need to react extemly quickly, as they can only be detected once launched. I'm not sure how widely used those systems are on helicopters, [the US seems to use them though](https://www.orbitalatk.com/defense-systems/defense-electronic-systems/an-aar-47/). There's a good article on Wikipedia about it: https://en.wikipedia.org/wiki/Missile_approach_warning_system

>There is no reason to use AA guns then

If you take a look at the modern battlefield, they are not used anymore, except as a last defense on ships, bases and SAM sites. MANPADS are relatively cheap and have proven to be very effective (they've had a major impact on the Soviet-Afghan War for example). Oh and of course insurgents still use AA guns because they don't have missiles.

---

Disregarding all that, we cannot trigger the vanilla missile detection system. There's no functionality for that. We could, in theory, make the pilot manually fire the flares, but then we have to consider reaction time, if the helicopter has actually one of those detection systems installed, etc. etc.
