### ISSUE TITLE
ace_medical minimal unconscious time is too low

### ISSUE THREAD

**Issue by severgun** [acemod/ACE3#6178]
**Arma 3 Version:** `1.80` stable
**CBA Version:** `3.5` stable
**ACE3 Version:** `3.12.1` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
Default delay 5-15 sec seems too low. Shoot, miss, miss, reload. Enemy is up...
Would be nice to see it as addon setting. Or tuned random to 10-60 sec or even 20-100.
```
#define DEFAULT_DELAY (round(random(10)+5))
```

**Steps to reproduce:**
Set unit unconscious. Wait for revive.

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None

**Comment by Armilio** [comment]
Agree, i did an ACE costum version with 55-85sec. 

`DEFAULT_DELAY (round(random[10, 30, 40]+45)) `

With increased blood loss multiplier (x2.7) it means have more occurrences of people that stay down unconscious because "lost a lot of blood". And so they need a medic with blood sacks and ephinephrine. 

I would like a cba setting for that but maybe i already asked it here or on Slack, so in this case sorry i don't want to seem clamant.

But i think that there is also a difference of opinion about what this knock out state should simulate. It seems that for the ace_team it's just a shock reaction, and not really a unconsciusness.
