### ISSUE TITLE
Can't link belt when magazin is empty

### ISSUE THREAD

**Issue by kamkill01011** [acemod/ACE3#6181]
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.6.1` (stable)
**ACE3 Version:** `3.12.1` (stable

**Mods:**
- CBA_A3
- ace

**Description:**
- When the gunner magazine is empty the assistant can check ammo but not link belt.

**Steps to reproduce:**
- Place a CSAT AR and assistant AR
- Remove all mags of the AR except the one loaded.
- Shoot until your mag is empty
- Take controle of the assistant AR and try to link belt
- You see the mag on the weapon, you can check ammo and temperature, but oyu can't link belt
- If you remove the mag of the AR you can only check temperature, but not check ammo or link belt

**Where did the issue occur?**
- Self-Hosted Multiplayer / Editor (Singleplayer)

**Placed Modules:**
- none

**RPT log file:**
- none

**Comment by PabstMirror** [comment]
I'm pretty sure this is by design as you need access to the loaded belt to be able to add more rounds to it. In general, I think once you have fired your last round, you will have to open up the gun to hook up the new belt.

```
// Exit if the belt is full or empty
if (_ammoCount == 0 || getNumber (_magazineCfg >> "count") - _ammoCount == 0) exitWith {-1};
```
We might want to even increase to require 2+ ammo left in the loaded belt otherwise the last bullet might not be accessible.

**Comment by Drofseh** [comment]
Makes sense to me, if there's no ammo in the belt then there's no belt to link to.
