### ISSUE TITLE
Feature Request: Disable ACE damage/medical system for a.i. entirely

### ISSUE THREAD

**Issue by PrivateIron** [acemod/ACE3#6184]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
-There is Only War
```

**Description:**
With previous mods and past units, i have had no issue of using a modded gun not compatabile with ace, it usually dealt its designated damage, if finicky in terms of interaction between it and other systems.
But my unit is currently trying to setup an liberation server using a 40k mod called There is Only War
and several of the weapons (Notably the las weapons) simply not working. after much testing and with some people who know how this stuff works far better then i do,  it was discovered the weapons do so much damage with the ace system the system simply goes "What just happened? that shouldnt happen, lets ignore it", and that it takes several repeated shots usually for it move past this, and simply outright kill the target, so usually you take no damage or none whatso ever

after much brainstorming for solutions, it was determined no matter what we did, we had to contact devs of some kind at either end, and the most widespread use we could think of was to simply have the ability to turn off the ace damage model for a.i. specifically, and restrict what weapons they can use to something that does work, allowing the players to still enjoy using ace without being absolutely unable properly complete missions without having to use non-mod assets that go against what we had intended for the server's theme to be. (we may just pay the TIOW devs in the end to finally create a compatibility patch and pressure them into updating that along with the main mod

(one of the people we have setting our server up may or may not send a second issue report as a feature request and provide more relevant information possible)

**Comment by dedmen** [comment]
Thank you for your request, but this is a feature request just like you wrote in the title. Please move it to the appropriate issue outlined in this guideline: https://ace3mod.com/wiki/user/how-to-make-a-feature-request.html

**Comment by BaerMitUmlaut** [comment]
As dadmen already mentioned, this is a feature request and should go in the appropriate issue. In addition to that, disabling ACE medical completly just through settings is not possible because of technical reasons. This has been mentioned multiple times in the feature requests issue.

I am also not sure what the creator of the mod does that makes ACE handle the damage in such a weird way, it's the first time I've heard of such an issue. You should definitely contact him. I took a quick look at the mod and the first thing I noticed is that he is completly overwriting the BulletBase class, which is basically the base class for all projectiles. That's generally a horrible idea and might very well a reason why it's not working.
