### ISSUE TITLE
Offest for large containers too small when being unloaded from trucks

### ISSUE THREAD

**Issue by KalleK-OPT** [acemod/ACE3#6357]
Arma 3 Version: 1.82 stable
CBA Version: 3.7.0
ACE3 Version: current to Steam WS

**Mods:**
- CBA_A3
- ace

**Description:**
- we have large containers (Taru and Huron pods) loadable into any kind of big truck (HEMMT, Zamak etc), when being unloaded they are put too close to the person unloading them or the truck causing critical damage to the person / the container / the vehicle

**Steps to reproduce:**
- set cargo size for containers as well as the adequate capacity to the trucks
- load container into truck -> unload container

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None

short video
https://youtu.be/t5-_39Krvqs?t=43

**Comment by Vdauphin** [comment]
This could be due to:
`isNumber (configFile >> "CfgVehicles" >> "Land_Pod_Heli_Transport_04_medevac_black_F" >> "ace_cargo_fnc_size") = false` so in `ace_common_fnc__findUnloadPosition` the `_radiusOfItem = 1` and return a position too close to the unloading vehicle.

**Comment by KalleK-OPT** [comment]
thx for the reference ... hope there will be a solution in one of the upcoming updates! keep up the great work!

**Comment by Vdauphin** [comment]
I did a mistake on this:
`isNumber (configFile >> "CfgVehicles" >> "Land_Pod_Heli_Transport_04_medevac_black_F" >> "ace_cargo_size") = true` and `getNumber (configFile >> "CfgVehicles" >> "Land_Pod_Heli_Transport_04_medevac_black_F" >> "ace_cargo_size") = -1`
So https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_findUnloadPosition.sqf#L47-L48 : 
`_radiusOfItem = (- 1) ^ 0.35) max 0.75 = 1.#QNAN`
It is even worst because the `_radiusOfItem` is just a NaN.
