### ISSUE TITLE
Opening arsenal on a player.

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [acemod/ACE3#6428]
**Arma 3 Version:** `latest` (stable )
**CBA Version:** `3.7.1` (stable)
**ACE3 Version:** `3.12.2 (stable )

**Mods:**
```
- CBA_A3
- ace
-Custom mod I'm working on
```

**Description:**
- I'm trying to make logged in admins be able to open the ace arsenal on a remote player to edit the player's gear live.
I find the remote player by their UID and call the function like this:
`_player = [_playerUid] call MRH_fnc_MilsimTools_Core_FindPlayerByUID;
[player, _player,true] call ACE_arsenal_fnc_openbox;`
I have also tried with 

`[_player, _player,true] call ACE_arsenal_fnc_openbox;`

In MP and on a dedi server:

In both cases I can edit the player's uniform and its content, the player's vest and it's content, the player's helmet and it's contents. No worries.

But :
-backpacks can't be changed at all.
-weapons can be changed on the admin's local machine, but are not changed for the player. Upon closing the arsenal the admin will see the new weapon on the player until (I'm guessing) the server kicks back in and restores the original weapon. The remote player doesn't see their weapon's change at all.
I'm guessing this all has to do with locality of items but I wonder if that's known/ intended behavior & if there is a workaround.

**Steps to reproduce:**
- Find remote player,
-Call
`[_player, _player,true] call ACE_arsenal_fnc_openbox;`
Change weapons and try to change backpack.

**Where did the issue occur?**
- Dedicated MP

**Placed Modules:**
- None

**RPT log file:**
I can provide the rpt but i've looked into it and it seems irrelevant.
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by alganthe** [comment]
This is due to ACE Arsenal using the local variants of addWeapon and addBackpack, in hindsight I should've.
I'll fix that.

Now in your current situation you could try to add a displayClosed EH and use getUnitLoadout / setUnitLoadout, the problem is that I have no idea if the data this command retrieves is from the remote unit or local one.

If that doesn't work your best bet is adding everything back yourself, what the unit possess is stored in `ace_arsenal_currentItems` , just be aware that this var only exist between the displayOpened and displayClosed EHs
More info on the currentItems array: https://github.com/alganthe/ACE3ganthe/issues/8
More info on the EHs: https://ace3mod.com/wiki/framework/arsenal-framework.html#60-eventhandlers

**Comment by MisterHLunaticwraith** [comment]
Thank you for your answer, I was planning on a workaround solution like that.
