### ISSUE TITLE
Differentiate PAK and Medkit

### ISSUE THREAD

**Issue by SilentSpike** [acemod/ACE3#6458]
An area of the medical UX that could use improvement. These item names are ambiguous and so similar that their use is not immediately self explanatory.

What ShacTac have done:
- Personal Aid Kit -> Basic Aid Kit
- Medkit -> Advanced Aid Kit

I quite like this personally, but perhaps other people feel that it's not realistic enough? Please weigh in with any thoughts!

**Comment by BaerMitUmlaut** [comment]
There's no medkit item?

**Comment by jonpas** [comment]
Surgical Kit maybe?

**Comment by BaerMitUmlaut** [comment]
That does something completely different though? I'm confused now.

**Comment by thojkooi** [comment]
I think there is a medkit in vanilla? Though that is switched out by medical supplies on init.

**Comment by dedmen** [comment]
It's called "First Aid Kit" in vanilla.

**Comment by SilentSpike** [comment]
I admittedly didn't check the item list and just brought this up based on ShacTac's feedback. However, I just looked now and see this:

```

    class ACE_medKit: ACE_ItemCore {
        scope = 2;
        displayName = CSTRING(Med_Kit_Display);
        picture = QPATHTOF(ui\items\personal_aid_kit_x_ca.paa); // todo: new picture
        descriptionShort = CSTRING(Med_Kit_Desc_Short);
        descriptionUse = CSTRING(Med_Kit_Desc_Use);
        class ItemInfo: CBA_MiscItem_ItemInfo {
            mass = 10;
        };
    };
    class ACE_personalAidKit: ACE_ItemCore {
        scope = 2;
        author = ECSTRING(common,ACETeam);
        displayName = CSTRING(Aid_Kit_Display);
        picture = QPATHTOF(ui\items\personal_aid_kit_x_ca.paa);
        descriptionShort = CSTRING(Aid_Kit_Desc_Short);
        descriptionUse = CSTRING(Aid_Kit_Desc_Use);
        class ItemInfo: CBA_MiscItem_ItemInfo {
            mass = 10;
        };
    };
```

**Comment by thojkooi** [comment]
So it looks like it's something that was newly introduced in the medical rewrite? I don't remember any thing about it.

It apparently is used for a partial heal treatment action. I don't think we should keep this in the rewrite. Judging from the code, it defeats some of the other gameplay mechanics.

**Comment by SilentSpike** [comment]
I would be on board with adding back a "Bandages Heal Damage" setting and removing the medkit

**Comment by nk3nny** [comment]
To give a perspective on how the pre-rewrite medical system has worked in one clans practice. We play with a form of pseudo-Advanced Medical enabled: 

In nopryl.no we equip Medics with the **Personal Aid Kit** which with our settings functions as a sort of madical rub-box capable of healing all ails in the field. Especially splints.  The PAK is multi-use, must be used on a stable target, and can be employed anywhere in the field. Our only concern is that the PAK is very light; there is little to discourage anyone from picking it up. 

Each soldier carries a conservative number of bandages and tourniquets for immediate first aid needs.  Because the PAK is a true Panacea we have little need for neither epinephrine nor morphine. 

The gameplay effect of this mirrors vanilla play, with some added complexity from bleeding and binding limbs. Our style emphasizes team work before realism. Generally a full platoon runs with 1-3 medics, either squad based or centered around the platoon HQ.  

---

A community perspective on this may be this: 

- We appreciate that the vanilla  **First Aid Kits** are split into bandages, morphine, and tourniquets. Though we generally ignore the plethora of bandage-variants. 
- We would love to have **Personal Aid Kits** be single-use heal-alls
- We would love to have **Medkits** essentially be heavier (at least the same as toolkits) multi-use Personal Aid Kits

This distinction mirrors the ACE setting to allow PAKs be multi-use in a diegetic, rather than an out-of-game manner. 

We tend to play infantry focused missions where forced limping would be a major detraction from the session experience. Having settings for treating limbs, without an excess of differentiated equipment, would in our opinion be beneficial. 

Keep up the good work!

**Comment by alganthe** [comment]
@nk3nny 

Basic / advanced has been replaced by another system.

You however:
- Can toggle advanced bandages
- Can choose who can use epinephrine and where.
- Can toggle advanced diagnose
- Can toggle self IVs.

You can have an experience closer to vanilla with the medical rewrite, however, limping is a fairly big issue as I pointed out a few posts above.

I do not think the medkit is a good solution to this issue.
Reintroducing heal hitpoints and maybe splints or some kind of special item to get rid of limping if the players don't want to use medkit seems to me to be a better idea.

Meaning that for your community you would still be able to carry PAKs, make them multi-use or not and you'd be able to get rid of limping by either using the PAKs or using the said special item.

In this example the rest of the communities aren't stuck with magical panaceas and everyone has a solution to limping.

**Comment by dedmen** [comment]
I also prefer splints. We just got a PR for them in the old med system. No big deal getting them into the new one.
It's kinda sad to see how in my group we constantly use PAK's to get people running again.

We had a lot of discussion in Slack about Splints and how they should work.
We could make it like the tourniquet such that wearing it for a long time causes pain to make it unattractive to run around with a splint for a long time.
In most cases it's enough to just patch someone up for maybe 10 minutes before he can get to a safe place and get patched up by a medic.

Maybe some mechanic to repair legs in the field? splint+surgical kit? I know it's not realistic. But that would be a nicer variant than bandages with heal hitpoints or using a full PAK.
And first having to apply a splint and then going over it with a surgical kit makes it more like a real "operation". And you need time and relative safety to do that.

I also like the idea of single use PAK and multi-use but heavier medikit. Also consulted my groups medics about it and they like it too.

**Comment by SilentSpike** [comment]
I'll come clean and admit I've always hated the PAK 😄

Anything that allows players to not have to resort to using a magic full heal item is good in my book.

**Comment by SilentSpike** [comment]
So, to summarise ideas so far:
- Add an option to allow bandages to heal damage as well as blood loss
- Introduce a splint item which will prevent limping while applied (needs model and icon)
- Introduce single-use and multi-use full heal items and remove the setting to toggle PAK behaviour

Also, I'd like to throw another one into the mix:
- We could make it so that damage slowly repairs itself if the unit isn't bleeding and is stable with a sufficient blood volume (if we add a split, broken legs could also have the caveat of requiring that applied first).

**Comment by dedmen** [comment]
For the self-healing not to be overpowered we'd have to make it so slow that you might aswell use a PAK. Not worth the effort.

**Comment by alganthe** [comment]
same thoughts as dedmen on self healing, it's not worth it.

**Comment by ArwynFr** [comment]
I'd like to toss my 2 cents in here.

I think it's important to keep the PAKs' behavior as a magical wand able to instantly restore one's condition. Both for consistency with previous versions and to allow instant health restore in some (non roleplay) situations.

The medkit could be dedicated to a « more realism option » regarding limbs. When activated, this option would force the player to crawl instead of limping when damage stacks over the threshold. Applying a splint-like item could allow to limp at the price of raising pain (tourniquet-like), and the medkit would be used to restore the ability to walk/run. Similarly damage to arms would cause weapon drop / weapon sway / customAimCoef restore.

Would be too hardcore an experience, perhaps ... wouldn't it ?

**Comment by Gwynblade** [comment]
I really like the idea of splint acting as a temporary solution that causes pain after a while, and splint+item (surgical or medkit) for a more permanent fix - much nicer than bandage to heal, or full heal PAK - in my opinion of course.

Regarding the medkit, in ACE2 (I know you're probably tired of hearing this), 
medkit used to fix legs, and do small amount of healing in the field (full heal in medical facility).

-It was a single use item, but medics carried 2 by default, so you could replenish of enemy medics when in dire need.
-Medic could also use it on himself, so if you only have 1 medic, he could fix his legs by himself and not slow the team down.
-Only medic and some special forces could use it in the field, anyone in the medical facility.

Maybe you could take some of this into account, if you decide to make a new single use item.

On top of that, adding splint into the mix, we'd have something like ACE2 medical on steroids, which would probably shut a lot of people up that enjoyed ACE2 medical (myself included).

**Comment by dedmen** [comment]
>-Medic could also use it on himself, so if you only have 1 medic, he could fix his legs by himself and not slow the team down.

Splints are easy to use. I think it wouldn't be a problem to let non-medics apply splint's so that they can temp heal the real medic. The medic ofcause would need to get real treatment sometime later.

**Comment by nk3nny** [comment]
I like the idea of splints being tourniquet-like extensions to the system. I will reiterate the concept of offering both PAKs and medikits. Medikits simply being heavier, but infinite-use PAKs.

A PAK being able to full heal in he field. 

This creates a nice consistent system which is easy to adjust to each groups needs.

**Comment by Will-Nichols** [comment]
Personally I like the option of leaving guys limping and making it a little challenging to finish the mission. Sure in small communities its a pain in the butt but in larger community missions it allows for multiple variables to be introduced.

If I as a platoon leader have >1 or more injured players what do I do?
A) is it better to establish a Medevac point and have them get a ride back to base? Provided I have a way to transport them to base whether by vehicle or helo?
B) If we are mechanized/motorized I can have the wounded player(s) switch out with someone as a driver(s) and or operator of vehicle gun(s) and still stay in the fight/assisting the overall mission without sacrificing mobility.

In our community we tend to have the more in depth full scale type of mission with longer operations and actually have a medical aspect we like to run with for triage and calling in CASEVAC when we get the engagement down to a manageable point. 

We would love to see some various options in the settings to allow communities to make adjustments to how they function with the various available items such as a _personal aid kit_; which should be the basic stuff to allow you the player to put white stuff on red stuff till the medic arrives. Along with the Medic(s) having a more comprehensive _medical bag_ that is literally just shy of a mobile operating room and then having a _surgical kit/items_ available back at base to allow for complete healing of the players. 

**Personally for me being able to heal in the field is not something that our community is fond of and outside of less realistic game modes such as Wasteland, Exile, KOTH, Overthrow, Liberation, etc...its great for when I want to just jump into a public server and play but for our milsim group it's not what we enjoy and what we like as a whole.**

**Comment by SilentSpike** [comment]
This is the advantage of adding items like splints, you can choose to not gear players with them if you don't want them to be able to heal limping in the field 👍
