### ISSUE TITLE
Setting ace damage through script question.

### ISSUE THREAD

**Issue by Drksydde** [acemod/ACE3#6471]
I am currently making a zombie script and want the damage from the zombie hit to register in the ACE3 medical system. Right now the only damage I am able to get the zombie to do is through the default setDamage command. Does anyone know how the ACE3 damage system works and how to send damage to that system? 

if (_unit distance _victim <= _attackDistance) then {call "damagePlayer.sqf"};

and damagePlayer.sqf is

[mainCharacter, 0.8, "head", 'bullet'] call ace_medical_fnc_addDamageToUnit;

**Comment by dedmen** [comment]
`call "damagePlayer.sqf"` That's not how `call` works.
`[mainCharacter, 0.8, "head", 'bullet'] call ace_medical_fnc_addDamageToUnit;` AFAIK that's exactly how you're supposed to do it.

You don't say what your actual problem is aka why it doesn't work for you.

This is a issue tracker. It tracks issues. Not a question board. For questions you should join the ACE Slack. You'll also get answers there much faster. https://slackin.ace3mod.com/

**Comment by PabstMirror** [comment]
Zombies will probably have different locality than the players, so you'll need to use event handlers
```
["pabst_addDamPass", {_this call ace_medical_fnc_addDamageToUnit}] call CBA_fnc_addEventHandler;
```
```
["pabst_addDamPass", [_target, 0.8, "leg_r", "stab"], _target] call CBA_fnc_targetEvent;
```
