### ISSUE TITLE
PCML launcher has no valid ammo when not using disposable pbo 

### ISSUE THREAD

**Issue by Neviothr** [acemod/ACE3#6591]
**Arma 3 Version:** `1.85.145075` (dev)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- While ACE and CBA are used, the PCML launcher has no valid ammo that can be added using both the ACE, and BI VAs.

**Steps to reproduce:**
- Open the ACE VA. Click on the launcher icon on the left panel, select the PCML launcher, click on the magazine icon on the right panel, notice how the PCML has no ammo/magazines available.

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
- https://gist.github.com/Neviothr/32b9260fc8984aadf07be95c87448561

**Comment by bux** [comment]
That is by intention. The NLAW (which is the real name for the PCML) is a single-use launcher. There's no ammo for it.

**Comment by Neviothr** [comment]
@bux - the bug occurred while only the following components were loaded, IIRC none of them turn the the PCML into a 1-shot weapon.
```
zeus
weaponselect
ui
tracers
thermals
quickmount
overpressure
optionsmenu
nouniformrestrictions
noream
noradio
noidle
nightvision
movement
modules
missionmmodules
main
magazinerepack
interaction
interact_menu
hitreactions
frag
explosives
dragging
common
ballistics
arsenal
aircraft
ai
advanced_throwing
advanced_fatiuge
```

**Comment by bux** [comment]
This is kinda missing in the description ¯\\_(ツ)_/¯

**Comment by Neviothr** [comment]
Reopen?

**Comment by Superxpdude** [comment]
As far as I can tell, this is caused by line 145 of fnc_scanConfig.sqf in the arsenal module.
https://github.com/acemod/ACE3/blob/d3727d7c27d7a0f95ff71eee3ec1d3203a393be7/addons/arsenal/functions/fnc_scanConfig.sqf#L145

It seems to me that this is where ACE Arsenal creates it's master list of magazines so that it can be displayed more quickly later on. It's looking for the `type` value for the magazine to be in the following list: `[256, 512, 1536, 16]`.
The default value for the PCML magazine seems to be `768`, or `3 * 256`. Which seems to exclude it from the master magazine list.

In addition (though I know it's not something with ACE itself), this seems to affect the CUP NLAW as well, since I imagine it uses the same value as the vanilla PCML.

**Comment by Neviothr** [comment]
> As far as I can tell, this is caused by line 145 of fnc_scanConfig.sqf in the arsenal module.
> https://github.com/acemod/ACE3/blob/d3727d7c27d7a0f95ff71eee3ec1d3203a393be7/addons/arsenal/functions/fnc_scanConfig.sqf#L145
> 
> It seems to me that this is where ACE Arsenal creates it's master list of magazines so that it can be displayed more quickly later on. It's looking for the `type` value for the magazine to be in the following list: `[256, 512, 1536, 16]`.
> The default value for the PCML magazine seems to be `768`, or `3 * 256`. Which seems to exclude it from the master magazine list.
> 
> In addition (though I know it's not something with ACE itself), this seems to affect the CUP NLAW as well, since I imagine it uses the same value as the vanilla PCML.

Would you like to PR a fix?
