### ISSUE TITLE
Medical out of treatment range in helicopter

### ISSUE THREAD

**Issue by dedmen** [acemod/ACE3#6683]
**Arma 3 Version:** `1.84` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
- Tons more
```

**Description:**
- When flying in the back of a non-local helicopter and trying to treat others, You get spam of "XX is out of range for treatment" and half a second later he's in range again. And then suddenly out of range again. And in range again. And so on and so forth.
Don't know what code is used for distance checking. Maybe a additional check if in same vehicle as the other unit if getting out of range?

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- Irrelevant

**Comment by thojkooi** [comment]
This behaviour happens probably due to the caching we do for interaction conditions. 

https://github.com/acemod/ACE3/blob/69a3ae823ad8904e86f94d2b9750158160a3de6b/addons/medical/functions/fnc_canTreatCached.sqf#L25

> Don't know what code is used for distance checking. Maybe a additional check if in same vehicle as the other unit if getting out of range?

I haven't looked at the implementation yet, but this sounds like a good potential solution. Note that this isn't checked in the medical component, but I think it's a feature of the interaction menu framework. I couldn't quite find the checking for this in the interaction component though. Did we move parts of this to CBA already @acemod/maintainers ?
