### ISSUE TITLE
ace_advanced_ballistics.dll not installed even disable BE and server not using BE

### ISSUE THREAD

**Issue by JinougaF** [acemod/ACE3#6783]
ace_advanced_ballistics.dll not installed this kind of error pop everytime for some player on same server, I can confirm server do not enable BE and all players have their BE in Arma launcher disabled, and some player still have this error but other players do not have the error and can connect to server.

All players download the ace3 from steam workshop offcial pages and all checked that they have the dll files in there mod folder but still have this issue.

**Comment by commy2** [comment]
Needs RPT file.

**Comment by 3Mydlo3** [comment]
Our group had a problem like this with one player about a year ago I think. We struggled for several hours and came to the conclusion that ACE dlls were blocked for some reason. In the end the problem was caused by polish characters in Windows username. I'm not 100% sure that those were polish characters but it definitely had something to do with non standard characters in Windows username or some path.
