### ISSUE TITLE
Duplicate Kestrel

### ISSUE THREAD

**Issue by Cephel** [acemod/ACE3#680]
ACE3 Version: 4ef80ab3a333fd1e5ff6ba4b1f16f12b4ad01694

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
None

**Description:**
![](http://puu.sh/hgiPL/3248b6c146.jpg)

Classnames: `["ACE_Kestrel","ACE_Kestrel4500"]` via `items player`

Possible leftover from merger?

`ACE_Kestrel4500` seems to be the extensive (better) one.

They also both get their own entries in the interaction menu, with completely different functionality

**Steps to reproduce:**
- Start empty mission
- Place ACE miscellaneous items box
- They're both in there

**Where did the issue occur?**
Editor

**RPT log file:**
Doesn't really apply

**Comment by esteldunedain** [comment]
Yes, the left one comes from AGM/Bwmod and the right one from CSE/AB. The one from the left was already eliminated from the repo, but you must still have the ace_kestrel pbo on your folder.

**Comment by jaynus** [comment]
The text on the AGM one should really be ported...

**Comment by esteldunedain** [comment]
Yep, that text looked rad. It's a great font for the gps display too

**Comment by Cephel** [comment]
That was the issue, but I think this highlights a small problem with the way release version caching works. If you delete all the pbos that it generates, it won't make new ones unless you delete the cache files as well. It would be better if the make python script could somehow take care of deprecated addons, or you'd need to think about dropping that caching functionality

**Comment by Jastreb** [comment]
Got dupes of the right one in the action menu, one is clearly visible as one on the right, the other one is in place of the left one, but much lower and off the screen. 

Self interaction menu > Equipment > Open Kestrel
                                                       > Show Kestrel

I cant catch them both on screen though. They never are there, because one action terminates the other one, making kestrel disappear from screen.

http://www.dodaj.rs/f/1v/UY/hTfsbPG/arma320150417031506300.png
http://www.dodaj.rs/f/2G/dP/4VvQVWRK/arma320150417031526127.png

build e12831bee474814bee5fd4f02f4dc10a9ccb40b6

**Comment by esteldunedain** [comment]
> Got dupes of the right one in the action menu, one is clearly visible as one on the right, the other one is in place of the left one, but much lower and off the screen.

Those are NOT dupes. You can show the new Kestrel on two modes: maximized (with a cursor you can press the buttons with) and minimized (non interactive). I admit the actions names don't reflect that at all, so they should get rewritten.
