### ISSUE TITLE
Mine placement height is different for local and non-local mines

### ISSUE THREAD

**Issue by Tikkasd** [acemod/ACE3#6835]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- fnc_placeExplosive sinks mine based on digDistance, which causes mine to be invisible for all players expect placer on some terrains.

- Issue seems to be caused by line 77: _explosive setPosATL _pos. After testing setPos/setPosAtl only moves mine if mine is local, otherwise it has no effect.

**Steps to reproduce:**
- Place mine which is sink by digDistance on terrain which allows digging
- Arm mine
- Mine seems fine for placer, for other players mine is usually below terrain and completely invisible

**Where did the issue occur?**
- Dedicated

**Additional information:**
- Atleast ATMine_Range_Mag has this issue

**Comment by madpat3** [comment]
[https://github.com/acemod/ACE3/issues/6469](url)

**Comment by Snak3Doc** [comment]
Would still love to see this fixed, it makes mines (especially ap) unusable by players/friendly forces in ops just because of the visual disparity between the person placing them and other players.

**Comment by Saborknight** [comment]
We're finding the same things as noted in this and in #6469. We're also finding that the different maps make no difference, behaviour is the same. We've tested with the M15 AT Mine, M19 from RHS and also the APERS AP Mine.

Whilst the two AT mines go completely invisible (due to being below the level of the ground) but are still interactable to diffuse with ACE, the APERS mine has it's pressure plate only just visible, protruding from the ground. When done via Vanilla, only half the model disappears below ground.

**Comment by dedmen** [comment]
Should we not reopen #6469 and move convo to there? its the same thing?
Could be Arma MP bug, position might not be synched if difference is not big enough? in that case we could move the mine very far away, and then back to supposed position to force it to sync.
Needs MP testing and some manual labor if this is ACE or Arma bug.

**Comment by Nemesi-BDR** [comment]
Any hope or plan to have this issue fixed? I agree completely with the comment above, this issue makes mines unusable especially for TvT ops!
