### ISSUE TITLE
Improve flashbang effect

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#69]
bux578:
> IRL if you're hit by a military grade flashbang you'll suffer a (in germany called: h90/3 type) sudden hearing loss, serious loss of orientation and eye damage like if you'd do arc welding without a safety mask. This usually leads to two weaks of being unable to fight (with potential hospital stay). That wouldn't be much fun in arma ... so this needs to be balanced to still be fun.

Kristian/VKing
> Flashbangs should knock you out for at least long enough for someone to clear the room you're in
it really needs to be limited to Line of Sight, though
if there's someway to make it work, it should have a greater effect indoors, even if you don't see it, than outdoors

**Comment by esteldunedain** [comment]
Done in #418

**Comment by CG-Delta** [comment]
My experiment doesn't quite match what I read here. I'm thinking of one called 6-bang which I believe is the one linked here:
http://www.angelopodesta.com/documenti/07_d380e0111_6bang.pdf

> bux578:

> IRL if you're hit by a military grade flashbang you'll suffer a (in germany called: h90/3 type) sudden hearing loss, serious loss of orientation and eye damage like if you'd do arc welding without a safety mask. This usually leads to two weaks of being unable to fight (with potential hospital stay). That wouldn't be much fun in arma ... so this needs to be balanced to still be fun.

Apart from throwing it on room clearing exercise on various occasions, we did one time try it on our selves. 10 people cramped together in a small, dim room, normal clear goggles, double hearing protection and dropped one at our feet. Some had eyes closed some not, either way it is not something that will damage your eyes at all. More like if you're looking into a camera flash in a dark room, if you're looking straight at the thing. 
Thing is. When clearing a room you'll go in after the first bang (5 to follow). The people going in are not blinded. That would be impractical. As for hearing. You'll go in with hearing protection (which you use anyway) and that will drastically reduce it's effect.

> Pain would perhaps be appropriate if the flash bang explosion was close enough to a unit. Let's say within 1 meter? Once the medical system is more developed, we could even go for burn injuries.

About damage. Just no. At least the six bang I'm talking about. It has been jumping between our feet. Apart from pressure/sound shock there's no pain involved at all.

> Military grade flashbangs even contain a small portion of CS gas.

As mentioned before. You go in after the first bang. The CS will have no effect before you go it, and then you're standing in a cleared room with CS gas. So you force yourself to use gas mask. Masks are no good for fighting, let alone CQB. At least make sure you use gas effectively if you're using masks anyway.

Overwhelming loud noises should have a particular confusing effect (I'm told), especially if unexpected. But I don't think it would have a very good effect on a combatant, ready aiming at a door with hearing protection.

Finally I think all effects you give to a flash-bang, should also be given to a lethal hand grenade too, and more. Much more violent; sound, flash, shock and the lethal part.

Bear in mind that some of my disagreement may be because I'm talking about a six-bang and not a "one-bang".

**Comment by commy2** [comment]
This was closed five (5) years ago.
