### ISSUE TITLE
Magazine proxies 1.92 compatibility

### ISSUE THREAD

**Issue by cineafx** [acemod/ACE3#6973]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.0` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- [Update 1.92](https://dev.arma3.com/post/spotrep-00088) added magazineProxies to a few weapons. 
  - These new magazines are not avaiable in all guns. See example in *Steps to reproduce*.
- The `6.5mm Creedmor 30Rnd Mag` and `6.5x47mm 30Rnd Mag (HPBT Scenar)` magazines are available in the normal `MXM` but cannot be taken in the `MXM (Black)` or `MXM 6.5 mm (Khaki)`

**Steps to reproduce:**
- Start game with only CBA_A3 (or no mod at all) loaded
- Open Virtual Arsenal 
- All MX colours can now load all coloured magazines. 
  - [MX](https://user-images.githubusercontent.com/7873738/57029585-7d756e00-6c42-11e9-92ab-672b6ed704f2.png) 
  - [MX black](https://user-images.githubusercontent.com/7873738/57029639-9bdb6980-6c42-11e9-8496-68299dd58976.png) 
  - [MX khaki](https://user-images.githubusercontent.com/7873738/57029658-a8f85880-6c42-11e9-8c02-ea88072ee0c0.png)
- Start game with CBA_A3 and ACE3 loaded
- Open Virtual Arsenal (or ACE Arsenal)
- Some magazine variations are missing
  - [MX](https://user-images.githubusercontent.com/7873738/57029827-2c19ae80-6c43-11e9-8316-69c8d535f5d8.png)
  - [MX black](https://user-images.githubusercontent.com/7873738/57029873-43f13280-6c43-11e9-91e7-a29535044a8a.png)
  - [MX khaki](https://user-images.githubusercontent.com/7873738/57029897-553a3f00-6c43-11e9-8e78-3d1f9056c76b.png)

**Where did the issue occur?**
- Everywhere (Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal)

**Additional information:**
- n/a

**RPT log file:**
- n/a

**Comment by dedmen** [comment]
>Update 1.92 added dynamic magazines (proxies) to a few weapons.

Magazine proxies* no idea who came up with dynamic magazines stuff.

>These new dynamic magazines are not yet implemented into the current version of ACE

ACE didn't implement any magazine proxies so far

>CBA has already fixed this in their latest release

CBA doesn't either. I think you are mixing some things up here.

>This currently also prevents certain magazines added by ACE to be taken by the different coloured variants of a gun. 

That is magazine wells not proxies. Those are two completely different things.

Magazines missing in vanilla weapons is a CBA bug, not ACE.

**Comment by Blutze** [comment]
> Magazines missing in vanilla weapons is a CBA bug, not ACE.

A combination, actually. Its not missing, its being _overwritten_ by ACE:
https://github.com/acemod/ACE3/blob/master/addons/ballistics/CfgWeapons.hpp#L31

Back in https://github.com/CBATeam/CBA_A3/issues/1050, we decided to put the realistic "all mags, everywhere, including extended mags in subcarbines" line into ACE because CBA shouldn't have any balancing impact. Now that this interaction is already in vanilla anyway, the line can be removed.

But yeah, on the CBA/ACE code side this has absolutely nothing to do with proxies. Proxies are just the reason BI finally decided to move away from the split. As I predicted. Hah.

**Comment by cineafx** [comment]
Okay yea It seems I mixed / messed up the different things. 
So am I right to assume that the following 3 things are in no way directly related to each other?
1. The new magazine proxies.
2. Vanilla magazines missing from vanilla weapons.
3. Certain magazines not being available for different coloured variants of a gun.

I don't know if the new proxies are important / even need to be implemented into ACE.
But the other two seem like _normal_ issues. 

Should I edit this issue to represent the issue of vanilla magazines missing from vanilla weapons and create a new issue to reflect the last issue listed above?

**Comment by Blutze** [comment]
Ticket is mostly fine, no need to make a new one. Just streamline the description part into something along the lines of "new mags not available in all guns (ACE fault); 6.5 Lapua/6.5 CM mags not available in all guns (ACE fault)". Images are good.

Otherwise:
- **magazineWells** are about what mags can be loaded into which gun, implemented in a way that does not require loads of separate compat mods.
- **magazineProxies** are about where the model of the magazine hanging from the gun is defined - on the weapon class, or on the magazine class. This allows extended mags to visibly show on any gun (pending support), so that rules like FK's "less than 42 rounds" are enforcable without sacrificing realism.
- BI has updated the MX platform to support BOTH of those systems at the same time. Thats probably where most of this confusion comes from, but they are technically totally different systems.

Maybe we should get someone to make a long action Remington 700 model with scrim or a canvas bag around the action that we can use for all Advanced Ballistics Demonstration mags instead of jamming them into weapons where they don't belong.

**Comment by dedmen** [comment]
>its being overwritten by ACE

🤦‍♂  Yeah should definitely use += and not =. We have same issue in CBA.

>I don't know if the new proxies are important / even need to be implemented into ACE.

We would need to make our own models if we wanted proxies. Which we won't do.
