### ISSUE TITLE
How to remove mad rocking arms

### ISSUE THREAD

**Issue by Dyadka940** [acemod/ACE3#7127]
Please tell me how to remove the furious rocking arms??

**Comment by commy2** [comment]
?

**Comment by Blutze** [comment]
You know, that issue template is there for a reason. That being said:
- Do you have massive weapon sway because you are over 50 kilograms, or because you ran around on more than 30? Take a diet, take a break. A basic rifleman with LAT can be below 20 kg if you pay attention.
- Do you have massive weapon sway because you got shot in the arm? Find a medic who knows his stuff, or run [the splints mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1291442929) (be aware though that the upcoming medical rewrite will make that mod pretty much obsolete).
- If some of your players are expressing a reasonably decent taste in music, don't be [unrockbar](https://www.youtube.com/watch?v=EMddUlW4LXw).
- If you want to actually detach someone's arms from the model, that is not going to have anything to do with ACE3. Also, what the fuck.

**Comment by BaerMitUmlaut** [comment]
>If you want to actually detach someone's arms from the model, that is not going to have anything to do with ACE3.

I disagree, but it would belong into #3594.
