### ISSUE TITLE
Units too hard to kill with new medical system

### ISSUE THREAD

**Issue by Aphex123** [acemod/ACE3#7349]
**Mods:**
- Arma 3: `1.96.146114`
- CBA: `3.13`
- ACE3: `3.13` 

**Description:**
Units are too hard to kill with newest medical changes.
Body armor does not allow LARGE wounds to chest that are needed to kill when `Fatal Damage Source` is set to `Only large hits to vital organs`.
Leg and arm damage does not carry enough trauma weight so it can be very hard to kill when `Fatal Damage Source` is set to `Sum of trauma`.

**Steps to reproduce:**
**1:**
- Set `Fatal Damage Source` to `Only large hits to vital organs`.
- Shoot unit in body armor.
- ACE medical interact with unit to see no LARGE wounds on chest.

**2:**
- Set `Fatal Damage Source` to `Sum of trauma`.
- Shoot unit in arms and legs multiple times.
- ACE medical interact with unit to see many wounds but no death.

**Expected behavior:**
When shooting a unit in body armor there should be a chance of LARGE wounds, especially after multiple hits.
Multiple large wounds to arms and legs should kill unit.

**Where did the issue occur?**
- Editor (Singleplayer)

**Log Files:**
- https://pastebin.com/DaW8hY3X

**Screenshots:**
After firing 10 rounds into back armor of Blufor unit with 6.5mm rifle round at point blank range.
https://i.gyazo.com/6721ce2a087da72170c3a79f292f6350.png

**Comment by mharis001** [comment]
What are the values of the `fatalInjuriesPlayer`, `fatalInjuriesAI`, `AIUnconsciousness`, and `cardiacArrestTime` settings?

**Comment by Aphex123** [comment]
`fatalInjuriesPlayer` = Always
`fatalInjuriesAI` = Always
`AIUnconsciousness` = true
`cardiacArrestTime` = 30 seconds

Additional and maybe i should add to OP.
When `FatalDamageSource` is set to `SumofTrauma` then `criticaldamagethreshold` seems to have no effect. Even when `criticaldamagethreshold` is set to 25 (max). There is no noticeable difference in number of hits to legs needed to kill as i believe is not intended.

**Comment by SilentSpike** [comment]
We could tweak
https://github.com/acemod/ACE3/blob/c7f58c183245fe7e25f639621602fb4bf85e2661/addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf#L99
which is used to scale wound size based on incoming damage

**Comment by SilentSpike** [comment]
@Aphex123 It would be good to clarify because you mention two separate systems here, is the issue that:
1. Units aren't bleeding out fast enough - which is tied into wound sizing received
2. Units aren't taking fatal damage (immediate death on being shot) - which is not tied into wound sizing

**Comment by Aphex123** [comment]
@SilentSpike Ill address `OnlyLargeHitsToVitalOrgans` and `SumOfTrauma` seperatly as it looks like they use two different systems and problems.

`OnlyLargeHitsToVitalOrgans`:
With a vest equipped, no shots are passing through the vest and causing LARGE wounds. There are only small to medium wounds that cause bleeding. This doesn't seem right to me. There should be a small chance of a round causing LARGE wounds. And medium wounds should also have a chance of stopping the heart through concussive forces.

From speaking to some that know coding better than me it looks like damage to chest must pass a certain threshold before going to a random check for heart failure. But with a vest no damage is high enough to go onto this random check. A point blank rifle round should pass this damage threshold. This is form others looking at `determineIfFatal` function so forgive if wrong.

`SumOfTrauma`
From the name of this setting it would seem that enough wounds over the whole body regardless of bleeding would cause death. But in testing a unit took 60+ rounds to arms and legs without dying. Arm and leg damage should count more towards the sum.

It looks like the intent of the new medical system is to make bleeding out and cardiac arrest the new standard way of dying but i dont believe that is within the scope of arma. If a unit receives enough damage that they will be passed out or tied to a medic for life support the rest of mission than they should just die. Maybe make a unit lose blood immediately upon hit and put it in addon settings.

**Comment by severgun** [comment]
> It looks like the intent of the new medical system is to make bleeding out and cardiac arrest the new standard way of dying but i dont believe that is within the scope of arma.
So may be just blood loss should be increased/multiplied by every hit?

**Comment by SilentSpike** [comment]
From your response it seems to me like this feedback is concerning lethal damage - and you're right, the difference between sum of trauma and organ damage basically comes down to lethal damage as a result of multiple damage events versus a single damage event.

The sum of trauma behaviour you describe sounds unintended as it should serve to fill the role of killing the unit when bloodloss alone isn't enough and they're sustaining lots of damage (as you expected). If the setting to tweak that isn't working as expected then that would be the priority here because fixing it allows that to be tweaked to your liking and then for us it's a case of finding a good default.

We can also look at tweaking the threshold for lethal damage of a single damage event to the chest. The problematic thing here is that different equipment seems to produce quite different engine damage values (especially when you start mixing in addon units and weapons).

I should make clear, that wound size isn't related to lethal damage at all. Both are based on the incoming engine damage, but there is no cause and effect as far as the code goes (I could tweak the numbers to always produce large wounds, but you'd still see the same lethal damage behaviour because it's a separate evaluation).

There's also no chance element in wound sizing (beyond built in variation from engine damage) unless you receive many wounds from a single damage event - where successive wounds have the chance to become increasingly worse:
https://github.com/acemod/ACE3/blob/c7f58c183245fe7e25f639621602fb4bf85e2661/addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf#L102

If there are issues with the wound sizing, I'd suggest making a separate issue for that to keep feedback for the two systems from mixing.

**Comment by Bummeri** [comment]
I am confused, Is ```SumOfTrauma``` supposed to kill if you get multiple small hits to hands and legs? Or is it supposed to kill if you get multiple small hits to torso and head? Or is it supposed to kill if you get multiple small hits anywhere?

**Comment by Aphex123** [comment]
@SilentSpike 
>  If the setting to tweak that isn't working as expected then that would be the priority here because fixing it allows that to be tweaked to your liking and then for us it's a case of finding a good default.

After reading the description of `criticalDamageThreshold` it seems that setting just affects when a unit goes unconscious. There seems to be no setting to adjust how much trauma is needed to kill. That was a misread on my part.
</br>
> We can also look at tweaking the threshold for lethal damage of a single damage event to the chest.

I think making that on a slider in addon options would be very good.
</br>
</br>
I believe the solution is to make a slider for `SumOfTrauma` that is needed to kill, and another slider to adjust lethal damage threshold. Maybe another for `BloodLossOnHit` or some other.
Perhaps it would be possible to create a small chance that damage to chest might get multiplied to simulate a plate failure. I know its (impossible?) to decrease a plates effectiveness over hits so this might be a work around.
Anyway more settings would be good all around. Thank you for your response

**Comment by Steve161st** [comment]
Sum Of Trauma seems to have an odd effect on AI. When we use this setting, it seems the AI never pass out through pain. (Players still seem to behave relatively normally.) With this setting turned on, putting an entire 5.56x45 round STANAG into an AI's knee leaves them bleeding but functional.
Changing this setting to Only Large Hits to Vital Organs and leaving all other settings the same, AI pass out from pain within 2-5 shots to the knee cap - so a much more expected result.
(Both settings tend to result in players losing consciousness in 3-6 shots to the kneecap.)

So I think this does suggest that the Sum of Trauma is not working as expect.

**Comment by JinougaF** [comment]
> Sum Of Trauma seems to have an odd effect on AI. When we use this setting, it seems the AI never pass out through pain when hit in the limbs. (Players still seem to behave relatively normally.) With this setting turned on, putting an entire 5.56x45 30 round magazine into an AI's knee leaves them bleeding but functional.
> Changing this setting to Only Large Hits to Vital Organs and leaving all other settings the same, AI pass out from pain within 2-5 shots to the knee cap - so a much more expected result.
> (Both settings tend to result in players losing consciousness in 3-6 shots to the kneecap.)
> 
> So I think this does suggest that the Sum of Trauma is not working as expect.

so basicly the only way to directly kill AI is shot in head or torso? By directly kill i mean they will not entering the unconsciousness stage but directly go to die stage and leave a body without ragdoll pshysic there.

**Comment by Ivanowicz** [comment]
@Steve161st That is quite bizarre. I was doing some testing in editor and got the exact opposite results - terminators on "Only Large Hits to Vital Organs", and relatively normal on "Sum of Trauma". Though, that's another reason for explanation of those settings - I don't think anybody aside from the devs knows what they do.

Another thing I just realised while double checking - it seems that it is RHS that does not work well with new medical system - 5.56 and 5.45 can not penetrate pretty much any standard armored vests, so you're left playing a zombie game, since headshots are the only reliable way of killing anyone (shooting the vests only leaves lots of bruises and *really* small avulsions). The vanilla weapons seem fine. Is that issue something that falls under ACE compatibility modules, or on RHS side?

**Comment by AdlofHilder** [comment]
@Ivanowicz 
`it seems that it is RHS that does not work well with new medical system - 5.56 and 5.45 can not penetrate pretty much any standard armored vests, so you're left playing a zombie game, since headshots are the only reliable way of killing anyone (shooting the vests only leaves lots of bruises and really small avulsions). **_The vanilla weapons seem fine_**. Is that issue something that falls under ACE compatibility modules, or on RHS side?`

I have been testing weapons on variations of armoured vests for hours tonight - I can confirm the weapons all suffer from the same problem modded or not -- There seems to be an issue instead with the way that some rigs are blocking almost all damage rather than the weapons -- If your interested I have an example in #7539 which goes through one example

**Comment by jonpas** [comment]
Requires evaluation if it still happens after some other changes (damage assignment to hitpoints).

**Comment by Ebolavector** [comment]
Still have the same problem here. And no action at all for the "DamageThreshold" sliders. 0.01 in the sliders has exactly the same effects than 25. 3/4 5.56 hits on the torso to kill or go unconscious with a body armor depending on the unconscious state parameter with a vest...

**Comment by bulg4kov** [comment]
Is there any fix on march 2022?

**Comment by baranelitez** [comment]
i can confirm this is still an issue in april 2022.

**Comment by DJ-Reticuli** [comment]
The fact that body armor is not degrading with 300 rounds fired into it is obviously an issue.

If Either is selected so that both Large Hits to Vital Organs & Sum of Trauma can cause an instant fatality besides just cardiac arrest bleed out, then I'm wondering if perhaps that would fix it.  When I'd previously tried Sum of Trauma, I think it was more of the bad stock Arma 3 instant fatalities from just rapid fire into someone's leg.  Certainly 300 major bruises to the chest should be fatal, though.  Heck, a fraction of that should be fatal, and the armor should have failed long before.  Lvl 4 body armor can take a couple spaced 7.62 NATO rounds, but that doesn't mean it's going to make it through an entire belt from an M60 or even three hits to the same spot.  Long before the end of the belt, the energy transfer would cause massive internal injuries even without penetration.  

At the other extreme, though, we certainly don't want that stock Arma 3 behavior of unloading into someone's leg causing an instant fatality.  If Sum of Trauma triggers fatality at the moment that Vital Organs (& cardiac arrest) Only's total non-vital-organ damage would simply cause non-temporary unconsciousness, then you're still left with the issue that massive torso bruising is not treated as a serious enough injury compared to, say, unloading an entire mag in someone's leg, which should mostly only be an issue as a result of reduced mobility, high pain causing temporary unconsciousness, and blood loss.  Massive bruising is technically a form of internal bleeding, right?  I like having blood loss rate tuned way down, so I'd rather not have to crank that up to cheat my way out of these issues.

My other issue, though, is that when I'm down, the AI doesn't run over and necessarily target my head, rather they continue to aim for center mass point blank even if that's been previously ineffective.  I seem more likely to get hit in the head when I'm further away, I guess as a result of aiming inaccuracies.

Edit: 

I've been doing some experiments.  While I can't confirm temporarily passing out is working yet when Either is selected (it definitely works when Vital Organs Only is selected and pain coefficient is up), I can say that about 15 medium chest bruises or 30 minor bruises causes an instant fatality from Sum of Injuries with the damage threshold setting at the default 1.0.

Edit:

With same settings, without penetration of the armor or excessive loss of blood, 5 or so large torso bruises with one or two minor or medium bruises appears to cause instant fatality .  I can also confirm that with elevated pain coefficient, passing out temporarily does appear to be happening with the AI.  I also shot someone up in the arms and legs while they had tunicates on, and no amount of damage to the limbs caused Sum of Injuries effects, which is good, even though mobility was not reduced quite as much as I liked.  They did tend to drop down at least once while awake, and the other time at least once temporarily due to pain unconsciousness effects and then wake up.  Making it so they could only walk and limp with broken bones at least helps, though.

It might be useful to have another slider for non-temporary unconsciousness (until third-party medical assistance), though, so you can get both instant fatality from Either Sum of All Injury or Large Hits to Vital Organs, but also get the semi-permanent pass out phase that requires medical help.  That of course would be separate from the temporary pain threshold passing out.  Having to choose between pass out until cardiac arrest from blood loss or a point-blank vital organ hit, or alternatively just a fatality at that same point is a big thing to ask.  Why not both?  It'd be better to allow three phases:  temporary passing out that can happen repeatedly, extended passing out until external medical help, and then fatality until CPR, each with their own thresholds and sliders.

Edit 8/21/2023:

I analyzed the armor and ammo results, but forgot to post a link in this thread...

https://steamcommunity.com/sharedfiles/filedetails/?id=2868465442

People also need to ensure they aren't using PiR, bCombat, Dagger's ammo, or ZluskeN Modified Loadouts, as they each break new ACE injury detection.  If you notice massive issues compared to what I describe in my guide and, for instance, have headshots registering on chest plates, then start eliminating mods to narrow down what's causing it.  Another good test is to unload a mag in someone's leg and then put a tourniquet on it, which should allow them to survive.  Please post to inform others.

**Comment by Mike-MF** [comment]
There's a setting for how much damage units need to take for death. 
`ace_medical_AIDamageThreshold` tweak it to your liking.

**Comment by DJ-Reticuli** [comment]
Yes.  With ACE Armor Adjuster...

https://steamcommunity.com/workshop/filedetails/discussion/2849354160/3817418065222639018/

...I have put the ACE Medical threshold back down to 1 for me and others, and set fatal immediate injury cause to Both, as well as various other tweaks to my liking like blood loss rate to 0.5, pain intensity up, and speeding up various tasks.  I have put Surgical Kits (made reuseable) and especially Personal Aid Kits (made consumable) up in time required, both also requiring medics to use.  It allows you to immediately defeat adversaries without significant body armor even using pistols and SMGs, but still benefit from protection if armored.  Without Both selected, it was taking several pistol shots to the chest to drop someone in their underwear.  You do need to eventually make use of PAKs, though, because even a dozen significant bruises can eventually cause fatality otherwise.

Death & Hit Reactions and Advanced Wound Reaction are also beneficial, but the former seems to cause you to go prone every time an explosion goes off on another floor, and the latter seems to be causing issues with not allowing blood loss to cause cardiac arrest.  Prior to a grenade detonating, go prone.  With Both selected, you're also more likely to die of combined wounds or someone finishing you off with a head shot, but it is a minor annoyance & anomaly when cardiac arrest fails to occur with blood loss.

**Comment by Mike-MF** [comment]
No, not with ACE armor adjuster. With that one setting which controls how much damage AI will take before they die.

**Comment by DJ-Reticuli** [comment]
Yes, but if you put that ACE medical threshold down to 1 and set fatal injuries to Both, you need to buff the messed up ACE body armor somehow to compensate.  People raise that threshold in order to deal with the poor body armor, but now with this combination it's mostly positives and few negatives.

**Comment by DJ-Reticuli** [comment]
For Ace Armor Adjuster, 18 threshold keeps a tactical vest and Kevlar fatigues combo in sub level 3 or about 3A+and still not able to handle most rifle rounds, and 36 is a good spot for the buffing of the chest, diaphragm, and abdomen.  I don't enhance other areas.  Some might feel that 34 is enough, though, and may want many of the adversaries that double up on soft armor to get a buff that necessitates higher power rounds like 308, 6.8 sig, 8.6 blk, and beyond, in which case 17 will do the trick for threshold.  In real life, though, two 3A soft layers do not equal full 3.  There don't seem to be many mods that make the enemy a near peer, though, so if you do want that, 17 works, otherwise 18.
