### ISSUE TITLE
AI not taking fatal damage from limb shots regardless of settings

### ISSUE THREAD

**Issue by Brumes-Wolf** [acemod/ACE3#7358]
**Mods (complete and add to the following information):**
- **Arma Current Stable [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.13.0` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.13.0` [eg. 3.0.0 stable, commit hash]
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
AI does not die from limb shots, only goes into unconscious state

https://youtu.be/UdF9xk6dfPo

**Steps to reproduce:**
Follow steps from video

**Expected behavior:**
AI to die after a certain amount of total damage is reached

**Where did the issue occur?**
- Editor SP/SP

**Log Files:**
https://pastebin.com/LECt0VC3

**Additional context:**

**Screenshots:**

**Comment by BaerMitUmlaut** [comment]
This is intentional. There are no vital organs in your limbs.

**Comment by Brumes-Wolf** [comment]
Then either sum of trauma setting does not work, or should have a different name\better explanation. I interpret sum of trauma as taking all damage both limb and vitals and causing instant death when a limit is reached, this currently does not seem to be the case. There is no difference in this behavior with the different settings. 60 shots to a limb should be a kill, not merely unconscious.

**Comment by PabstMirror** [comment]
We could add a setting to count limb damage,
it would be closer to vanilla medical

**Comment by Brumes-Wolf** [comment]
> We could add a setting to count limb damage,
> it would be closer to vanilla medical

Out of curiosity, what does sum of trauma actually do then?

**Comment by Dave247** [comment]
> We could add a setting to count limb damage,
> it would be closer to vanilla medical

I think this would be a really good idea to enable people to better customise their settings to work the way they want them to, as well as helping to bridge the gap between Medical before and after the rewrite.

Say in the example that two squads of infantry are engaging each other over a long distance, it takes a lot longer to down any units as you would have to hit them in either the head or chest.
To compensate for that the unit I play with has opted to raise the rate of blood loss and the transfusion to be rather high so you don't end up with really long and prolonged firefights.

**Comment by Brumes-Wolf** [comment]
This behavior is still present after the most recent update and preventing us from using the live version of ACE, it would be very nice if this was adressed.

**Comment by Brumes-Wolf** [comment]
I was doing some more testing related to this recently, and I was wondering if there is anyone that can explain to me what the "sum damage" or "either"/"only hits to vital organs" settings actually do, because they seem to have no effect at all. 
I haven't been able to find any documentation related to this.

**Comment by bux** [comment]
https://ace3mod.com/wiki/feature/medical-system.html#1114-fatal-damage-source

**Comment by BlackAlpha** [comment]
I want to support what Brumes-Wolf said. There is something wrong since the medical rewrite. People are mentioning bullet spongy enemies every mission. I'm guessing it might be related to sum damage not working as intended. Nevermind the unconscious soldiers, it happens with conscious soldiers too.

What happens is:
- People shoot an AI soldier 10+ times.
- The AI soldier shoots back and kills a player.
This happens often. The main problem is that the AI can still fight back effectively even though they got hit 10+ times on arms/legs.

I did some testing in the editor with just ACE. I placed some NATO riflemen and shot them in the arms/legs. On average it takes 8+ shots to down a soldier (to make them fall over, be combat ineffective). But often it takes 12 to 15. Meanwhile, shots to body armor take 1 or 2 shots. That's backwards. The AI damage threshold doesn't seem to do anything. Neither does the fatal damage source. Whatever setting is used, it still often takes 12+ shots on arms/legs to down a soldier.

Expected behavior would be that a soldier should fall down much quicker (or alternatively, a soldier should incur an extreme accuracy penalty). Sum of trauma should take care of that, no? Right now, a conscious soldier can take a lot of wounds and still remain conscious. This makes me think that sum of trauma isn't working properly.

**Comment by sam11hamilton** [comment]
Exact same issue here. Only 1 shoot in a Heavy Chest for exemple. In Arms/legs sometime 5 shoot, sometimes more than 1Mag of 30round. So Ok arms, and leggs are not vital... But when you receive 5shoot on your leggs... :) I so several report here older than 1Month, and for the dev its seems to be "normal"? Please.

**Comment by Dudejo** [comment]
Perhaps fractures should have a random chance to spike pain and, therefore, knock out the target.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
