### ISSUE TITLE
People don't wake up from unconsciousness

### ISSUE THREAD

**Issue by Brumes-Wolf** [acemod/ACE3#7378]
**Is your enhancement related to a problem?**
Unlike before the rewrite people/AI seem to never wake up on their own, and also seem to go uncon quite easily

**Solution you'd like:**
A setting or toggle that allows people to wake up when they are not stable.

**Additional context:**
For a small non milsim group having people be forced to respawn as soon as they go uncon is not very fun nor good gameplay. The previous system of people waking up on their own if they weren't very damaged worked better for this use case.

**Comment by Bummeri** [comment]
Can you adjust the  "seem to go uncon quite easily" by adjusting this setting?
![Uncon set](https://i.imgur.com/HBIYero.png)

Does the epipen not help with the chance of waking up? Especially if you adjust this setting higher?
![Epi set](https://i.imgur.com/Rio4epD.png)

**Comment by Brumes-Wolf** [comment]
I adjusted the unconsciousness  wake up chance to 1.0 and people still did not seem to wake up. I have not tried changing the pain coefficient yet, nor did I change the Epi wake up chance. I will try these sometime soon.

But my main request here is for people to be able to wake up on their own without help from others. so epipens aren't relevant to that.

**Comment by Bummeri** [comment]
> I adjusted the unconsciousness wake up chance to 1.0 and people still did not seem to wake up.

I guess the unit cannot wake up since it:
- Is bleeding still too much
- Has lost too much blood
- Is in too much pain

I dont think bleeding slows on its own?
Does pain go down on its own?

It might be that the system does not permit any random wakeups if nothing is made to assist the uncon unit?

**Comment by Brumes-Wolf** [comment]
> > I adjusted the unconsciousness wake up chance to 1.0 and people still did not seem to wake up.
> 
> I guess the unit cannot wake up since it:
> 
> * Is bleeding still too much
> * Has lost too much blood
> * Is in too much pain
> 
> I dont think bleeding slows on its own?
> Does pain go down on its own?
> 
> It might be that the system does not permit any random wakeups if nothing is made to assist the uncon unit?

What I meant is that previously units could randomly wake up without assistance if they were hit only a few times and didn't lost too much blood previously. I would like a settings to return this behavior to the rewrite version

**Comment by dedmen** [comment]
I think the default random wakeup chance is too low?
With advanced medication you seem to basically have to wait for it, and it has only a 5% chance, checked every 15 seconds.
you can give epi, but epi boost by default is 100%, so.. none.

just tried on an AI, bandaged all wounds, no pain, full blood, epi in system, pulse 70, no wakeup.
increased wakeup chance from 5% to 50%., woke up after ~20 seconds,

But pushing the wakeup chance up, works for me.

**Comment by Brumes-Wolf** [comment]
With wakeup chance at 1.0. People still don't wake up on their own. But i am talking about people who are NOT stable. So they have not been bandaged or given blood or given epi. In the old system those people would wake up on their own, now they don't.

**Comment by Rod6er** [comment]
I will add to this that over a few hours of playtime with our group, there was not one instance of spontaneous waking up as was the case before...this means that as people start to go down, and with the new procedures to wake people up taking more time rather than being able to force lightly wounded persons up with a shot of epi, it started a death spiral and we were always overrun...

TBH I think we are going to simply downgrade ace until there are better parameters to control the medical rewrite because this is unplayable for small group sizes with only one or two medics.

**Comment by Brumes-Wolf** [comment]
We have no medics, means everyone just force respawns when they get knocked. We already downgraded because of the many issues there are now.

**Comment by commy2** [comment]
I think "Epinephrine Increases Wake Up Chance" is a multiplyer.
This is why range is 1-30.

If your base chance ("Uncon Wake Up Chance") is 10%, you want the multiplyer to be 10x.
10%*10 = 100%.

**Comment by Rod6er** [comment]
We've got it set to the max (30).

**Comment by Brumes-Wolf** [comment]
Regardless my suggestion/request has nothing to do with epinephrine. My request is for a toggle allowing people to wake up without any help or treatment, like in the pre rewrite system.

**Comment by psYGer** [comment]
It would perhaps help if you had an untreated multi in addition to the existing epi multi. So everyone can set it according to their own preferences.

As an an example:
chance to wakeup 0.05 (5%)
epi given multi of 5.0 (25%)
untreated give multi of 0.2 (1%)

The new multi should then have a range between 0 and 1.

**Comment by DylanFrese** [comment]
Using the function `ace_medical_fnc_setUnconscious` I can set myself unconscious, and then wake myself up. I will also wake up according to the spontaneous chance set in the settings. However, if I get shot, I will not wake up on my own and trying to use this function does nothing, despite returning `true`.

I would *guess* this is related; whatever normal mechanism there is for forcing a unit unconscious or awake is bypassed when falling unconscious immediately due to shock. But I'm not certain what's actually going on.

**Comment by Bummeri** [comment]
This issue stems from the following:

1. No amount of Pain actually causes uncon. Never.
2. Enough bleeding does, but since bleeding is ongoing while uncon, it wont let spontaneous wakeup to happen.
3. Blood loss does cause uncon. But since blood does not replenish, no spontaneous wakeup will not happen.

**Comment by commy2** [comment]
You answered a one year old resolved issue...

**Comment by Brumes-Wolf** [comment]
Closed: Yes, Resolved: no. As far as i'm aware there has been no mention of a fix in the changelogs, although I haven't tested it in a while since we don't use regular ace anymore because of issues with the new medical system.

**Comment by Bummeri** [comment]
> You answered a one year old resolved issue...

Well the initial text is talking about being able to regain consciousness on your own. Currently that will not happen. Some treatment needs to be done to you. I do not think this issue is resolved. The discussion went off in the direction of fixing issues with waking up when stability was regained by treatment. That is another issue.

The new medical does not permit gaining consciousness on your own if you have nothing done to you. That is the behavior OP was looking for I believe. 

And that issue stems from the points I laid out:

1. that no amount of reachable pain will put you uncon. Since pain is the only value that does ease on its own. But since pain is not a factor in becoming conscious, it does not matter.
2. Bleeding enough can make you uncon but it will not get better on its own so no getting back up if you are bleeding too much
3. Having lost enough blood makes you go uncon, but it will not get better on its own so no getting back up.


Here are the factors that make you become conscious again:
https://github.com/acemod/ACE3/blob/c44360bd19bafc773324df1b082aac3904268144/addons/medical_status/functions/fnc_hasStableVitals.sqf

**Comment by Bummeri** [comment]
To elaborate on the thinkin related to pain and its effects. It think the route to uncon goes like this:

1. You get hit and receive some pain yet it is unlikely to be more than threshold: https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf#L202-L204

2. If it is larger than the threshold, it is unlikely to lead to anything:
https://github.com/acemod/ACE3/blob/master/addons/medical_damage/functions/fnc_handleIncapacitation.sqf#L35-L37

3. If it leads to anything it is likely that you are fucked anyway. But if pain is the biggest factor, then you get thrown into the statemachine state "Unconscious": https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_statemachine/Statemachine.hpp#L12-L15

4. From that state you are automaticaly thrown to injured state because pain level is not prerequisite for staying unconscious:
https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_statemachine/Statemachine.hpp#L51-L55

https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_status/functions/fnc_hasStableVitals.sqf
