### ISSUE TITLE
General suggestions for the reviving functions

### ISSUE THREAD

**Issue by LockAndLoafCat** [acemod/ACE3#7458]
**Is your enhancement related to a problem?**
Currently, there are a few "issues" with the new medical system. Firstly, people almost always have no heartbeat when they are knocked unconscious. This, as well as being confusing, is also unrealistic. Secondly, epinephrine's new function seems out of place and jarring. I've played a good amount of hours with the new system, both in large-scale long-term ops, as well as shorter purely mission-based ops. Allow me to suggest a few changes that I personally feel would benefit the system.

**Solution you'd like:**
1. Being knocked unconscious should, more often than not, set your heart rate to a very low bpm, not no heart rate. This will ensure players are not performing CPR on someone who has been shot in the arm a few times (this issue seems to be a result of fatal injury, I think the system needs some tweaking).

2. Epinephrine should return to a system similar to its previous function, in which it is purely there to raise the heart rate and act as adrenaline. The system of adrenaline being an interval check for regaining consciousness sounds good in theory, but in practice is very annoying. I'm not certain, but I'm pretty sure this is why the perfect health unconscious state is occurring (aka. patients having an 80bpm and perfect blood pressure with no un-bandaged wounds remaining unconscious).

3. CPR needs to be addressed. This was discussed in a previous thread ([https://github.com/acemod/ACE3/issues/7434]) and the conclusion was that the current CPR system is working as intended, but perhaps needs tweaking. From experience, CPR should only return the heart rate to a bpm of 20-30. It should then look at blood pressure and pain levels, then slowly rise to a sustained level overtime. Consciousness should return at 40-45.

4. Regaining balance and becoming alert upon revival. Even after regaining consciousness, players can immediately jump to their feet as if nothing happened. This is fine gameplay wise, but I'd like a toggle option to enable a system in which players move slowly for a few seconds upon revival, simulating one trying to regain their bearings. I used to faint quite often when I was younger due to a condition and despite being fine upon waking up, I would need to sit for a second or two before I could stand properly.

**Alternatives you've considered:**
My first point seems more like an unintentional result of the code and is maybe down to just needing a small tweak. I feel like fatal injury should bypass the unconscious state and just kill you.

The second point is the main issue from my experience. Adrenaline should be used after successful CPR to boost one's heart rate back to a higher bpm. With such a system, adenosine becomes even more crucial, as injecting epinephrine without checking could really cause the heart rate to go far too high.

CPR again, I think this just needs some small tweaking to be fine.

The fourth point I raised may seem controversial, and it's not necessarily game breaking not having it, I just feel it'd be a welcomed addition.

**Comment by Grezvany13** [comment]
1. The question is; why did someone fall unconscious? Is it because of high pain levels? Or because of low blood pressure / cardiac arrest?
I would say, by default, someone who gets shot is in so much pain he/she passes out, which (due to pain) actually raises the heart rate, up to a point the heart stops and CPR is required. The moment blood loss is increasing, the state should be based on the amount of blood in the system (which is also tied to cardiac arrest), and requires CPR to keep someone alive.
I agree that a single shot to the arm or leg shouldn't be a fatal injury, unless untreated for a longer time.

2. Epinephrine = Adrenaline, and raises the heart rate (and can even restart the heart after cardiac arrest). Although it can also trigger the brains to wake up and gain consciousness again.
However it's very short lived and it's a "work now, or not" case. It doesn't solve anything, it just boosts things.

3. After reading the mentioned issue, here's my take on a possible fix:
CPR itself should only elongate the cardiac arrest timer (aka death timer) of the patient, but have a (high) chance of returning a (low) heart beat when the amount of blood is capable of handling itself.
After that the body should recover itself again (heart rate and blood pressure) based on pain levels, running IV's and given medication.
When all stats are in normal range again a high chance of gaining consciousness should occur.

4. I like the idea of temporary disorientation after a massive trauma. A "simple" timer could running after being unconscious (and depending on amount of trauma) which forces a player to only walk, have increased fatigue or having the change to fall down when running (similar to low blood levels).
However Epinephrine can shorten the timer due to the increased amount of adrenaline in the system.

In the end; ACE is making Arma more realistic, but without being TOO realistic (aka spending 3 months in a hospital after getting shot in the head).

**Comment by LockAndLoafCat** [comment]
> I would say, by default, someone who gets shot is in so much pain he/she passes out, which (due to pain) actually raises the heart rate, up to a point the heart stops and CPR is required. The moment blood loss is increasing, the state should be based on the amount of blood in the system (which is also tied to cardiac arrest), and requires CPR to keep someone alive.

Definitely, however, this seems to simply occur everytime without fail. I think the biggest issue is that people don't want to set headshots to insta kill you, because the AI aim is so unpredictable, especially with this issue - ([https://github.com/acemod/ACE3/issues/7391]). 

> However it's very short lived and it's a "work now, or not" case. It doesn't solve anything, it just boosts things.

This is my issue, adrenaline should be "now or not" case. The issue is that is not how it currently functions in ACE.

> After reading the mentioned issue, here's my take on a possible fix:

This sounds like a good solution to me.

**Comment by SilentSpike** [comment]
> My first point seems more like an unintentional result of the code and is maybe down to just needing a small tweak. I feel like fatal injury should bypass the unconscious state and just kill you.

If this is the result of fatal injury like you say, there are actually settings to control that (analogous to the old prevent instant death stuff):
https://github.com/acemod/ACE3/blob/3a65a73e945480b342d1a5c7cbb244114a6ba3d0/addons/medical_statemachine/initSettings.sqf#L1-L25
When set to:
1. "always" a fatal injury instantly kills
2. "in cardiac arrest" means you take 1 and go into cardiac arrest and if you take another while in cardiac arrest you die
3. "never" just means they can only put you into cardiac arrest and not kill you

**Comment by JinougaF** [comment]
> > My first point seems more like an unintentional result of the code and is maybe down to just needing a small tweak. I feel like fatal injury should bypass the unconscious state and just kill you.
> 
> If this is the result of fatal injury like you say, there are actually settings to control that (analogous to the old prevent instant death stuff):
> https://github.com/acemod/ACE3/blob/3a65a73e945480b342d1a5c7cbb244114a6ba3d0/addons/medical_statemachine/initSettings.sqf#L1-L25
> 
> 
> When set to:
> 1. "always" a fatal injury instantly kills
> 2. "in cardiac arrest" means you take 1 and go into cardiac arrest and if you take another while in cardiac arrest you die
> 3. "never" just means they can only put you into cardiac arrest and not kill you

so this is the clear explaination, never is working like the old prevent instant death, but still it could not be a hard confirm that you will never go die, you still gonna die if other condition meets, like bleed out, am I correct?

**Comment by SilentSpike** [comment]
@JinougaF When set to never you enter cardiac arrest and so will die after the cardiac arrest timer runs out (if untreated). You can still enter cardiac arrest as a result of bleeding out if you take non-fatal injuries. Then obviously there is also the option to turn off fatal injuries completely so you can only take non-fatal ones.
