### ISSUE TITLE
Viewdistance stuck on video settings only

### ISSUE THREAD

**Issue by CPTMiller** [acemod/ACE3#7611]
**Mods:**
- **Arma 3:** `1.96 stable`
- **CBA:** `3.14.0.200207`
- **ACE3:** `3.13.1` 
- **ACEX:** `3.5.1` 

**Description:**
ACE Viewdistance with video settings on, ignores viewdistance slider settings.

**Steps to reproduce:**
Set ACE viewdistance on foot/in land vehicle/in air to video settings.
Change the viewdistance slider either in vanilla or ACE, and see that it doesnt do anything.

**Expected behavior:**
The viewdistance would change based on your desired settings.

**Where did the issue occur?**
- Dedicated

**Log Files:**
- https://pastebin.com/5wjxBa6N

**Additional context:**
Steps to solve the problem
Set ACE viewdistance on foot/in land vehicle/in air to 10000
Set view distance slider to 10000
Then set it down to preferred distance.

**Screenshots:**
N/A

**Comment by dedmen** [comment]
Same issue on my server, but we have ACE viewdistance disabled, we couldn't find any reason and don't have any other limiting mods.

But thats off the point, your report is not following the issue template, please edit it to follow and add all the requested details to it, otherwise it might be closed as invalid.

**Comment by CPTMiller** [comment]
Ive changed it, but I dont have any logs for it tho. I can reproduce the bug every single time with these mods launched.

**Comment by commy2** [comment]
Reproduce with just CBA and ACE and upload the RPT file.

**Comment by CPTMiller** [comment]
Done.
