### ISSUE TITLE
ACEX headless limit removal

### ISSUE THREAD

**Issue by tapasje** [acemod/ACE3#7627]
Currently "_HC1" to "_HC3" are hard coded into ACEX headless, but could you rework it to have as many clients as you want? Or at least up 'till 5? It'd be a nice feature enhancement, as for someone who has the hardware to run it (recent availability of affordable multi-core Ryzen processors for dedicated servers) and the requests to have more units present on the map at any given time.

Apologies if this is a known barrier - I have little understanding of the ArmA scripting language and environment)))

**Comment by jonpas** [comment]
System is based on round-robin between 1-3 headless clients. Accepting PRs to rework that for more if wanted. Testing has shown that more than 3 is either not worth it or even has negative impacts due to the amount of communication those HCs have to perform between each other and the server.

For more discussion, please move this to the ACEX repository. I will close this one.
