### ISSUE TITLE
preventInstaDeath

### ISSUE THREAD

**Issue by razgovorov87** [acemod/ACE3#7639]
In the last update, the parameter was removed force ace_medical_preventInstaDeath = false;
Does this parameter have an analogue or has it been replaced?
Is it possible to achieve "instant death" in another way?

**Comment by ArwynFr** [comment]
This setting is replaced by two other settings :
* medical statemachine settings `Player Fatal Injury`
* medical damage settings `Fatal Damage Source`

`Fatal Damage Source` defines what is considered a fatal hit ; it has 3 possible values :
* `Only large hits to vital organs` = only hits on head/torso above a certain threshold of damage value are fatal ; all other hits are non-fatal, even if you already sustained a lot of wounds
* `Sum of trauma` = all hit are considered non-fatal, until the sum of overall damage reaches 1 ; then all hits are considered fatal, including very small hits
* `Either` = both mechanisms at work ; any large hit to head/torso is considered fatal whatever the sum of trauma you have ; other hits will add until the sum reaches 1 ; then any hit will be considered fatal

`Player Fatal Injury` defines what happens when you receive a fatal hit ; it has 3 possible values :
* `Always` = taking a fatal hit will instant kill you
* `In Cardiac Arrest` = taking a fatal hit will set you in cardiac arrest ; if you already are in cardiac arrest, it will instant kill you ; this introduces the ability for enemies to execute you when in cardiac arrest state
* `Never` = taking a fatal hit will set you in cardiac arrest ; if you already are in cardiac arrest, nothing specific happens (you still get additional wounds though)

Non-fatal wounds can either be critical or non-critical, depending on damage and location of hit. Non-critical hits will simply add a wound on the bodypart. Critical hits will set you unconscious. Usual conditions for unconsciousness recovery apply. You may still die after a non-fatal wound if you loose a large amount of blood and enter bleedout condition (hemorrhagic class V = blood volume below 0.5).

There is a separate `AI Fatal Injury` setting, but `Fatal Damage Source` is the same for everyone.

**Comment by jonpas** [comment]
> There is a separate `AI Fatal Injury` setting, but `Fatal Damage Source` is the same for everyone.

Should still be split in my opinion.

**Comment by jonpas** [comment]
Do you want an ACRE update or a setting you won't use? ;)

**Comment by bux** [comment]
setting 💯
