### ISSUE TITLE
How to prevent instant unconsciousnes when getting a Headshot 

### ISSUE THREAD

**Issue by Backwasch** [acemod/ACE3#7642]
Hey,
I have a small problem with the new ACE System, because I can`t find a way to prevent instant death/unconsciousnes, when recieving a headshot. Even with a Viper Helmet, my player gets unconscious after just one shot.

Is there a way to increase the amout of damage a player needs to recieve to the head before he gets unconscious? Because the only setting I found is "ace_medical_playerDamageThreshold" but this setting just changes how much damage he is allowed to get into the rest of the body but doesnt change anything for the head.

If such a setting doesn´t exist yet, is it possible to implement into ACE?

**Comment by ArwynFr** [comment]
You shall set `Fatal Damage Source` to `Sum of trauma` ; this will deactivate the detection of the headshot as a fatal hit _per se_. Then you can set the `Player Damage Threshold` to something large enough for the shot to stay below that limit.

**Comment by hugo-davron** [comment]
Hello I've got the exact same problem ! I tried many different settings but if i set Fatal Damage Source to Sum of Trauma like you said @ArwynFr but if I get headshot I die. Same if I set Fatal Injuries on provoke cardiac arrest. I figure that this problem has occured just after the Old Man update.

**Comment by ArwynFr** [comment]
Sounds like your player damage threshold is too low, and the headshot did more damage than that.

**Comment by hugo-davron** [comment]
Yeah I already explore this clue. I put player damage threshold to maximum (25 if I'm not wrong) and It require exactly same amount of cartridge in leg, arm, torso, head (1) to die. It seems really weird. Also four other strange things appear since Old man update. Medical-related : You can be hurt like in the leg and my character limp but not a single injuries for ace; Second thing, if you check a player corpse, no injuries to where the AIs got it. Moreover if you take control of an AI and kill a player it will be write in the chat : Player has been killed by (you who control the AI) but before it was write player has been killed. Finally fourth thing which not really fit in this issue but I'm convince will be resolve by the same time : Stamina has been deactivated with ace but if you run a couple of meters you will shudder as stamina was activated.

This thing is just driving me crazy. My theory is that since Old Man was released the ACE medical system is just being override by the vanilla medical system and same for stamina and all mechanics which are provided by Arma and enhanced by ACE.

I have really no explanations of what this thing happen. Just to set a context everything was fine before Old man and just after instant death to make it short. We also run the game on a Linux base dedicated server if this can be a clue. Honestly I'm really lost because some people seems to be the same issue and others absolutely not.

Thank you for you quick response @ArwynFr , really appreciate it ;)

**Comment by JP4422** [comment]
Have the exact same issue. Doesn't matter how high the Player Damage Threshold is, one shot seems to kill even if sum of trauma is turned off.

**Comment by commy2** [comment]
Try without other mods.
