### ISSUE TITLE
Medical system is completely broken

### ISSUE THREAD

**Issue by OlegAckbar** [acemod/ACE3#7660]
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` 
- **CBA:** `3.15.0` 
- **ACE3:** `3.13.2` 
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
Medical system is broken. Players and AI could receive insane amount of damage to their limbs. Grenades, explosives and etc. deals almost zero damage (units survive and feel fine after direct hit of 40mm grenade). Although damage which is dealt to torso is pretty deadly (as it should be).

**Steps to reproduce:**
Just shoot infantry units by firearms and explosives.

**Expected behavior:**
High amount of damage to limbs should be more lethal. Explosives should deal more damage and leave worse wounds.

**Where did the issue occur?**
- Everywhere

**Log Files:**
- https://yadi.sk/d/F4V1aBMX214N5w

**Additional context:**
Don't tell me to change damage threshold. Famage to torso when "damage threshold" is 1 is just fine.

**Screenshots:**
Here's video with demonstration https://youtu.be/mMsD6RnMgl4

**Comment by BaerMitUmlaut** [comment]
It's almost as if there are not vital organs within your limbs! Crazy how that works.

**Comment by Aphex123** [comment]
> It's almost as if there are not vital organs within your limbs! Crazy how that works.

If this is the unrealistic model which you want to play by than so be it. But more threshold sliders must be added so others can model traumatic injuries accurately.
As of now many of the medical sliders related to how easy a unit may go unconscious and/or die are not functioning properly.

**Comment by PiZZAD0X** [comment]
It's almost as if a majority of the ace users hate the new medical system which is effectively broken and when some dev responds in a condescending manner with no regard for users' wishes people lose respect for the whole mod team. Crazy how that works!

**Comment by jonpas** [comment]
> At this point some communities are looking to fork and fix this mess.

Great! PRs very welcome!

> It's almost as if a majority of the ace users hate the new medical system which is effectively broken

That's not what general feedback or statistics of that feedback currently says.

**Comment by BaerMitUmlaut** [comment]
>If this is the unrealistic model which you want to play by than so be it.

What exactly is unrealistic about this? What limb wound would cause instantaneous death?

>As of now many of the medical sliders related to how easy a unit may go unconscious and/or die are not functioning properly.

If something specific doesn't work, create an issue for it. You are welcome to create multiple issues for each specific problem. Saying "it's completely broken" does not help.

>It's almost as if a majority of the ace users hate the new medical system

How would you know, have you spoken to the majority of ACE users? Because that's not what our download numbers say.

>which is effectively broken

Please create an issue if you find a bug.

>when some dev responds in a condescending manner

I responded in a condescending manner to a condescending issue calling the result of *months* of work "completely broken".

I'm closing this issue, no need to feed the trolls. If you want to reconsider and try giving some constructive feedback we can work with, please create a new issue.
