### ISSUE TITLE
Explosive Armor Value Causing Bullet Sponges

### ISSUE THREAD

**Issue by Ezzyboyo** [acemod/ACE3#7799]
**Mods (complete and add to the following information):**
- **Arma 3:** ` 1.98 Stable` 
- **CBA:** `3.15 Stable` 
- **ACE3:** `3.13.3 Stable` 
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
EOD/Explosive/GL Vests Spike Armor Values

**Steps to reproduce:**
Place down 1 Standard Rifleman and 1 Grenadier/Team Lead for AAF
Place down Player Character with a 5.56 Weapon
Shoot Rifleman then shoot Grenadier in the Chest until they die

**Expected behavior:**
Grenadier takes way longer then they should too die

**Where did the issue occur?**
- Editor/Zeus Multiplayer Editor/Zeus Singleplayer

**Log Files:**
The issue didn't cause me to crash

**Additional context:**
Note that GA Carrier Lite vest has an armor value of 18 whereas the GA carrier GL rigs have an armor value of 80 which Is probably the Issue

**Screenshots:**
I have two Videos of it https://youtu.be/RiFA4CCaGcE and https://t.co/v3DPQ0V5Ay?amp=1

**Comment by Salluci** [comment]
ACE's damage engine is different from vanilla Arma 3's. There is no usage of the passthrough value (vanilla "Ballistic Protection") to simulate sum of trauma. Instead damage is taken directly from the hit value, which as calculated as bullet damage divided by armor, and sum of trauma is handled by its own function.

This may not necessarily be intentional, but it is *expected* behavior. IIRC, this also holds true for legacy versions of medical.

**Comment by Dudejo** [comment]
does that mean it is now absolutely pointless to use the Special Rig?
