### ISSUE TITLE
Delayed/Phantom Damage/forced uncon for pilots

### ISSUE THREAD

**Issue by TFMVapour** [acemod/ACE3#7960]
Current  release and stable version of ACE
Link to current modset: https://steamcommunity.com/sharedfiles/filedetails/?id=1390826487

Problem recreated with just ACE and CBA

**Description:**
Pilots appear to be taking damage/made unconscious with significant delay. i dont really know how to explain it, myself and 2 others have run into this issue multiple times with other helicopters, note the ones in the video linked below are from RHS

**Steps to reproduce:**
Approach an LZ with 1 or more helicopters
AI were placed down via Zeus by a different player

**Expected behavior:**
If pilot was hit/shot: become wounded/unconscious at time of impact

**Where did the issue occur?**
Dedicated multiplayer server
**Log Files:**
No crash was experienced and no clue how to get the RPT file from our dedi server
**Additional context:**
link to video demonstrating issue: https://youtu.be/-85kgN9Ihj0
at 0:47 you can see rounds impact the glass of the cockpit and i assume these rounds have hit the pilot, but for whatever reason the damage is delayed and is not inflicted on the pilot until after he has left the LZ, this video is from the perspective of someone else, i am piloting the helicopter on the right around the same time the pilot of this Helo was knocked unconscious i recieved phantom damage in the form of a velocity wound to my left leg as well as the main rotor being damaged i had already left the LZ when the pilot in the video was knocked unconscious

My initial thoughts are that thanks to the new contextual unconscious animation update released at the end of august may be causing the issue, bear in mind i genuinely have no clue what is causing this

**Comment by BaerMitUmlaut** [comment]
This might be a visual bug, as in the blood effects not appearing.

**Comment by TFMVapour** [comment]
> This might be a visual bug, as in the blood effects not appearing.

I doubt it in the video you can see multiple rounds impact the cockpit and assumedly impact the pilot surely he would have been knocked out instantly? also as stated this is not from my point of view and myself and my helicopter (on the right) did not receive damage until we had left the LZ the moment the damage kicked in the MROT in the top left turned orange and I gained a velocity wound in my left leg

**Comment by BaerMitUmlaut** [comment]
I could not reproduce this and to be honest, I'm pretty sure everything is in order here. My explanation:
- The rounds at the beginning hit some glass - might be cockpit glass, might be the cabin doors. They did not hit the pilot, otherwise the blood effect would have shown. There is no indicator that they hit the pilot.
- You still were being shot at after leaving the LZ, llikely by some bigger caliber, which caused the main rotor to get damaged.
- This explains both why you received a leg wound as well as why the pilot was knocked unconscious. He probably received an unlucky round to the head.

I don't have RHS installed, but you could test the armor of those helicopters. You could check if you can headshot the pilot through the hull from some angle behind and below the helicopter. I tested this with the vanilla Hellcat and can confirm that's possible.

What I would need in this case to confirm this is an actual problem is some sort of proof that you got shot before taking off. Glass breaking just isn't enough.
