### ISSUE TITLE
"Set zero adjustment" changes UI but not zeroing

### ISSUE THREAD

**Issue by soryy708** [acemod/ACE3#7968]
**Mods (complete and add to the following information):**
- **Arma 3:** stable
- **CBA:** stable (steam 22-apr-20 5:23pm)
- **ACE3:** stable (steam 31-aug-20 5:29pm)
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
Ace self-interaction "Set zero adjustment" changes the zeroing UI but doesn't actually change zeroing.

**Steps to reproduce:**
1. Set up the following settings:
ACE Advanced Ballistics: Enable `Adv. Ballistics`, Set `Simulation Interval = 0.20`
Ace Scopes: Enable `Force adjustment turrets`
2. Get a Mk14 mod1 EBR rifle, put on a Nightforce NXS scope, and use 7.62mm 20rnd tracer rounds.
3. Set up a target at 800m distance from you. Press page-up to adjust zeroing appropriately (approx +9.0).
4. Fire at target, note where the bullet hits.
5. Ace self interact -> Equipment -> Set zero adjustment
6. Fire at target, note where the bullet hits.

**Expected behavior:**
Bullet should hit way short of where it did before resetting zeroing.

**Actual behavior:**
Bullet hits where it did before. It's as if zeroing didn't change, despite the UI showing otherwise.

**Where did the issue occur?**
- Dedicated multiplayer, Editor (singleplayer)

**Comment by Laid3acK** [comment]
The "Set zero adjustment" has been introduced with the first ACE3 versions because the vanilla zeroing was (and is always) inaccurate.
The raison of the "Correct zeroing" option enabled as default in the ACE Scopes panel.
The "Set zero adjustment" makes sens only if the "Correct zeroing" is disabled.

**Comment by soryy708** [comment]
In that case,
If `Correct zeroing` is enabled by default then it is enabled in this reproduction scenario.
Therefore, the "Set zero adjustment" option is broken by default.
In that case, I think that it should be hidden from the self interact menu if `Correct zeroing` is enabled.

**Comment by Laid3acK** [comment]
There is nothing broken, you just don't understand how use it.
The "Set zero adjustment" has an effect on the scope elevation only, not the bullet trajectory in-game.

**Comment by soryy708** [comment]
Relevant files:
https://github.com/acemod/ACE3/blob/master/addons/scopes/functions/fnc_canResetZero.sqf
https://github.com/acemod/ACE3/blob/master/addons/scopes/functions/fnc_resetZero.sqf

**Comment by Salluci** [comment]
Set zero adjustment is used for setting a new zero as your baseline, not resetting your scope's zeroing. Setting your scope's zero adjustment to +9 will mean +9 is your new reference point for zeroing. Adding +2 to that would show +2 in the UI, but since your new reference point is +9, it's +11. It's meant for small adjustments to correct deviations. In math:

zero = 0 + zeroAdjustement + turretAdjustment, but zeroAdjustment is equal to 0 until you manually set it.

**Comment by Laid3acK** [comment]
You should try some old Advanced Ballistics tuto videos which explain the utility of the "Set zero adjustment".
But let's go with math and the example above. The NXS has a total elevation of 27 mRad.
If the "Set zero adjustment" is used with 9 mRad, this means 27 - 9 = 18 mRad, 
the NXS elevation turret is now configured with 18 mRad Up and 9 mRad Down (-9 with the legacy UI), that's all.
That is the "Set zero adjustment", nothing else.

**Comment by soryy708** [comment]
I understand that I misunderstood the desired functionality of the option.
Perhaps the option should be renamed slightly to communicate it's function in a more intuitive way?
