### ISSUE TITLE
Improving medical fluids.

### ISSUE THREAD

**Issue by Dudejo** [acemod/ACE3#8015]
**Is your enhancement related to a problem?**
Currently, there are no advantages to either fluid type. In-game, I have successfully cured blood loss with nothing but Saline.

**Solution you'd like:**
Too little blood causes pain (asphyxiation), too little plasma causes bandages to leak sooner (low platelet) and too little saline causes high heart rate/low blood pressure (dehydration).

**Alternatives you've considered:**
Limit the current blood level at which the fluid will have any effect. Fatal or Large amount of blood loss would only be treatable with Blood IVs, Lot of blood loss could be treated with Plasma and, if only Some blood loss, Saline could then be used.

**Additional context:**
none

**Comment by BaerMitUmlaut** [comment]
People would carry only blood bags then, so we would also have to add a downside - which would probably be having to cool them. And that is really hard because tracking unique items is really difficult.

**Comment by Kryomancer** [comment]
I don't think it's absolutely necessary for every item to have a downside, because Arma is a military simulation game, it doesn't need to uphold gameplay balance in the traditional sense. It's kind of like saying that it's pointless to offer normal sniper scopes when everyone could just take the Nightstalker. People are perfectly willing to play with deliberately suboptimal equipment for the added challenge and immersion. It'd also mean that having a setting to turn off the downsides for other liquids might not be necessary, as people who wanted their liquids to _just work™_ could just bring the blood bags instead. Currently having all the liquids behave exactly the same makes them somewhat pointless duplicate items.

**Comment by Dudejo** [comment]
Ideally, I would simply trim down the number of fluid items but then you'd have people complaining that it breaks their loadouts.

Also, I figured that since ACE3's purpose seems to be increased realism, we should justify having the different fluids. Hell, it already simulates morphine overdoses. While I agree my initial suggestion is imperfect, I believe it's an avenue worth exploring instead of being dismissed.

**Comment by Kryomancer** [comment]
I might've been slightly unclear, what I meant with my comment was in response to @BaerMitUmlaut about having to add a downside to the blood bags as well, I'm fully in support of adding downsides to the other fluids as per your ( @Dudejo ) initial comment. What I meant to point out is that having the blood bags be "owerpowered" or "unbalanced" compared to the other fluids is not an issue in my opinion. Having to keep blood cold would be a nice feature as well, but implementing might be a bit impractical for Arma.

**Comment by severgun** [comment]
> but implementing might be a bit impractical for Arma
That is why it should be balanced.
Even with taste of realism ARMA is just a game and gameplay should be a quite major factor to consider.

**Comment by JustAKuba** [comment]
If I am right, blood and plasma will "rot" when they are not at the medical facility for a longer time... Doesn't that mean that only MEDEVACs will be able to transport Plasma and Blood?

**Comment by BaerMitUmlaut** [comment]
@JustAKuba If you mean the behaviour right now within ACE3, no, that is not true.

**Comment by JustAKuba** [comment]
Ok, So why not do it like this? :D

**Comment by BaerMitUmlaut** [comment]
Read my previous reply.

**Comment by kymckay** [comment]
> Ideally, I would simply trim down the number of fluid items but then you'd have people complaining that it breaks their loadouts.

We could just hide items to cut them down (been a long time since I did ARMA stuff, but I know there's a config value to do so). Meaning they're still accessible by script/scenarios using them, but new scenarios are limited to *just* bloodbags or whatever.

I do agree it's a bit odd we provide these different items with no differentiable behaviour.

**Comment by JustAKuba** [comment]
> Read my previous reply.

Ok, so how about moving the problem from the item to the character itself? It is sure hard to track the item itself, but it is not hard to track the state of a player. When we set some kind of maximum value of fluid, that can a player have in his veins, then it makes sense that saline should have an impact only on blood pressure. 
I don't know how many people actually use KAT medical, but that would mean that when you pump up someone with saline, his saturation would not rise and he will die because he has not enough oxygen. Basically, it would add the next dimension in the lives of CLS and doctors in ArmA.

**Comment by pterolatypus** [comment]
Balance-wise, having a separate setting for plasma/blood only being usable at medical vehicles/facilities would have a similar effect in terms of gameplay while still being configurable.

**Comment by Dudejo** [comment]
> 
> Ok, so how about moving the problem from the item to the character itself? It is sure hard to track the item itself, but it is not hard to track the state of a player. When we set some kind of maximum value of fluid, that can a player have in his veins, then it makes sense that saline should have an impact only on blood pressure.
> I don't know how many people actually use KAT medical, but that would mean that when you pump up someone with saline, his saturation would not rise and he will die because he has not enough oxygen. Basically, it would add the next dimension in the lives of CLS and doctors in ArmA.

Or for a simpler solution....what if injecting fluids that aren't blood causes "artificial" bleeding, since the blood concentration is lower?

**Comment by Andx667** [comment]
i would love a setting to allow blood/plasma only in vehicles/facilities.
maybe its possible to have saline only restore up to 2 litres of blood volume? if the patient needs more he would need blood/plasma.

**Comment by BaerMitUmlaut** [comment]
#3594
