### ISSUE TITLE
40mm grenades shrapnel travel too far. 

### ISSUE THREAD

**Issue by Brisse89** [acemod/ACE3#810]
IRL specifications for M203: 

Minimum safe firing range (HE):

    Training.....................................................................130 meters (426 feet)
    Combat......................................................................31 meters (102 feet)

In ACE3, I have found shrapnel from these to be a danger as far out as 250m, and even at the weapons maximum reach at 400m I can still hear shrapnel hit the ground around me.

**Comment by jaynus** [comment]
The ranges, velocities and types of shrapnel are pretty correct and realistic. You may be hearing lower velocity (it slows down) shrapnel hitting near you. We use the gurney equations to calculate shrapnel instead of magical values, so the flight and velocity of the pieces are indeed realistic.

You may be interested to know that overall pieces of shrapnel travel a lot further than you may be used to in A3. 

I'm referencing the M67 documentation here, as it states this best:
"The M67 can be thrown 30 to 35 metres (98 to 115 ft) by the average male soldier. Its fuze delays detonation between 4 and 5 seconds after the spoon is released. Steel fragments (not to be confused with shrapnel) are provided by the grenade body and produce an injury radius of 15 metres (49 ft), with a fatality radius of 5 metres (16 ft), though some fragments can disperse as far out as 250 metres (820 ft).[2]"

**Comment by Brisse89** [comment]
Jaynus, have you actually tried this ingame? I'm sure the Gurney equations are correct, but there's more to the frag simulation, that has the potential to screw it up. 

I had a little discussion with NouberNou on BI-forums and when I present the problem he pretty much confirms that what I said was true. 

The problem is real, and I even found it in your configuration file. See links below for discussion and solution. 

http://forums.bistudio.com/showthread.php?190433-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2925438&viewfull=1#post2925438

http://forums.bistudio.com/showthread.php?190433-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2925466&viewfull=1#post2925466

http://forums.bistudio.com/showthread.php?190433-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2925538&viewfull=1#post2925538

**Comment by Brisse89** [comment]
Nevermind. Fixed it for you. :) 
https://github.com/acemod/ACE3/pull/818
