### ISSUE TITLE
ATragMX - coriolis and spin corrections ignore direction of fire for lateral corrections

### ISSUE THREAD

**Issue by ArwynFr** [acemod/ACE3#8123]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.00`
- **CBA:** `3.15.2`
- **ACE3:** `3.13.5`

**Description:**
The coriolis and spin effects in the ATragMX do not take into account the direction of fire.
This results in an incorrect lateral correction in the calculations.

**Steps to reproduce:**
1. _Open ATragMX and enable Option Show Coriolis_
2. _Enter latitude = 42°N; Dir of Fire = 0°; Target Range = 2000m; Done_
3. _ATragMX displays Coriois = x.xx L and Spin = 0.xx L (correct)_
4. _Change Dir of Fire = 180°_
5. _ATragMX displays the same values as before (wrong)_

**Expected behavior:**
Results should depend on the direction of fire.
For instance, when facing south, effects should give a correction to the right.

**Where did the issue occur?**
- Virtual Arsenal
- Local multiplayer
- Dedicated server

**Log Files:**
- https://1drv.ms/u/s!AuiYSC7rO21qp4tEAsWfKut9qpF-Uw?e=Mu6JHz

**Additional information:**
- Up/Down corrections are correct

**Comment by Laid3acK** [comment]
The direction of fire has only a vertical effect due to the Eötvös effect (Earth rotation).
In your example, there is no reason that the AtragMx, or another ballistic softwares, update the lateral corrections between 0° and 180°, the horizontal spin drift and Coriolis effects are exactly the same.
Shooting at 0° and 180° will not reverse laterally or change something to the bullet trajectory in-game (except wind).

**Comment by ArwynFr** [comment]
I think I need to go back to physics class :)
