### ISSUE TITLE
Unsupported language Russian in stringtable

### ISSUE THREAD

**Issue by topden** [acemod/ACE3#8136]
Mods (complete and add to the following information):

    Arma 3: 2.00.146.773 [stable]
    CBA: 3.15.2.201119 [stable]
    ACE3: 3.13.5 [stable]

Description:
 4:29:54 Unsupported language Russian in stringtable
 4:29:54  ➥ Context: z\ace\addons\explosives\stringtable.xml
 4:29:54 Unsupported language Russian in stringtable
 4:29:54  ➥ Context: z\ace\addons\grenades\stringtable.xml
 4:29:54 Unsupported language Russian in stringtable
 4:29:54  ➥ Context: z\ace\addons\map_gestures\stringtable.xml
 4:29:55 Unsupported language Russian in stringtable
 4:29:55  ➥ Context: z\ace\addons\goggles\stringtable.xml
 4:29:55 Unsupported language Russian in stringtable
 4:29:55  ➥ Context: z\ace\addons\trenches\stringtable.xml

Steps to reproduce:
start the game and check rpt

Expected behavior:

Where did the issue occur?

    Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

Log Files:
no

Additional context:
no

Screenshots:

**Comment by PabstMirror** [comment]
selfnote: These don't show up unless you actually switch your game's language

It's not really an error, it's just saying there are untranslated entries
e.g.
```
        <Key ID="STR_ACE_Explosives_TimerMin_DisplayName">
            <English>Minimum Time</English>
            <French>Durée minimale</French>
        </Key>
```
will cause that error because it's missing russian
this must have changed in 2.02

ref issue: https://github.com/acemod/ACE3/issues/367 - we're always looking for more translators 😉
