### ISSUE TITLE
Arma 3 not loading saved games in Single player

### ISSUE THREAD

**Issue by KoelJ** [acemod/ACE3#8181]
Hi followed your flow chart and isolated ace as culprit, new mission starts ok and saves but just freezes on load, If I click on screen it says wait to respond or close, tried different missions with just cba3 and Ace , as soon as I remove ace it saves quicker and loads quicker

**Comment by KoelJ** [comment]
It seems to be after the last changelog, could always save and load before

**Comment by BaerMitUmlaut** [comment]
Please fill out the issue template.

**Comment by KoelJ** [comment]
Where can I find the template?

**Comment by bux** [comment]
You probably came from ace3mod.com.
When you click on the "New issue" button on the top right:
![image](https://user-images.githubusercontent.com/1235520/112482530-7268e100-8d78-11eb-88da-823d814156aa.png)
you can select "Bug report" from that list:
![image](https://user-images.githubusercontent.com/1235520/112482594-84e31a80-8d78-11eb-9ecc-6b1fcc7d9dfc.png)

I have changed the link on ace3mod.com to lead to that list instead of to just a blank new issue, yesterday.

**Comment by KoelJ** [comment]
Ok must have done just before.  Pretty easy to replicate.  With only  cba3
and ace mid when you load into a new single player scenario and save it
freezes on the loading screen when you load the  saved game either from
withinn the scenario or when you resume the scenario from scenario menu.
As soon as you click or press buttons it gives the usual nooit responding
message.

If you remove the ace mod however it loads as normal also with all my usual
mods minus ace it loads fine.  This seems to be a very recent thing,
started noticing since this week

Wil try aanvaa
