### ISSUE TITLE
[Medical] Morphine and torniquets too strong against pain

### ISSUE THREAD

**Issue by Ivanowicz** [acemod/ACE3#8213]
**Is your enhancement related to a problem?**
For a while now, our group was noticing some weirdness with pain related knockouts - and now that you added the Pain Unconscious Chance slider (thanks!) we started understanding how they work. We did some testing and found some rather problematic things (mostly focusing on limb pain):

Settings for tests were mostly default, except for Pain Unconscious Chance set to 100%, to eliminate some randomness.

- **Morphine** is quite strong at reducing new, incoming damage pain - not to a ridiculous extent, but it still took a few times more damage to knock a unit out through pain - even more if the damage was being dealt to a single limb, since there seems to be a cap, or some sort of diminishing pain returns on a single body part. (Please correct me if I'm wrong here.) 
I could dump a full 30rnd 6.5 mag into a single leg and have the unit still standing, but it took *only* 2-3 rounds into each leg to knock it out. With no morphine the units will go down from at most a few shots to a leg, with 1 hit being enough most of the time.

**EDIT 2** Seems part of that result (torniquets only) was either error on our part, or a one-off Arma weirdness.

- **Torniquets** ~~not~~ only stop bleeding, ~~but also reduce the pain coming from the limb by something like 90%+!~~ After additionaly taking morphine before applying torniquets, it seems to be impossible to knock out a unit through limb damage/pain - I think 100+ bullets in each limb counts as impossible. ~~Without morphine it's at least feasible, though still crazy - needs a few dozen rounds per limb.~~

I am aware this is an extreme example, but even with growing pain from torniquets, there seems to be nothing stopping a player from taking morphine, putting on 4x torniquets, and then just taking a single torniquet off and putting it back on to reapply morphine every 10-15min, becoming a bit of a terminator, especially in shorter missions.

**Solution you'd like:**

- **Morphine** - no criticisms for the most part, but if possible, a reduction of its effect on new pain - it makes sense for it make the soldier more resistant, but having to deal at least 5x more damage for a pain knockout is a bit much I think.

- **Torniquets** - either massively reducing the pain reduction, or adding bigger penalties related to apparently cutting both blood flow _and_ nerve connections off from the limb. Amittedly I don't have any exact ideas on what would those be - maybe something along the lines of the broken limb effect, e.g. slower movement speed for legs, more sway for arms, scaling at the same pace as the pain from torniquets? Or the torniquet pain being more severe/somewhat resistant to morphine?

**Additional context:**
If necessary I can provide screenshots and/or videos of the issues.

**EDIT**
Since it seems to be a bug, I'm doing additional testing to make sure it's not something on my end.

**Comment by BaerMitUmlaut** [comment]
Tourniquets reduce pain? That would be news to me.

**Comment by Blutze** [comment]
Shot in the dark here: maybe the knockout chance is based on bloodloss difference, and with a tourniquet bloodloss on that limb is zero both before and after? Alternatively, the tourniquet pain being added overwrites the intermediate (time-wise) pain change from the hit?

Other way, tourniquets interfering here seems to be a bug.

**Comment by LachlanSneddon** [comment]
The requirement for unconsciousness from pain is a pain level of 0.5. If you have advanced medication on, a single morphine is going to prevent pain from ever reaching that level for a little over 11 minutes. 

In regards to tourniquets, one of the other ways to knock someone out is bleed rate. As tourniquets reduce effective bleeding to 0, having them on will prevent unconsciousness from this. Bleeding is required to be above 0.5 in order to knock someone out, while legs are capped at 0.5, and arms at 0.3. This is why mag dumping one leg had significantly less effect than a few bullets in both.

From my testing, tourniquets don't appear to decrease pain from damage to limbs, at least not by any level significant enough to measure, as there is a degree of randomness in the pain value applied. 5, 6.5 rounds to a tourniquetted and untourniquetted leg led to pain values of ~0.8.

By blocking both of these ways of knocking out a player, it does largely negate limb damage (with the exception of limping), as damage based incapacitation only utilises head and chest damage. 

As far as tourniquet + morphine terminators go, adjusting the damage thresholds is probably the quickest solution, as this is probably one of the more frequent reasons players go down. How this setting affects unconsciousness and cardiac arrest chances depend on your player fatal damage settings and your damage source settings (sum of trauma/Large hits)

**Comment by Ivanowicz** [comment]
Well, I did some more testing (on AI only this time, when we find some time I'll do more with another player). It seems we must have done a mistake somewhere during testing, because I couldn't reproduce the **torniquet only** result - so the results seem to be completely in line with what @LachlanSneddon has said. Apologies for a bit of an accidently misleading report.

On top of that, thanks you @LachlanSneddon for extensive explanation on how bleeding relates to knockouts - had no idea that extensive bleeding can cause it by itself (If I'm understanding what you wrote right). That got me thinking - is bleeding or pain  coefficient in any way connected with that part of knockout mechanic?

As for the last paragraph - well, that's another part of our problem. I am aware that our settings are quite a bit different from defaults (damage threshold **2.5**, with damage source on **Either**) - for us it strikes a nice balance between not going down from random shots and still being killable. Sadly though, this, combined with the "terminator torniquets", makes for a potentially easily abusable combination (and makes me feel kinda bad when using tqs with morphine at all, haha).

Still, I would love if there were more (maybe optional) penalties connected with using torniquets for extended periods of time - given the pain penalty can be pretty much 100% countered with morphine. (Which, of course, has downsides, but not large enough ones in my opinion).

**Comment by LachlanSneddon** [comment]
For the coefficients: The pain coefficient will to some extent, as with higher values you are more likely to get pain values that put you above 0.5, while with low values (e.g. 0.1) you'll rarely take enough damage to get up to 0.5. For the bleeding coefficient, it's only applied when calculating the blood lost from a player. The values used for knockout thresholds are a percentage of cardiac output (can be thought of as flow rate of blood in the patient) , which isn't affected by the coefficients.
