### ISSUE TITLE
Ace stuff disapear in Arsenal 

### ISSUE THREAD

**Issue by Aedix** [acemod/ACE3#8237]
**Mods (complete and add to the following information):**
- **Arma 3:** latest steam version
- **CBA:** 3.15.3.210310
- **ACE3:** 3.13.6
- _The others mods used when the issues happened :_

> [-] **Dynamic Universal War System**

**Description:**
When I'm playing with Ace at the beginning everythings working good but after a time, when I'm trying to take some heal at the Arsenal all aids for Ace Medical have been disapear
![ArmA 3 Screenshot 2021 04 29 - 15 33 06 56](https://user-images.githubusercontent.com/66688859/116559174-6edcf280-a900-11eb-8e68-17c6e615dcd0.png)

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**

**Where did the issue occur?**
- Singleplayer / Virtual Arsenal

**Log Files:**
- Link to: (https://pastebin.com/ih3pxcJN)

**Screenshots:**

**Comment by BaerMitUmlaut** [comment]
This sounds like an issue with the mission to me.

**Comment by Aedix** [comment]
> This sounds like an issue with the mission to me.

This is right, the issues come from the mission who dont use the Ace Arsenal and it cause issue like ace Aid or some stuff are not listed in the arsenal. My problem now it's I dont know how I can put the ace arsenal for the mission, I have trying to see how I can do it but still dont work.

**Comment by BaerMitUmlaut** [comment]
The vanilla arsenal works just fine with ACE items. If you prefer the ACE arsenal, you can find more information about using it here: https://ace3mod.com/wiki/framework/arsenal-framework.html

If you have any specific questions for using it, feel free to ask them here or in our Slack.

In this case, I would ask the mission author about this issue. This is not a problem caused by ACE and I don't know how we could solve your problem.
