### ISSUE TITLE
Seperate 'Wounds Reopen' into own option.

### ISSUE THREAD

**Issue by Mannulus** [acemod/ACE3#8335]
Pretty self explanatory but would be great for those who want a nice medium of their medics having more purpose with stitching while still not having to deal with the various types of bandages.

**Comment by kymckay** [comment]
Others will remember better than I can if there's a rationale for the settings being coupled (off the top of my head it might be due to the way these systems are actually implemented resulting in no reopening for basic bandages).

That said, just looking at the settings themselves, if I were going to redesign and reimplement them then I'd just make the reopening coefficient 0 by default and increasing it implicitly enables reopening independently of the basic/advanced bandaging setting.

**Comment by Drofseh** [comment]
#3594

**Comment by BaerMitUmlaut** [comment]
Agreed with Drofseh, belongs into feature requests.
