### ISSUE TITLE
error in common_fnc_getAwakeAnim

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#8429]
`CUP_B_MH47E_GB` - chinook - woke up when in a cargo seat
felt like "neck was broken", camera movements were bizzare

```
Error in expression < >> getArray (_config >> "cargoAction") select _cargoIndex) 
Error position: <select _cargoIndex) 
File z\ace\addons\common\functions\fnc_getAwakeAnim.sqf..., line 45
```

**Comment by johnb432** [comment]
Never got around to reporting this issue, but it has happened twice to our group in the "Y-32 Xi'an (Infantry Transport)" from the Apex DLC. The infantry in the back of the VTOL passed out due to excessive G-force and when waking up they had the same issue as Pabst has described.

`Error in expression < >> getArray (_config >> "cargoAction") select _cargoIndex)`
`Error position: <select _cargoIndex)`
`Error Zero divisor`
`File z\ace\addons\common\functions\fnc_getAwakeAnim.sqf..., line 45`

**Comment by PabstMirror** [comment]
Thanks for the info

```
class VTOL_02_base_F: VTOL_Base_F {
    cargoAction[]= { "passenger_generic01_foldhands" };
```
So it seems like it's valid for the array to be smaller than the max cargo index a player could be.
