### ISSUE TITLE
Autoinjectors are shown as weapons in inventories

### ISSUE THREAD

**Issue by bux578** [acemod/ACE3#870]
ACE3 Version: 71f29466d71f8db944ffa7a5cd1a74798292304d

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
* None

**Description:**
Autoinjectors are shown as weapons in inventories should be "items".
![morphEpiWeapons](http://puu.sh/hrpFx/867e3b49fa.jpg)

**Steps to reproduce:**
* Place Medical Box

**Comment by alganthe** [comment]
can confirm, only happens with boxes they are fine when they are on the ground.

**Comment by commy2** [comment]
@bux Is that box placed with zeus?

**Comment by commy2** [comment]
It was.

Those "morphine weapons" are buged weapons. They also have no mass and don't stack with normal items. Happens when the morpine is added via addWeaponCargo. Zeus does this with all MineDetectors. All ACE items are MineDetectors (with detectRange = 0;) , because otherwise they wouldn't show up in the VA.
Zeus sucks and doesn't understand that some classes are items not weapons.

Related:
http://feedback.arma3.com/view.php?id=20997

**Comment by commy2** [comment]
https://github.com/KoffeinFlummi/AGM/issues/1223

**Comment by commy2** [comment]
Fixed in https://github.com/acemod/ACE3/commit/90f1d1f3fa3c0f799745ef828bae13be8957d4a1

Actually they were magazines this time, but basically the same issue.
