### ISSUE TITLE
Laser guided Arty not working with dumb/no computer

### ISSUE THREAD

**Issue by OHoltan** [acemod/ACE3#8867]
Mods (complete and add to the following information):

Arma 3: 2.08 Profiling/stable
CBA: 3.15.6
ACE3:  3.14.1

https://cdn.discordapp.com/attachments/540267144051687426/962097203151769700/Arma_3_Preset_Royal_Welsh_Version_22.html * tried other modlists too

Description:
For laser guided mortar/arty rounds to work you need to fire with the artilery computer 

Steps to reproduce:

Get taget
get mk6
get Laser 82mm rounds
Lase Target
Shoot round manualy
shoot round with Arty computer
see where they land

Expected behavior:
Laser guided mortar guides to laser while using Arty sheet

Where did the issue occur?

Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer)
Log Files:
pt1 https://pastebin.com/CNfXveph
pt2 https://pastebin.com/caapL06s

Additional context:
tested on 3cb and Rhs vehicles too

**Comment by Drofseh** [comment]
Fill out the issue template properly

**Comment by OHoltan** [comment]
if you tell me where it is i can. it aint pined so idk

**Comment by Drofseh** [comment]
If you click on "New Issue" and select "Bug Report" it's right there. 



**Mods (complete and add to the following information):**
- **Arma 3:** `x.xx` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.x.x` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.x.x` [eg. 3.0.0 stable, commit hash]


**Description:**
A clear and concise description of what the bug is.

**Steps to reproduce:**
_Follow [https://ace3mod.com/img/wiki/user/issue_flowchart.png](this flowchart)!_

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**
Add any other context about the problem here.

**Screenshots:**
If applicable, add screenshots to help explain your problem.

**Comment by PabstMirror** [comment]
IIRC this might be a game engine thing and it needs something from the "artillery computer" to know when to deploy the laser seeker submunition

Should be able to test this in vanilla and see how it works when shot from 1st person view (not arty-comp)

We might be able to manually fix this by either triggering it via code or maybe just tweaking the subdeploy config

(Also I should try to finish https://github.com/acemod/ACE3/pull/8210)

**Comment by kamkill01011** [comment]
To me it looks like it's an Arma issue, I tried to use an artillery vehicle manually and with no mods and the result is funny. 
The first shot is a normal HE shell and go straight up in the air, the second is a guided one and goes where I aim. 
![image](https://user-images.githubusercontent.com/17127732/195148621-a6376759-70a2-46c2-98b7-ec12160f8dd9.png)
![image](https://user-images.githubusercontent.com/17127732/195148641-cf227517-7f60-4eb2-8437-e4837c868bea.png)

My guess is the base ammo (for the guided shelll) has `triggerDistance = 500` and the point I'm aiming at is 250m away, so the submunition get triggered as soon as I shoot, but at the same time there is no laser or vehicle so I don't know why the guidance system is working...

**Comment by Kiskadee-dev** [comment]
The 82mm laser guided shells seems to guide itself where the camera is looking if the elevation and direction are withing some radius or no laser target is found, correcting or ignoring completely the weather conditions

If it finds a laser target near the elevation and direction, it guides itself to it

Just my observations on this, tested with the mk6

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
