### ISSUE TITLE
Lower resolution issue

### ISSUE THREAD

**Issue by R4ppiT** [acemod/ACE3#891]
The interaction menu cuts out for me like this. (http://i.imgur.com/z82KZas.jpg) I assume it is because I use 1368x768 resolution. If I disable always display cursor I can see all the options but cannot move on them because they disappear. (http://imgur.com/a/F2EVZ)

**Comment by esteldunedain** [comment]
Yes, 1368x768 is definitely a problem. Try the following workarounds:
* Set the setting "Display Interacion Menus as a list" to true. That should help a bit
* Try reducing the overall size of Arma interface (on A3 Display settings IIRC, set "Smallest"). Our menu size is currently binded to that setting.

Besides that we are planning to create an additional setting specifically for interact menu size, so that will help too.

**Comment by R4ppiT** [comment]
Changing UI size in Arma to small worked.

**Comment by bux578** [comment]
Great. :+1:
