### ISSUE TITLE
Having problem when using ACE3 on Geforce Now

### ISSUE THREAD

**Issue by KeremPasaa** [acemod/ACE3#8977]
I'm an user of Geforce Now and I wanted to play Arma 3 Milsim. But when I try to use Ace3 mod the application kicks me out from the game cause of the mod. The launcher is giving the error code: 0x8003001F. Other mods aren't causing this problem, i tried to start without Ace and it started without any problem. I sent a ticket to Geforce too. But i think the problem is about the mod and Geforce's "don't allow user to change game folders after start" rule. Cuz my other mods aren't about the game's config/prefix but Ace is. So if there is a way to solve/suspend it, i would be grateful.

**Comment by commy2** [comment]
ACE doesn't work with Geforce Now, because it is using DLL extensions. The same happens with all mods that use DLL extensions. This is a limitation of Geforce Now. Until Geforce Now allows DLL extensions, this won't change. Removing DLL extensions from ACE is not feasible, because many core features depend on them.

**Comment by commy2** [comment]
See also: https://github.com/acemod/ACE3/issues/8027 & https://github.com/acemod/ACE3/issues/8741

**Comment by jonpas** [comment]
Duplicate #8027.
