### ISSUE TITLE
Carrier GL Rig & GA Carrier GL Rig Bullet Immunity

### ISSUE THREAD

**Issue by ross1296** [acemod/ACE3#9063]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10 Stable` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.8 Stable` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.2 Stable` [eg. 3.0.0 stable, commit hash]

**Description:**
Targets wearing either Carrier GL Rig or GA Carrier GL Rig can live through multiple mags worth of bullets when hit center mass.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. Create a new mission. For this, I used Eden Editor on Altis
2. Place two AI targets that you intend to shoot. Equip them with Carrier GL Rig or GA Carrier GL Rig
3. Get a gun. _For my testing, I used an MX with 6.5mm_
4. Shoot the target center mass. _For my testing, I proned 30m away from the target, used bipod, and unloaded mag after mag into the chest with no result other than the target having bruises_

**Expected behavior:**
If the Carrier Special Rig, which has full ballistic protection, can soak 10-15 bullets before the target dies, then the Carrier GL Rig & GA Carrier GL Rig shouldn't soak more.

**Where did the issue occur?**
- Replicated in BI VA, ACE VA, Eden Editor SP and Eden Editor Self-Hosted MP

**Log Files:**
https://gist.github.com/JFCO-Highlander/c59e9e7070acae49dca023aeb1fffe8d

**Additional context:**

**Screenshots:**
https://www.youtube.com/watch?v=Q4MCsfYcs5Y

**Comment by johnb432** [comment]
What is the CBA setting "Fatal Damage Source" set to in your tests?

**Comment by nightovizard** [comment]
> What is the CBA setting "Fatal Damage Source" set to in your tests?

I confirm I was able to reproduce this issue too.

Used the NATO grenadier as test subject.

While having the setting: only large hits to vital organs, any hits on the torso will have no effect.

While having sum of trauma or either, after some mags dumped on the torso the grenadier will collapse due to minor and medium bruises. No bleeding or any other kind of damage whatsoever.

Hope this helps.

PD: This also affcts the vests of other sidemods, but since it affects vanilla content we can conclude its not a third party issue.

**Comment by mrschick** [comment]
I've noticed a similar pattern of behavior with AI in our missions wearing RHSAFRF vests, which often have armor levels of 5 or 6. While that might only be semi-related, I also noticed the issue with NATO "Carrier GL Rig" wearers being very difficult to kill.

After seeing this issue thread I made some testing of my own, using the same CBA/Ace versions and MX 6.5mm Rifle on all ballistic/explosive resistant carriers in use by NATO and AAF, counting the number of center-mass shots from <5m required to drop an AI, with damage resistance set to 1.0 and fatal damage source "sum of trauma".
Results are listed below for every mainline carrier rig, in the format of: `name` (`ballistic resistance%`/`explosive resistance %`): `number of shots and remarks` (% values are approximated from Ace Arsenal's stat bars).

- NATO Carrier Lite (65/45): 2 hits, 2 medium VWs (Velocity Wounds;
- NATO Carrier Rig (80/50): 3 hits, 2 medium VWs + 1 medium avulsion or small VW;
- NATO Carrier GL Rig (65/100): 18-20 hits, only medium/minor bruises;
- NATO Carrier Special Rig (100/60): 3-4 hits, only causes small VWs;
- AAF GA Carrier Lite (65/45): 2 hits, 1 medium avulsion + 1 medium VW or just 2 medium VWs;
- AAF GA Carrier Rig (65/45): 2 hits, identical to previous Carrier Lite, but covers much more skin;
- AAF GA Carrier GL Rig (65/100): 16-18 hits, only medium/minor bruises;

Hit number and wounds vary when striking vest parts other than the central front plate. The difference is especially severe in the 2 max explosive resistant vests, as the upper torso's plate can eat up >14 hits, but surprisingly the lower plate covering the abdomen (still on the torso, not referring to the lowest pelvis plate) lets shots through and drops the wearer via 2 medium VWs.

When downgrading to 5.56mm out of an F2000 (AAF), the results (un)surprisingly remain almost the same, penetration is very similar at close range but is stopped slightly better, causing smaller wounds.

When switching the fatal damage source from "sum of trauma" to "only large hits to vital organs", upper plates of GL rigs can withstand >60 direct hits, probably because bruises count even less towards "damage" with the tweaked setting. Abdomen hits also seem less effective, but only slightly (probably due to the intestines being less vital).

After running this test >10 times on every rig with both 6.5 and 5.56, the main contributing factor appears to be high explosive resistance, or more specific resistance multipliers for individual vest segments.
