### ISSUE TITLE
Add missionConfigFile (Description.ext) support for ACE3 Interation Menu

### ISSUE THREAD

**Issue by Benargeez** [acemod/ACE3#908]
https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_compileMenu.sqf#L94

I have been digging through the ACE3 files and noticed that third party menu options can only be defined In addons. If mission makers are not able to define their own actions easily, then users will still have to rely on Arma 3's old clunky action menu in certain situations.

**Comment by commy2** [comment]
Thats not entirely true. You can always use:

https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_addActionToClass.sqf
https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_addActionToObject.sqf

Adding those actions by script is generally prefered anyway. We only use configs, because we use the class inheritance to simlify things, but that doesn't really work for missions.

**Comment by PabstMirror** [comment]
Could add the following to description.ext:
```
class Extended_InitPost_EventHandlers {
    class CAManBase {
        class MissionActions {
            clientInit  = "_action = ['VulcanPinch','Vulcan Pinch','',{_target setDamage 1;},{true}] call ace_interact_menu_fnc_createAction; [(_this select 0), 0, ['ACE_MainActions'], _action] call ace_interact_menu_fnc_addActionToObject; x3 = [(_this select 0), 0, ['ACE_MainActions'], _action];";
        };
    };
};
```

**Comment by Benargeez** [comment]
Ah, Thanks for the info. Hopefully this answers other people's questions. I guess documentation is lacking at this point. Thank you for the swift reply. 

P.S. Where is the best place for people to chat with devs about the more technical details? Do you guys have a Skype, HipChat or your own Forum?

**Comment by PabstMirror** [comment]
Take a look at: #429

**Comment by Benargeez** [comment]
Thanks!
