### ISSUE TITLE
fnc_addActionToObject: Problem with passing parameters

### ISSUE THREAD

**Issue by szpolny** [acemod/ACE3#9111]
**Mods (complete and add to the following information):**
- **Arma 3:** `2.10.149954` [e.g. 1.00 stable, rc,  dev]
- **CBA:** `3.15.8` [e.g. 3.0.0 stable, commit hash]
- **ACE3:** `3.15.2` [eg. 3.0.0 stable, commit hash]

**Description:**
I pass object to fnc_addActionToObject, but it tells me that im passing string.

**Steps to reproduce:**
_Follow [https://ace3.acemod.org/img/wiki/user/issue_flowchart.webp](this flowchart)!_

1. _Go to 3DEN Editor, and play the scenario
2. _Click ESC and pass code to Debug Console
```
_action = ["cutTree","Cut down a tree","",{[_player, _target] execVM 'functions\____.sqf';},{[_player] call _____;}] call ace_interact_menu_fnc_createAction; 
_terrainObjects = nearestTerrainObjects [[worldSize / 2, worldSize /2, 0], ["Tree"], worldsize / 2]; 
{ 
  _object = _x;
  _modelInfo = getModelInfo _x; 
  _model = _modelInfo # 0; 
  if (_model == "t_ficusb1s_f.p3d") then { 
    [_object, 0, "ACE_MainActions", _action] call ace_interact_menu_fnc_addActionToObject; 
  }; 
} forEach _terrainObjects;
```

**Expected behavior:**
Add action to all trees on map

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) 

**Screenshots:**
https://i.imgur.com/FEJm9xd.png

**Comment by PabstMirror** [comment]
`["ACE_MainActions"]` instead of `"ACE_MainActions"`

but ace will try to add a mainAction and fail because typeOf object is ""
```
 Error position: <setVariable [_objectType, _actionTrees];>
 Error Reserved variable in expression
 File z\ace\addons\interact_menu\functions\fnc_addActionToClass.sqf..., line 62
```
interaction menu really isn't designed to work with objects with no type,
and adding actions to 400k map objects will probably have problems

I think the best bet is to do something like mine defuse or logi wirecutters and dynamically add actions via proxy objects
e.g. https://github.com/acemod/ACE3/blob/master/addons/logistics_wirecutter/functions/fnc_interactEH.sqf
