### ISSUE TITLE
ACE breaks inventory interface

### ISSUE THREAD

**Issue by RobertSandiford** [acemod/ACE3#9163]
**Mods (complete and add to the following information):**
Latest ArmA 3 stable, and whatever CBA and ACE3 is on steam workshop. I don't know what versions they are.
No other mods.

**Description:**
ACE breaks the UI for dragging the 1st item from another unit's uniform/vest/backpack. After dragging and dropping the item in the same place, or anywhere the doesn't cause the item to move, the UI will break, not allowing dragging that item against, until that container is closed and re-opened.

Only affects the first item. Might be related to the recent ArmA fix where the ID of the first item in a listbox was fixed (previously showed row index 256 IIRC).

**Steps to reproduce:**
1. New Mission
2. Place player
3. Place NATO missile specialist
4. Play
5. Shoot missile specialist
6. Open inventory on him
7. Open kitbag (backpack)
8. Drag Titan AT missile, and drop it again, still in the backpack

Result: UI has now broken, no longer possible to drag the Titan AT Missile, missile text has turned red.

**Expected behavior:**
UI to continue working

**Where did the issue occur?**
Editor

**Log Files:**
Client RPT: https://pastebin.com/8zcWWj5a

**Additional context:**
Checked with vanilla and CBA - occurs only after ACE is added.

**Screenshots:**
N/A

**Comment by BaerMitUmlaut** [comment]
Afaik this happens in vanilla too and is one of its oldest bugs.

**Comment by Xaneas** [comment]
Hello, Author of Better Inventory here.

Can confirm this Bug is still a thing.

When the Item you drag is not put somewhere the item will bug out with red text.
onLBDrag eventhandler says the item has a lbValue of 127.

Testet with only cba and ace activated.
This bug doesn't occur in vanilla or with cba.

This is causing the bug:
https://github.com/acemod/ACE3/blob/master/addons/inventory/functions/fnc_inventoryDisplayLoad.sqf#L76
Line:76 asks if the value is not the same as DUMMY_VALUE (127).
Line:78 changes the value 0 to DUMMY_VALUE (127).
I testet it without this and the bug is fixed.

For the moment i will try to work around this bug for my mod, but it would be nice if someone could fix it.

**Comment by RobertSandiford** [comment]
@Xaneas Sounds correct

> Might be related to the recent ArmA fix where the ID of the first item in a listbox was fixed (previously showed row index 256 IIRC).

I guess it was 127 not 256.

I suppose you can submit a pull request for it.

**Comment by Xaneas** [comment]
The question is what the code is for.
I haven't looked through it enough and never realy looked much into the code of ace.

**Comment by RobertSandiford** [comment]
> The question is what the code is for. I haven't looked through it enough and never realy looked much into the code of ace.

There was an ArmA bug where the first item was marked as position 127 instead of 0. The ACE code was to workaround the ArmA bug. The ArmA bug was fixed, so that code can be removed from ACE.
