### ISSUE TITLE
Dragging - Script error in XEH_postInit

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#9385]
On dedicated server
```
18:23:23 Error in expression < _unit = (getUserInfo (_this select 5)) select 10;
        _unit call ace_dragg>
18:23:23   Error position: <select 10;
        _unit call ace_dragg>
18:23:23   Error Zero divisor
18:23:23 File /z/ace/addons/dragging/XEH_postInit.sqf..., line 8
```

**Comment by jonpas** [comment]
Comes from this https://github.com/acemod/ACE3/commit/9505d4c47ef56e9c214b89b8d0768d986526c96b#diff-baccfba963e58cce5d824d01073bc7cc39f05a4a36030b6b9923904f6b7126c9 which added [`getUserInfo`](https://community.bistudio.com/wiki/getUserInfo), but that command "Returns an empty array if said player is not found".

This is the exact same issue as https://github.com/OCAP2/addon/pull/31. :smile:

**Comment by jonpas** [comment]
@johnb432

**Comment by johnb432** [comment]
> Comes from this [9505d4c#diff-baccfba963e58cce5d824d01073bc7cc39f05a4a36030b6b9923904f6b7126c9](https://github.com/acemod/ACE3/commit/9505d4c47ef56e9c214b89b8d0768d986526c96b#diff-baccfba963e58cce5d824d01073bc7cc39f05a4a36030b6b9923904f6b7126c9) which added [`getUserInfo`](https://community.bistudio.com/wiki/getUserInfo), but that command "Returns an empty array if said player is not found".
> 
> This is the exact same issue as [OCAP2/addon#31](https://github.com/OCAP2/addon/pull/31). 😄
> 
> It is not a reliable use, especially when players force disconnect or crash.

@jonpas

What do you propose? The fix you implemented for OCAP2 is a solid base, but should I revert the EH change instead? I think `HandleDisconnect` (old EH) *might* be able to handle force disconnections and crashed better than `PlayerDisconnected`, but I'm really not sure. I ran a test where I cut off the internet connection to the connected client and `HandleDisconnect` returned the correct unit (I did not check `PlayerDisconnected`).

The reason why I changed the EH is because I thought `HandleDisconnect` triggered too late. In reality it's fine, I had forgot to take something into account. So the change was unnecessary and it's probably a good idea to revert back to the old EH.

I'll make a PR reverting to the old EH if nobody objects.

**Comment by jonpas** [comment]
Ideally if unit no longer exists, the system should still handle that gracefully.
