### ISSUE TITLE
In game 3D sights & lasers bug

### ISSUE THREAD

**Issue by Stardekiller** [acemod/ACE3#9665]
**Mods:**
- **Arma 3:** `2.14`
- **CBA:** `3.16.1.231025` 
- **ACE3:** `3.16.1`

**Description:**
Once in Game, changing lasers from IR to visible doesn’t seem to work, even if you switch key binds. It also happens with the 2D to 3D sights. It seems to bug the 3D sights so it immediately changes into 2D once you try. Laser modules (changing from Visible laser to IR laser) doesn’t even work at all

**Steps to Reproduce**
Host a Mutliplayer Game
Equip a weapon with an ACE3 Sight and ACE3 laser module
Try out the default key binds: CTRL + - (NUM) & CTRL + L

**Expected behavior:**
A clear prompt on the right side of the screen indicating the change from 2D to 3D (in the case of sights) and from “Visible Laser” to “IR Laser” on laser modules. Expected to change the visual of the sights to become PIP and able to work with NVG. For lasers, the possibility to use a NVG visual Only laser or a visible one

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer) / Virtual Arsenal

**Comment by BaerMitUmlaut** [comment]
The switching is part of CBA, not ACE. You can manually switch them by double clicking the item in your inventory.

**Comment by johnb432** [comment]
> It also happens with the 2D to 3D sights.

There is no such thing as switching between 2D and 3D sights in ACE at the time of writing. You can't change from 2D to PIP and vice versa either.
I tried CBA's attachment switching functionality on CUP scopes and ACE lasers and switching between the different mode worked just fine, with a clear prompt on the right displaying to which mode you've switched to.

I'm going to close this issue, because this isn't the right place for it. If you think it's ACE fault, feel free to reopen and add additional information.
